### ISSUE TITLE
Issues while upgrading from Custom Learning for O365 to Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by BabalParihar** [pnp/custom-learning-office-365#101]
I am trying to update our existing custom learning for O365 site to the new M365 learning pathways. I have followed the following link to upgrade our site - https://docs.microsoft.com/en-us/office365/customlearning/custom_update. After the upgrade, when I try to add the new "Microsoft 365 learning pathways" webpart to the page, I get the following error:
Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance.

Below are the logs from the browser:
Message: InitService (setLearningSite) -- Tenant property 'MicrosoftCustomLearningTelemetryOn' has not been set.
Message: InitService (setLearningSite) -- Tenant property 'MicrosoftCustomLearningSite' has not been set.
Message: TypeError: Cannot read property '_url' of undefined - DataService (constructor)
Message: TypeError: Cannot read property 'lists' of undefined - DataService (getCustomConfig)
Message: TypeError: Cannot read property '_url' of undefined - InitService (validateLists)

Please let me know if there are any other steps which we need to upgrade the learning site. Kindly share any link with the complete steps if there is any.

**Comment by juliemturner** [comment]
@BabalParihar It sounds like you followed the entire readme and not just teh section pointed to "Updating the Solution": https://github.com/pnp/custom-learning-office-365/blob/master/README.md#updating-the-solution? Did you try and provision another site collection?

**Comment by BabalParihar** [comment]
We haven't tried provisioning another site collection yet. I will get that done and update you with the outcome.

Thanks,

**Comment by juliemturner** [comment]
@BabalParihar I was not suggesting you do so I was asking if you had because that might be part of the issue. You cannot have more than one site collection that you try to provision M365LP to. I’m also further looking to understand how you provisioned it originally. Base on the error messages it doesn’t feel like it could ever have been working as those things it’s saying are missing are fundamental for it to work and not related to updating the solution so I’m just trying to get a full picture so I understand how to direct you.

**Comment by BabalParihar** [comment]
@juliemturner  Last year around June, we had worked with Microsoft to setup the Office 365 learning site in our tenant. They had provided an executable package (EXE) which automatically created the learning site and pages in the site. 

Now, they have shared the following link to update the old learning site to Microsoft 365 learning pathways. - https://docs.microsoft.com/en-us/office365/customlearning/custom_update

We have followed all the steps under [updating the solution](https://github.com/pnp/custom-learning-office-365/blob/master/README.md#updating-the-solution) section only. After that we tried to add the "Microsoft 365 learning pathways" webpart to the page.

Please let me know if we need to follow other steps mentioned in the "[Manually installing and configuring Microsoft 365 learning pathways](https://github.com/pnp/custom-learning-office-365/blob/master/README.md#manually-installing-and-configuring-microsoft-365-learning-pathways)" section too.

Let me know if you need any other details.

**Comment by juliemturner** [comment]
@BabalParihar -- From what you're telling me it sounds like you had gotten involved in a very, very early beta program. Things have evolved significantly since then. If you aren't married to any customizations you've created, etc, etc... then I would start from scratch by provisioning a new Microsoft 365 learning pathways site collection using the [Microsoft Provisioning service](https://provisioning.sharepointpnp.com/).  When on that site, navigate to "Solutions" and select "Microsoft 365 learning pathways".  If you have problems provisioning the site you get help from sp-dev-docs by submitting an issue to that [repo](https://github.com/SharePoint/sp-dev-docs/issues).  

If that's not the route you feel you'd like to take then I suggest you get in touch with the Microsoft representative who you dealt with during that period so that they can direct you appropriately.

**Comment by juliemturner** [comment]
closed to inactivity
