### ISSUE TITLE
Unable to provision Microsoft 365 Learning pathways in our Online tenant

### ISSUE THREAD

**Issue by madhugooty** [pnp/custom-learning-office-365#102]
#### Category

- [ x] Bug

#### Expected or Desired Behavior

Set up Microsoft 365 Learning pathways in our tenant

#### Observed Behavior

Unable to provision Microsoft 365 Learning pathways in our tenant

#### Steps to Reproduce

1)	Followed the steps in the MS official article below
          https://docs.microsoft.com/en-us/office365/customlearning/custom_provision
2)	We get an error ‘Sorry, something went wrong’ at step  ‘Add to your Tenant’ (  attached document has detail)
3)	Please note that we get this error even after all the pre-requisites mentioned in the article are met 

#### Additinoal Information

Our tenant is SharePoint Online Dedicated and we have vanity URLs. 

[Provision Microsoft 365 learning pathways.docx](https://github.com/pnp/custom-learning-office-365/files/3406233/Provision.Microsoft.365.learning.pathways.docx)

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@madhugooty -- Unfortunately your issue is related to the SharePoint online provisioning service and not Microsoft 365 learning pathways which means we have no expertise to be able to assist you. You will need to submit this issue to their repository to get assistance which is at https://github.com/SharePoint/sp-dev-docs/issues.
