### ISSUE TITLE
When will the Learning Pathways be released - currently in beta

### ISSUE THREAD

**Issue by clayjam** [pnp/custom-learning-office-365#108]
- [ ] Question
The Learning Pathways is currently in Beta and has been for a while. When will be available as a full featured product ready for production environments ?

Looking to install in client environments and they won't install anything that is in beta for good reason.

Will the production released version require a re-provision if I already have the beta version installed ?

**Comment by praywin-Sol** [comment]
looking for answer to same question.

**Comment by juliemturner** [comment]
We expect to remove the beta label in the coming months but do not have a firm date for release. Please consider the following as you evaluate, plan and implement Microsoft 365 learning pathways:


- As with any Beta solution our service management team reserves the right to make changes to the service and its components. As we are actively resolving bugs and UX issues you would likely need to update the WebPart.

- To update the web part you will need to download it from our GitHub repository and upload it into your tenant app catalog. Please see the "[Updating the solution](https://github.com/pnp/custom-learning-office-365#updating-the-solution)" section of the Microsoft 365 learning pathways Readme file.

**Comment by praywin-Sol** [comment]
Thanks @juliemturner . Really appreciate it. Please can you help me to advise on any document that can provide the term and condition of the usage of permission granted during PNP provisioning. I have created a ticket with Microsoft support and they have directed me on this forum since Learning pathways is on opensource. I am looking for document that can specify why learning pathways need full permission on all site collection. I am working for government organization. We need to know if this solution "READS" all our data in the SharePoint tenant, We have NO issues in accepting terms and condition as we like the product. However as end user we need to know what will be the usage of permission. 

Sorry for long post !!

**Comment by praywin-Sol** [comment]
Thanks @juliemturner  for the link. Let me check .

**Comment by juliemturner** [comment]
Learning pathways has been GA'd as of Ignite 2019
