### ISSUE TITLE
Multiple instances of Learning Pathways

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/custom-learning-office-365#112]
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
After implementing Learning Pathways for a department, I deployed another instance in another department. I am doing manual deployments (Web Part and PowerShell).Each department has its own site collection on SharePoint Online.
Each department is expected to have its own learning content that doesn't apply to the other department.

#### Observed Behavior

The playlists and assets are global, and displayed on all deployed instances of Learning Pathways. I don't see a way to target a playlist to a specific department. Am I missing something?

#### Steps to Reproduce

Deploy Learning Pathways manually to two site collections. Add a playlist to a site collection and it will show up on the other site collection too.

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@PathToSharePoint  -- Your issue is because M365LP can have only one 'master' site collection.  This site collection is where the admin web part (CustomLearningAdmin.aspx) will load and the custom playlists and assets will be stored. In the scenario you outline above the master is currently set to the last site collection you created, as it overwrites the TenantApp property that defines which site collection is the master. You can then add the web part to any other site collection and if you want to limit the playlists shown in that site collection use the 'custom subcategory' ability and then pin the web part to that subcategory by configuring the web part properties.
