### ISSUE TITLE
Changing the Search button

### ISSUE THREAD

**Issue by Rafou2** [pnp/custom-learning-office-365#123]
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Currently in Learning Pathways, the user want to use a search function on the home page.

#### Observed Behavior
Currently in Learning Pathways, the search field on the home page actually searches in the SharePoint library, not in the training content. The actual training content search field only appears when you are already in the training pages. This is very misleading and I got a few user complains. 
Could you either :
- hide the SP search OR
- replace it with the training content search

#### Steps to Reproduce
Always behave that way

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@Rafou2 - Unfortunately what you're looking for is not possible.  SharePoint search cannot be hidden because we cannot modify the page in that manner and we also have no ability to make that search box function differently.  The search functionality is particular to the repository that the web part exposes and therefore the only way we have to manifest search functionality is within the confines of the web part canvas.
