### ISSUE TITLE
Custom Playlist issue

### ISSUE THREAD

**Issue by jswiftca** [pnp/custom-learning-office-365#126]
#### Category
- [X] Question
- [ ] Bug
- [ ] Content

#### Expected or Desired Behavior
I want to use a Custom Playlist instead of, or before, the "Six Simple Steps - Welcome to Office 365"  I added the custom playlist to "First Days" 
#### Observed Behavior
I am not able to see the playlist when I enter the URL  of the custom playlist, replacing the link for 6 simple steps

**Comment by juliemturner** [comment]
@jswiftca  -- Sorry I think I'm not exactly following your question but to address your expected/desired behavior if you want a custom playlist to replace a Microsoft provided playlist you need to recreate it and then hide the Microsoft one.  So in this scenario you'd create a new custom playlist in first days, populate it as you want and then hide six simple steps.  Once that'd done you can go back to a page where you have the web part and refresh it and that should then show you your new desired state. Also, in an upcoming release we will have a "Copy Playlist" function to allow you to start with an exact copy and then modify vs having to build it entirely from scratch.

**Comment by jswiftca** [comment]
Many thanks for the quick response, Julie.
I had done what you suggested and the title of the Custom playlist did show, but the webpart did not appear as a playlist, just the title of the play list, with no way to see the items in the play list.
I suspect I entered an incorrect URL.
It would be easier if, when we have to enter a play list URL, there was a drop down of choices for available playlist. With a selection of the desired playlist, the appropriate URL or other entry was made.
Thanks again
Jim

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by juliemturner** [comment]
@jswiftca -- I would absolutely like to help you but I'm not following your issue. I think you're saying when you're on a playlist you can't see the other items in the playlist, you're just looking at an asset?  Have you tried clicking on the "Burger" menu?

![image](https://user-images.githubusercontent.com/7570936/65458731-40da2700-de1c-11e9-8a60-304308439b38.png)

**Comment by jswiftca** [comment]
Sorry to be less than clear about the problem. I am not a sharepoint expert, but I did not think that was needed to start customising Learning Pathways.
I hid the playlist Six Simple Steps as you see below:

[LP1.PNG]
But I now have to replace the link in the capture below with the correct URL.

[LP2.PNG]

And that's where things seem to go wrong.
When I hit the change button. I cannot find the custom playlist I created "First Steps with your account" It is not listed in the available pages.
It seems I need to learn a lot more about the basic structure of things in order to understand what's going on behind the scenes.

I have never seen anything resembling the image in your screen capture.
Jim
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jswiftca** [comment]
A PS to the previous letter. I just watched your video again and found the screen capture you included in this message.
My Custom Play lists works perfectly OK in that view.
So the problem now seems to be the much simpler on of how to find the URL to the play list that replaces the 6 steps playlist.

Jim
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by juliemturner** [comment]
@jswiftca  -- I think the reason you're not seeing my images is that you're not using the GitHub UI you're responding to an email.  And then sadly now I don't see your images, for the best experience please go to [GitHub Issues List #126](https://github.com/pnp/custom-learning-office-365/issues/126) to respond. 

So, that all said, first you do not need to have SharePoint expertise to use learning pathways. Unfortunately, I'm really still not following your issue, which may be because I can't see your screenshots. Let me attempt to answer your question anyway. If you've added a custom playlist in the admin page **{url to your pages library}/CustomLearningAdmin.aspx** then when you go to a page with the viewer web part or the built-in page **{url to your pages library}/CustomLearningViewer.aspx** that new custom playlist should show up. In the screenshot, I have a custom playlist called "My new Six Simple Steps"

![image](https://user-images.githubusercontent.com/7570936/65531614-4a20cd80-dec8-11e9-9101-8f2adeaa3d34.png)

Now if I go to the viewer page and navigate to "First Days" I see my custom playlist and do not see Microsoft's Six Simple Steps playlist.

![image](https://user-images.githubusercontent.com/7570936/65531695-73415e00-dec8-11e9-9b14-65aab41f6733.png)

If I then want a link I would click on my playlist and use the "link" button we discussed above to get a link to it.

You could do this on any page with the M365 learning pathways web part on it as long as you didn't configure the web part properties to have it be in "Content Only" mode which hides the menu at the top which includes the ability to get the link.

I hope that helps.

**Comment by jswiftca** [comment]
Many thanks. Problems solved :-) 

I had to use a link to the first asset in my playlist, instead of being able to select a Page from the collection of pages presented when I clicked Change to change the setting in this screenshot. 

![LP2](https://user-images.githubusercontent.com/54451846/65536784-ed69e680-deb8-11e9-8cae-a1db19ff9424.PNG)

Once I saw how to get the link for the playlist, everything clicked. 
I greatly appreciate the help.  Many thanks
