### ISSUE TITLE
Information about the Learning Pathways site planned downtime ?

### ISSUE THREAD

**Issue by Rafou2** [pnp/custom-learning-office-365#132]
#6 ## Category
- [x] Question
- [ ] Bug
- [ ] Content

#### Expected or Desired Behavior
The Learning Pathways site should be able to be accessible for users at all times (we have users in all time zones). Any downtime should be announced in advance.

#### Observed Behavior
On September 27, early in the morning around 7 UTC time, we experienced that the site content was empty and not showing any of the playlists. When checking later around 9 UTC, everything was back to normal. Was this due to a refresh of some of the site Microsoft content or a planned downtime ?

#### Steps to Reproduce
NA

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@Rafou2  -- First, I'm very sorry you experienced downtime. However, it's not entirely clear what you mean by "the site content was empty and not showing any of the playlists"... that could mean a lot of things.
- The URL for the site showed a blank page
- the page loaded but the learning pathways web part showed and error or no content
- the web part showed the icons for content and you could navigate to a playlist but the iFramed playlist content wasn't loading

Because of that, I cannot directly address your issue, however, if it was any of those three things, it's really out of our hands. 

The site collection showing a blank page is an issue with SharePoint online having some sort of issue loading the site or sites in your tenant and that may be related to something internal to your organization, your internet connection, or SharePoint itself could have experienced downtime. 

If the web part wasn't loading content that could have been a result of an issue with where the content is hosted, which is GitHub, I've checked and no outages were reported for Sept 27th, although that could still have been the issue. 

Finally, if the web part loads but the iFramed playlists assets aren't loading that could again be an issue within your network temporarily blocking and/or the support.office.com site or docs.microsoft.com site having issues.  

Given the way, the solution is architected, there is no "downtime" that we could or would ever schedule. The only possible way we could have caused an outage would be to have removed or moved the manifests from the source entirely and then, in that case, everyone would have experienced downtime. I can tell from our logs that didn't happen in this case either by myself or anyone else on the team.

**Comment by Rafou2** [comment]
Thank you Julie for your quick reply.
The symptoms were actually that the page loaded but the learning pathways web part showed no content (see image). I understand that this could have been by several local network reasons, and I can confidently say to the client that this was not linked to Microsoft activities since no other such site had the same experience.

Best regards
![LP site content not showing](https://user-images.githubusercontent.com/50907271/65951040-865fab00-e43f-11e9-8cbc-b7cd5fa38276.jpg)

**Comment by juliemturner** [comment]
@Rafou2 -- Based on your screen grab that would appear to be either an outage of GitHub (which I confirmed at least was not reported) or something blocking the manifest.json file from downloading which I have seen happen because of issues with network hardware. If this happens again your best bet is to review the network tab of the browser's developer console to see what the error is so that it can be investigated further.
