### ISSUE TITLE
hide a playlist and it hides all and only shows the hidden

### ISSUE THREAD

**Issue by kyleg11** [pnp/custom-learning-office-365#135]
This issue is still there since day 1 and happened again this morning. If you have a playlist hidden than it hides all and shows the hidden one (a toggle that is doing the opposite of what it should). The only workaround is to hide something new go out hit refresh a couple time and all show but hidden, go back and uncheck the new hidden (that you just used as a workaround "trigger" for this), and than it's back to normal. This happens some mornings when coming in and I would say it occurs (since we do have some MS dynamically pulled content hidden), 5 times a month

**Comment by juliemturner** [comment]
Can you please validate that you have the latest version of the web part https://github.com/pnp/custom-learning-office-365#current-release-version

**Comment by ec-alm** [comment]
Hi @juliemturner - I've found exactly the same behaviour on the following version (fresh install)

Version | 2.0.15.0
-- | --
Release Date | September 2019

**Comment by juliemturner** [comment]
The current version of the web part is 2.0.17, please see here to update:
https://github.com/pnp/custom-learning-office-365#current-release-version

After you've updated let me know if you're still seeing the same behavior.

**Comment by kyleg11** [comment]
I will look at upgrading to version 3, since that appears to be a critical update. I see the notice on back up of content and assume that the content that is custom and added will remain? and this will just install over? We do have sharegate and I can try and backup, but just wondering if this was tested as a install on top and custom content is thought to be fine? Right now, it appears that some update came in with new content (that's great) but completely hid my stream section section (custom) it's in the admin, but I can't seem to get to show. It also appears to have added accessibility under all the other O365 applications (not the right spot for it) ...Hopefully the update will repair this?

**Comment by juliemturner** [comment]
The bug referred to in this thread should be fixed by 2.0.17.

To address your other questions, Yes version 3 is out and the update makes several schema changes to the content. We have tested it with custom content and the update worked fine in our testing but it's always good to have a backup so you can restore the list items if necessary, give you have ShareGate that's a great answer if only to copy the list items to backup lists in the same site. 

The v2 content was also updated, so you can get a content update without moving to version 3 of the web part. I would like to stress that content updates are completely decoupled from web part updates, so if you expect a web part update to fix content issues that will not happen.

For any issues I didn't address please open a new issue as they are unrelated.
