### ISSUE TITLE
Editing one instance of the Learning Pathways web part affects the other ones

### ISSUE THREAD

**Issue by SJHCtrain** [pnp/custom-learning-office-365#137]
This is frustrating ...

I add the Learning Pathways webpart to different pages, and when I make an edit to one of these pages, it changes what is dipslayed by the webpart on the other pages.

I have my main Learning Pathways administration set up from the home page and then when I go to add the webpart to a new page and make changes (on that new page) the edits filter through the other pages that have the webpart.

For example, I thought I could set up a page dedicated to Word, insert the Learning Pathways webpart, and then edit that webpart to ONLY show Word content.

However, when I make changes it flows to other pages that have the webpart. 

It appears that the latest changes I make affect the Learning Pathways MIcrosoft learning administration Playlist administration off of the main page.

Is it possible to add customized Learning Pathways webparts?!!

**Comment by juliemturner** [comment]
@SJHCtrain -- I'm sorry but what you described doesn't really make sense to me.

Learning pathways administration can only be done from the administration web part which can only be on one page in the site collection and that page is automatically created for you... The administration web part isn't even available in the gallery, the only way you can get it on a new page is by using powershell, but don't do that. 

I also wouldn't make the CustomLearningAdmin.aspx page the home page of the site because only admins can access it, that wouldn't be ideal user experience.

As far as adding the viewer web part to multiple pages, yes, you can do that and you configure the web part by changing the web part properties to filter it to show only the category, sub-category, or playlists you want to show on that page. You can even add multiple instances of the web part to a page all configured differently. 

So for example, create a page in your pages library, call that page "Word" and then edit then add the learning pathways web part to it, edit the web part properties to filter the content to the sub-category "word". Apply the changes and save the page.
Now create a second new page in the pages library, call that page "Excel" and then repeat the process setting the web part properties to filter the content to the sub-category "Excel".  Those two pages will show the word content or excel content depending on what page you're on every time... changing the filter of one web part to "Excel" on the Excel page will not change the web part settings of the Word page.

If you're still having issues maybe you can create a short video depicting what you're seeing so that I can better understand what the issue is.

**Comment by SJHCtrain** [comment]
Hi there,

Here's video.
[PlaylistAdmin.pptx](https://github.com/pnp/custom-learning-office-365/files/3712953/PlaylistAdmin.pptx)

**Comment by juliemturner** [comment]
@SJHCtrain -- Thanks for the video, that helped me understand what you were trying to accomplish.  I think the disconnect is that the administration web part is to administer the entire content set. Hide/Show is only meant to hide/show content that you don't want anyone in your organization to see at all, ever...  things like, we haven't rolled out Teams as an organization so we'll hide it so it never shows up.

On your "Introduction to Office 365" Page you talked about just wanting to show "Office 365" but you seemed to be happy when it showed both First Days and Office 365. At no point did you try to edit the web part properties to accomplish this as I mentioned in my above answer so I'm not sure if you're unhappy with that answer or you're not following me.

Without hiding Outlook, and assuming you want both "First Days" and "Office 365" to show, you could get a similar thing by adding the web part to the page twice. In the first instance set the web part properties to filter to the Sub-Category "First Days" and then in the one below it, set it to filter to the sub-category "Office 365".  If you didn't want to show "First Days" then you only need one web part and you just edit the web part property to filter it to "Office 365". Here's a screen shot of setting the web part property.

![image](https://user-images.githubusercontent.com/7570936/66583353-2eb4f400-eb51-11e9-80ab-4d3c8ffba146.png)

**Comment by SJHCtrain** [comment]
[PlaylistAdminII.pptx](https://github.com/pnp/custom-learning-office-365/files/3730320/PlaylistAdminII.pptx)
 I've added some more examples to help clarify.

**Comment by juliemturner** [comment]
@SJHCtrain  -- You are still trying to use the "administer playlist" link, which takes you to the learning pathways administration web part to customize what one instance of the viewer web part shows. This is NOT how administrating playlists is meant to work. Please see the attached screen shot for how to edit a web part property which is the correct way to accomplish what you're asking for.

![image](https://user-images.githubusercontent.com/7570936/66852088-094d2f00-ef31-11e9-8903-bd2f1cf7239e.png)

Then change the filter so that it filters to the sub-category "OneDrive"

![image](https://user-images.githubusercontent.com/7570936/66852189-3dc0eb00-ef31-11e9-81a4-10581f28a58c.png)

**Comment by SJHCtrain** [comment]
... mind ... blown ...  ;-)

So when Custom Playlist content is are added, they are available throughout the entire site and show up on the Playlist Administration. Now I've got to go back and zero in on how to use categories, and sub-categories.

THANKS Julie!

Do you have a link to detailed documentation for LearningPathways as I didn't grasp this concept when going through the online documentation.

Craig

**Comment by juliemturner** [comment]
@SJHCtrain  -- Glad you were able to get clarity.  
Here's the documentation about adding and setting the properties of the custom web part.
https://docs.microsoft.com/en-us/office365/customlearning/custom_addwebpart
