### ISSUE TITLE
Inserted learning webpart but more are showed. We would like to have user see specific contents only.

### ISSUE THREAD

**Issue by PriscillaWP** [pnp/custom-learning-office-365#139]
#### Category

- [x] Question
- [] Bug
- [] Content

#### Expected or Desired Behavior

Inserted learning webpart (subcategory) unfortunately the links are still showing on the webpart where user could select or get confused which to click.

Can we select a subcategory and when a webpart is inserted to a site page, it will not show extra links other than the selected contents?

#### Steps to Reproduce

??

**Comment by juliemturner** [comment]
@PriscillaWP  -- updated your question to use the template.

As far as it goes I'm not really sure what you mean by "links" but if you mean the breadcrumb navigation then you probably want to change the Web Part Mode to "Content Only".  But maybe that isn't what you're referring to.

**Comment by PriscillaWP** [comment]
Hi Julie,

         Thanks for your reply. Yes I am referring to the breadcrumb. I did tried the content only mode. However, each time the user click on the webpart, it will redirect user to the Learning pathway site which is out of the sharepoint page. We would want the content to be display in the webpart without redirect out of the sharepoint page. Is there any workaround to use Content only and the content will be display in the webpart itself not redirect out of the webpart? Appreciate your answer. Thanks.

**Comment by juliemturner** [comment]
So yes, in the current version of the web part this is a limitation as the way the navigation was originally designed by putting the part in content only mode you lost the ability to control the playlist well. The next release will change that paradigm and this redirecting will be removed because the playlist nav will be updated.  So, for now, there is no workaround, you either leave the nav or you deal with the redirect.

**Comment by PriscillaWP** [comment]
Noted with thanks dear Julie. Have a blessed day.
