### ISSUE TITLE
Hide Hub Navigation from Custom Assets

### ISSUE THREAD

**Issue by FlorianReinprecht** [pnp/custom-learning-office-365#140]
#### Category
- [ ] Question
- [x] Bug
- [ ] Content

#### Expected or Desired Behavior

The Hub Site Navigation of a custom asset should be hidden. 

#### Observed Behavior

Currently, if a hub-joined SharePoint Page is used as a custom asset, the Hub Navigation is still shown. (Basically, there can be two Hub Navs if the WebPart itself is also joined in a Hub and users can navigate to other pages via the navigation.)

#### Steps to Reproduce

Use a hub-joined Page as a custom asset and take a look at the playlist where it is used.

**Comment by juliemturner** [comment]
@FlorianReinprecht  -- So because the content is being iFramed into the page what you're really experiencing is a limitation of how SharePoint handles its pages being iFramed. That said, in an upcoming release we will be overriding the content to hide the entire header and therefore this issue will go away.

**Comment by FlorianReinprecht** [comment]
@juliemturner - thats what i thought. 

Thank you for the information. Then i will be looking forward to this upcoming release.

**Comment by juliemturner** [comment]
Complete header now hidden for custom assets in SharePoint tenant.
