### ISSUE TITLE
Excel module [Create a drop-down list] has video link duplicate of [Fill data automatically]

### ISSUE THREAD

**Issue by bengtmoss** [pnp/custom-learning-office-365#154]
#### Category

- [ ] Question
- [x] Bug
- [ ] Content

#### Question / Expected or Desired Behavior

In Home > Excel > Intro to Excel > Create a drop-down list, the video should fit the module title.

#### Observed Behavior
In Home > Excel > Intro to Excel > Create a drop-down list, the video is "Fill data automatically"
#### Steps to Reproduce
In the MLP Viewer, navigate to Home > Excel > Intro to Excel > Create a drop-down list.
Please note: This is a copy of issue #119 [https://github.com/pnp/custom-learning-office-365/issues/119](url), which was closed with the message "Content has been refreshed closing this issue.". Upgrading to 3.0.1.0 changes nothing - the behavior is exactly the same as before and the bug has therefore not been removed.
#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
To make sure there's clarity, the version of the web part has nothing to do with the content, they are completely decoupled.  This is a content issue and I'll reassign it as I was told this was fixed with the content refresh that happened at Ignite 2019 which coincided with the solution going GA as well as the version 3.0.0 web part.
