### ISSUE TITLE
Consistent breadcrumb navigation for custom sub category?

### ISSUE THREAD

**Issue by ian365** [pnp/custom-learning-office-365#163]
- [x ] Question

Hi there, we've had to add a custom sub category and put together content for Skype. The breadcrumb of a custom sub category does not include a link back to Home > Products >  (the top level will be the Custom Sub category).  Please can this be consistent with the other products? thanks

**Comment by juliemturner** [comment]
In general, what the breadcrumb nav does depends entirely on the web part mode.  If you have it set to content only it will not include full breadcrumb navigation, maybe that's what you're experiencing because regardless if it's a custom sub-category or not the navigation should work the same and during my testing it does.

![image](https://user-images.githubusercontent.com/7570936/70075975-d556c780-15cb-11ea-80d1-c1d24f472997.png)

**Comment by ian365** [comment]
Thanks for the explanation. Please see the video below, loading the webpart for standard OneDrive content and then switching to standard SharePoint subcategory with custom playlist or Skype custom sub cat, the banner and title for OneDrive remains displayed and does not update.

Separately, as mentioned above, when accessed via a link to the Skype Playlist page the breadcrumb for the Skype custom sub category does not show Home > Products >.
When accessed from playlist tiles then the the full breadcrumb will display. Should I be linking in a different way and can either of these be addressed?

![navigation](https://user-images.githubusercontent.com/56627514/70163972-45db1280-16b8-11ea-8f63-427c6c8bc51f.gif)

**Comment by juliemturner** [comment]
Ah, ok... the full explanation helped me understand what you were referring to.  Yes, I see your point and that is probably some leftover not ideal implementation from one of the preview versions. I will update it so that if the content is a link or the web part is pinned to a particular piece of content that will be the starting point for the breadcrumbs.  If not then the content will start with "home", and will not add the "Category" as a step in the breadcrumbs as it's not really a place you can come back to in that instance.
