### ISSUE TITLE
[QUESTION] Custom Content - Adding more material

### ISSUE THREAD

**Issue by pkbullock** [pnp/custom-learning-office-365#169]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [X] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**

I'm looking to install in a set of curated playlists and asset, still based on the Microsoft support material, as you have done for the pre-installed curated content. Ideally, i am starting to deploy to clients where id like to focus the content on activities relevant to them.

For example, i have a list of content about the modern editing experience with SharePoint Online, so wanted to create a playlist and select the support articles based on that subject. Ideally, i would like to install these by script (i'm quite familiar with PnP PowerShell) rather than manual, to make this reproducible and repeatable.

From what i understand of the solution the JSONData column contains all the metadata for CustomAssets and CustomPlaylists, just needs to have these items added/correctly configured in order to include them?

Is that the best way of doing it? Or do you have any guidance around this? Or any details around the schema info for the JSONData column?

**Comment by juliemturner** [comment]
So if I understand you correctly you want to create the custom playlists and/or custom assets by PowerShell so that anyone that runs the PowerShell would have those playlists and assets added to their implementation of learning pathways? If that's what you're saying then yes, you can use PowerShell to do this, however each of the "support articles" you link to must be custom assets unless they're already included in the assets.json file.  If they're not you're going to need to make sure you add the query string parameters so that they appropriately iFrame themselves and then also make sure that you capture the IDs of the assets as you add them so you can update the JSON payload of your playlist.  It's not impossible to do but there's work there.  As far as the structure there is documentation now in the partner section: https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint

**Comment by pkbullock** [comment]
This is perfect, thank you!

**Comment by juliemturner** [comment]
@pkbullock  -- is there a reason you reopened this?

**Comment by pkbullock** [comment]
Hi @juliemturner,

Sorry, went into impromptu meeting...

https://docs.microsoft.com/en-us/office365/customlearning/custom_partnerguide_contint 
I've been reviewing the docs and its not straight forward to get he associated GUIDs for the associated categories e.g.

- AudienceId
- TechnologyId
- SubjectId
- etc

Just wondering if this could be added to the docs or are they likely to change often?
I wrote a quick PS script to list these out which i could add to blog or share. Just thinking of making the process easier for the next person.

**Comment by juliemturner** [comment]
I'm not sure I follow you on what you mean by it's not straight forward to get the associated GUIDs, they're plain text in the metadata.json file... you can get them by either going to the [github repo](https://github.com/pnp/custom-learning-office-365/blob/master/docs/learningpathways/v3/metadata.json) or by looking at the network tab when the file is downloaded while using the admin web part. I'm not sure why you'd need PowerShell.  Maybe I'm not understanding the issue?

**Comment by pkbullock** [comment]
I think its just me just not connecting the dots and not applying enough thought into how this hangs together and reading through more carefully the manifest.json. 

I have however, managed to get the content pack setup and hooked into my fork and pulling into my  tenant now 😊. I will close this as i have managed to achieve what i was after. Thank you for coming back to me, sorry for the scatty responses.
