### ISSUE TITLE
How can I hide Admin Center category only for Learning Pathway admins?

### ISSUE THREAD

**Issue by pb762** [pnp/custom-learning-office-365#170]
**What is the context of your question?**
- [ ] Installation
- [ x] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
Me and a few other team members are in-charge of preparing the learning pathways content for our organization. How can I manage the visibility the Admin center category so only a select group of users can have access to it and not all the end users of the site?

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
By default users in the Members and Owners groups have access to the Admin Web Part, as it checks and will not render for others.  You could also if you feel it necessary change the item level security on the page in the pages library, which is not something I would do (simply because I think item level security is a bad practice as it can easily get out of hand) but is supported.
