### ISSUE TITLE
Menu Bar missing

### ISSUE THREAD

**Issue by fefaul** [pnp/custom-learning-office-365#176]
**What is the context of your question?**
- [ ] Installation
- [x ] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
In a fresh installation (Ver. 3.0.2), I can see the menu bar. Do I need to activate something to get it?

**Provide related screen-shots to help us understand your question**
![image](https://user-images.githubusercontent.com/29343331/71908426-43178580-316e-11ea-8236-3b3660d2ab2a.png)

**Comment by juliemturner** [comment]
Unfortunately, I have no idea how that would/could happen.  The site is created via the provisioning service and the issue you're seeing isn't related to learning pathways itself.  I attempt to look into it more and see if I can figure out how that might happen.

**Comment by juliemturner** [comment]
I was able to track the issue down to the Provisioning Service bug, which has been patched as of about an hour ago. If you have not done any customizations and would like to you can delete your site collection and remove the app from the app catalog and reprovision, otherwise, you will have to add the menu items manually.
