### ISSUE TITLE
[BUG] All custom content missing after updating from 2.0.13

### ISSUE THREAD

**Issue by lukasenz** [pnp/custom-learning-office-365#179]
We recently updated our app version from 2.0.13 to 3.0.2, but now every custom content we created is missing. 
In the Custom Learning Administration the custom subcategories still show up, but they are empty (no playlists). I also tried to re-create the playlists, but I can not find the assets with the search. 
The CustomPlaylists-,CustomAssets, and CustomConfig-lists are all still there.
Three custom playlists somehow "survived" and still are shown in the learning in preset-subcategories.

1. Install version 2.0.13
2. Update to version 3.0.2
3. All custom content missing.

**Comment by juliemturner** [comment]
So they're not all missing the ones that were in custom sub-categories are missing, is that a correct description? If so, can you please provide the payload of the field JSONData from the CustomSubCategories list item in CustomConfig list as well as the JSONData payload of one of the missing playlists.

**Comment by lukasenz** [comment]
All the ones that are still there are in preset-subcategories, but there are also some missing that were in preset-subcategories.

**Comment by juliemturner** [comment]
Ok, but still need that information to help you. So JSONData field for one of the missing playlists to start.

**Comment by lukasenz** [comment]
For example:
> {"Id":"10","Title":"When to use what","Image":"","Level":"Intermediate","Audience":"End User","Technology":"","Subject":"","Category":"Get Started","SubCategory":"When to use what","Source":"Tenant","Assets":["18","20","19"],"CatId":"7a2bc6ee-635a-410e-a5c1-e4b22471d8c7","Description":"Get an overview when you can use which Office 365 apps","StatusTag":""}

**Comment by juliemturner** [comment]
Oh, I see the problem. Not all of the playlists were updated to V3.  So, probably the easiest thing to do is to modify the JSONData for the CustomConfig to force it to update any that were missed.  
1. Have the CustomLearningAdmin.aspx page open.
1. In a new tab, open site contents and go to the "CustomConfig" list and show the information panel for the "CustomConfig" list item. 
1. Edit the value of the JSONData field, changing the value of CachedMetadata.Version.Manifest from "v3" to "v2". It's easiest to do this if you copy the contents out, paste it in a text editor, search for "Manifest" and then make the change and then paste it back into the JSONData field.
1. Switch back to the CustomLearningAdmn.aspx tab and refresh... then wait.  Don't click refresh multiple times, just let it run until it loads. 

This should then run through all the playlists and assets and complete upgrading all of them. If you look at the playlists you should see that they show "LevelId" instead of "Level" the ones that still show "Level" didn't get upgrades and therefore won't load into the solution.  If this doesn't fix the issue let me know and we can try and determine where it's getting stuck and if there's some sort of of bug in the upgrade that I can address.

**Comment by lukasenz** [comment]
First of all, thank you for the help!

There is 1 CustomConfig Item with "v3" and three with "v2".

I edited the part in the JSONData field from: 
`"Version":{Manifest":"v3","ManifestMinWebPart":"3.0.2","CurrentWebPart":"3.0.3"`
to 
`"Version":{Manifest":"v2","ManifestMinWebPart":"3.0.0","CurrentWebPart":"3.0.3"`

but after reloading the CustomLearningAdmin.aspx the value was change back to "v3", without changing the values in the other CustomConfig list items. They still have:

 `"Version":{Manifest":"v2","ManifestMinWebPart":"2.0.16","CurrentWebPart":"2.0.16"`

**Comment by juliemturner** [comment]
So the other CustomConfig list items may, if you're using it, be related to other CDN's... the primary one is related to the Default CDN and so "Default" will be in the CDN column.  If they all say Default, or the others are blank those list items can be safely deleted, you only need to keep the list item where the Manifest version say v3.  And yes, after you reload the CustomLearningAdmin.aspx page the value should go back to v3 because the upgrade ran.  What you're really looking to see is if those playlist that aren't showing up are now showing up and if not did the JSONData payload of those playlists get updated so that they show for instance LevelId vs Level.  If not then something is blocking the update of 1 or more of those playlists...

**Comment by lukasenz** [comment]
Unfortunately the playlists are still not showing up and are still showing "Level".

**Comment by juliemturner** [comment]
Ok, so something is wrong with the data somewhere or a bug in the code that most people aren't running into.  If you can repeat the experiment of changing the manifest version to v2, but this time when you refresh the admin page make sure you already have the debug console open so that any errors are reported and then refresh the page.  Please let me know what errors are reported.

**Comment by lukasenz** [comment]
How to I open the debug console?

**Comment by juliemturner** [comment]
Depends on what browser you're using but normally F12 will do it, it should also be in the browser menu as "developer tools".

**Comment by lukasenz** [comment]
I receive the following errors:
`Key quickActions.screenReader does not exist in string map https://spoprod-a.akamaihd.net/files/sp-client/chunk.vendors~sp-pages-search_aed36dfbaa1883de6cd1.js`

`Key quickActions.suggestion does not exist in string map https://spoprod-a.akamaihd.net/files/sp-client/chunk.vendors~sp-pages-search_aed36dfbaa1883de6cd1.js`

`Access to XMLHttpRequest at 'https://waconafd.officeapps.live.com/apc/trans.gif?2ec3c320905efc6263c9f5f70381ccad https://tenant.sharepoint.com/sites/NWoWLC/SitePages/CustomLearningAdmin.aspx' from origin 'https://tenant.sharepoint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by juliemturner** [comment]
Hm, those are odd errors... it implies your solution isn't even running.  Did it load in the end?  How many playlists are we talking about?

**Comment by lukasenz** [comment]
Yes I can use the CustomLearningAdmin-Center normally. I am able to create playlists and also new assets, but not able to link old assets. I also see the custom SubCategories but they have no playlists.
 We have 41 CustomPlaylist items and only 3 are working, I think the working ones are the oldest.

**Comment by juliemturner** [comment]
Well, unfortunately, the console log you're sending me is not telling me what the issue is and without that information, I'm not sure I can do anything for you.  I can use the example you already sent me to try and figure out what minimum things need to be done to manually make them work if you want me to go down that route.

**Comment by lukasenz** [comment]
If there is any way to get the custom playlists and assets working again (e.g. editing the  without having to set them all up again, I would really appreciate it.

**Comment by juliemturner** [comment]
Ok, I'll work on figuring out (using your one demo item) what might be done to make it work.. I'll get back to you when I have more info.  If you wanted to paste in the JSONData for 1 or 2 more playlists that would be useful.

**Comment by lukasenz** [comment]
Thank you very much!
examples:

`{"Id":"19","Title":"Collaboration members","Image":"https://tenant.sharepoint.com/:i:/r/sites/NWoWLC/Shared%20Documents/Icon%20for%20RBI%20Guides%2028x20_version2.png?csf=1&e=8UfRLF","Level":"Beginner","Audience":"End User","Technology":"","Subject":"","Category":"Get Started","SubCategory":"Group Coll@boration at RBI","Source":"Tenant","Assets":["32"],"CatId":"92bffb4d-9451-45bf-b0fa-8f5614003d9c","Description":"Here you find a list of the Collaboration members of the NWUs.","StatusTag":""}`

`{"Id":"5","Title":"SharePoint Online und Office Group RBI internal guides and videos","Image":"https://tenant.sharepoint.com/:i:/r/sites/NWoWLC/Shared%20Documents/Icon%20for%20RBI%20Guides%2028x20_version2.png?csf=1&e=8UfRLF","Level":"Intermediate","Audience":"End User","Technology":"SharePoint","Subject":"","Category":"Products","SubCategory":"SharePoint","Source":"Tenant","Assets":["9","10","11"],"CatId":"e5e2ae74-20ff-4626-937d-df4ff3405f29","Description":"RBI internal guides and videos","StatusTag":""}`

**Comment by juliemturner** [comment]
@lukasenz  -- First let me apologize, I just realized what the issue is with what I told you to do and why I didn't work.  So... first, go through the CustomPlaylist list and CustomAssets list and enter the word Default for every CDN field that's empty.  This is why the re-upgrade didn't happen as it wasn't actually loading those playlists and assets into memory to be updated.  Once you do that (which is easily done by using Quick Edit on the list then go back to the instructions I sent you earlier (quoted below) about updating manifest to v2 so that the upgrade code will run again. I just tested it and this worked perfectly, but only AFTER I updated all the non-converted playlists and assets to have the CDN field set as 'Default', basically match one of the working ones.

> Oh, I see the problem. Not all of the playlists were updated to V3. So, probably the easiest thing to do is to modify the JSONData for the CustomConfig to force it to update any that were missed.
> 
> 1. Have the CustomLearningAdmin.aspx page open.
> 2. In a new tab, open site contents and go to the "CustomConfig" list and show the information panel for the "CustomConfig" list item.
> 3. Edit the value of the JSONData field, changing the value of CachedMetadata.Version.Manifest from "v3" to "v2". It's easiest to do this if you copy the contents out, paste it in a text editor, search for "Manifest" and then make the change and then paste it back into the JSONData field.
> 4. Switch back to the CustomLearningAdmn.aspx tab and refresh... then wait.  Don't click refresh multiple times, just let it run until it loads.
> 
> This should then run through all the playlists and assets and complete upgrading all of them. If you look at the playlists you should see that they show "LevelId" instead of "Level" the ones that still show "Level" didn't get upgrades and therefore won't load into the solution. If this doesn't fix the issue let me know and we can try and determine where it's getting stuck and if there's some sort of of bug in the upgrade that I can address.

**Comment by lukasenz** [comment]
No need to apologize, I am very grateful for your help!
I am now on my way home, but will try it first thing tomorrow.
________________________________

**Comment by lukasenz** [comment]
It is working now, thanks again for your effort and help!!!
