### ISSUE TITLE
Questions about Release of new content

### ISSUE THREAD

**Issue by pb762** [pnp/custom-learning-office-365#183]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [ ] Custom Content
- [ x] M365 learning pathways web part

**What is your question?**
1. How will we know when new content from Microsoft is added to Learning Pathways. Can there be a notification?
2. When new content is added will it be "visible" by default or "hidden" by default. We don't want it to be visible before content admins in our company have had a chance to review.

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
For question 1, I have a question back into the content team to find out how they intend to communicate updates, but you can see the detail they have here from the November update: https://docs.microsoft.com/en-us/office365/customlearning/custom_contentupdates

For question 2, any content updates will be visible by default because there is no facility for us to hide them by default given hiding and showing content is done at the tenant level. We can look at the feasibility for adding this ability at some point in the future but it is not currently on our backlog.

**Comment by pb762** [comment]
Ok, the reason for us is that we want better control over the content so that we as content owners can review it first before the general user population in our company views it.

**Comment by juliemturner** [comment]
@pb762 -- If that's your goal... one way that you could accomplish it is to leverage the custom content packs feature and fork this repo, turn on GitHub pages for that fork, use that URL + /learningpathways/ as the CDN URL for a custom content pack and then point all your web parts to that custom content pack instead of Microsofts.  That way, when we update the repo with new content you could review it first, then when you had a list of what you wanted to hide, you would update your fork and then in the admin area hide any of the playlists or categories you don't want to show. 

Technically you could even modify the .json files if you really wanted to, but that will make a more arduous merge process. Regardless it's doable.

**Comment by pb762** [comment]
Hi @juliemturner  thanks for the above feedback but at this time we would prefer not to go with the custom content and prefer a simple approach of consuming the learning pathways content.

Also, I think we are due for the next quaterly updates after the Nov 2019 release right? When is it expected? Or did I miss it?

**Comment by pb762** [comment]
Hi @peterjkrebs  - looking forward to an update on this :)

**Comment by peterjkrebs** [comment]
The next quarterly content update for Learning Pathways is scheduled to be released in early April.
