### ISSUE TITLE
error on mobile devices for .../sites/LearningPathways/SitePages/Get-started-with-Microsoft-365.aspx

### ISSUE THREAD

**Issue by thomasdaggett** [pnp/custom-learning-office-365#187]
![issue](https://user-images.githubusercontent.com/33695409/72534677-34ebf800-3845-11ea-8808-ffbc26daa75e.png)
My users are receiving an error only mobile devices when opening .../sites/LearningPathways/SitePages/Get-started-with-Microsoft-365.aspx, the "Microsoft 365 pathways has a configuration issue.  Ask you administrator for assistance...".  Any suggestions on what may be happening our mobile devices when access this page?

**Comment by juliemturner** [comment]
I'm somewhat confused, the screenshot you provided shows the page isn't loading at all, or maybe that's a partial screenshot?

**Comment by thomasdaggett** [comment]
Hi Julie,

We are seeing this now on all Apple devices – The issue happens from any browser on a Mac running Mac OS Catalina.

[cid:image001.png@01D5CC6B.58F89230]

Thomas

Thomas Daggett, Ph.D.
Colleague Products & Solutions | Digital Solutions & Enablement
Mobile: 860 449 2927 | Office: 860 686 9766

[cid:image003.png@01D51F6F.03E221C0]

**Comment by juliemturner** [comment]
So the issue you're seeing is that Apple devices won't load the SharePoint site/pages? I'm still confused because your screenshot doesn't match the description of the issue.  

>Note: Please be careful responding via email as your email signature ends up in the github issue body. I've removed it from your previous response.

**Comment by thomasdaggett** [comment]
Hi Julie - that is correct, we are seeing issues now with Apple devices and also issues with users who are guests to our tenant.  One other change was that we renamed the site and changed it URL since it was first instantiated.  The site works fine for PCs on our network, this one page is not working for Apple devices and Guest accounts.

**Comment by juliemturner** [comment]
Ok, renaming the site is one thing but changing the URL is probably going to cause some problems, but it shouldn't be device-specific other than it may be that the redirects that happen when you change the URL for a site aren't being honored. Anyway, there is a tenant app property that specifies what the URL is for the learning pathways site collection.  Because you changed the URL but probably didn't realize you needed to update that property things are probably going to be failing. You will need to update the property using the following PnP Power Shell command, where $clSite is the URL for the learning pathways site:

`Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Microsoft 365 learning pathways Site Collection"`

But still, the web part failing shouldn't cause the entire page not to load, so I really don't know if this is going to fix your problem but it's definitely needed to make the solution work in general.

**Comment by karuanag** [comment]
Hello Thomas please give us an update and any new/continuing screenshots here at your convenience.

**Comment by juliemturner** [comment]
Closed - no response from the user. Please feel free to start a new issue if you're still having issues.
