### ISSUE TITLE
Delve Image

### ISSUE THREAD

**Issue by ruenells** [pnp/custom-learning-office-365#190]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [ x] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
I am looking to find a Delve image to update the custom config with and when i follow the same naming as the other icons it appears not to exist can you tell me the correct name to use?

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
The only custom images/icons that exist are the ones at these folders: https://github.com/pnp/custom-learning-office-365/tree/master/docs/learningpathways/v3/images

These images are custom made by our designer specifically for the custom content that is added to the content pack. Since we do not currently have Delve in our content we do not have a Delve image.  If you want a Delve image the best way forward is to create one yourself and store it in your site assets library and then reference it there.

**Comment by ruenells** [comment]
> The only custom images/icons that exist are the ones at these folders: https://github.com/pnp/custom-learning-office-365/tree/master/docs/learningpathways/v3/images
> 
> These images are custom made by our designer specifically for the custom content that is added to the content pack. Since we do not currently have Delve in our content we do not have a Delve image. If you want a Delve image the best way forward is to create one yourself and store it in your site assets library and then reference it there.

Yes, that is what I am doing just wanted to make sure I didnt miss one in your library thank you
