### ISSUE TITLE
GCC Support

### ISSUE THREAD

**Issue by pkeegs** [pnp/custom-learning-office-365#214]
I am confused about GCC support for learning pathways.

I just deployed, the prerequisite checks all passed but the provisioned site is full of "Microsoft 365 learning pathways has a configuration issue..."

Post-deployment, I allowed custom script via PowerShell and I still get "Microsoft 365 learning pathways has a configuration issue...".

How do I get learning pathways working in GCC? I am assuming GCC is my issue.

**Comment by juliemturner** [comment]
So there are two levels of GCC (GCC and GCCH).  I can guarantee that it won't work in GCCH.  I have heard through others they have gotten GCC to work but I don't have access to a GCC tenant so it's very difficult for me to tell.  What I can say is that if you're seeing that message than by opening the browser's development console (F12 on most browsers) you will end up seeing the console and then if you refresh the page it should list "errors" that will tell you more specifically why it's having problems and through that, we should be able to determine if the problem is simply configuration or something blocking because of being GCC.

**Comment by pkeegs** [comment]
F12 helped!

It appears I cannot access resources on https://pnp.github.io/ due to the security settings somewhere in my organization.

Requests to pnp.github.io fail with this message:
_This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner._

For example, this fails
https://pnp.github.io/custom-learning-office-365/learningpathways/v3/images/playlists/set-up-Microsoft-365-learning-pathway.png

Outside of my organization's network...everything works.

So, I do not think it is a GCC issue.

**Comment by juliemturner** [comment]
Right, so that would mean that your organization has a proxy/firewall of some type that's blocking access to GitHub. This is not uncommon as we've seen that issue here before. Sadly there's nothing that we can do about that but you're correct that's not a GCC issue specifically.
