### ISSUE TITLE
[BUG] Cannot access CustomLearningAdmin page

### ISSUE THREAD

**Issue by ehrlee** [pnp/custom-learning-office-365#222]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).

**Describe the bug**
Hi Julie, I am trying to create custom playlists (thanks to your great GlobalCon demo!) but when trying to access the Learning Pathways Custom Admin page I receive this error message:
"Microsoft 365 learning pathways has a configuration issue. Please see the browser console for detailed logs. For assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues."
The rest of the site functions properly. It's been up and running since January.
I've attached the errors received. 

**Screenshots**
![image](https://user-images.githubusercontent.com/62067532/76464440-c1391800-63bb-11ea-8db5-1dcba2a72317.png)

**Learning Pathways version number:**
v3.0.3.0
We tried updating to what looks like a newer update version several times based on version instructions on github. The package addition is successful but each time the app catalog reversed it back to the above version. 

**Additional context**
Regarding my first comment - re: zero trust policy (https://www.microsoft.com/en-us/security/business/zero-trust). We have this policy in place which means we need to sign out all permission roles, i.e global admin, admin centers like SP, etc. Initially I thought that the LPs app might be trying to authenticate against a role that wasn't granted at the time. However, I have tested both with SP Admin permissions and Global Admin permissions and this was not the issue. All permission levels receive the same error.

**Comment by juliemturner** [comment]
Based on that screenshot it appears that you've changed the tenant app property that controls where the web part tries to load the content from (MicrosoftCustomLearningCdn).  If you note it's trying to load metadata.json from https://pnp.github.io/custom-learning-office-365/learningpathways/v3/v3/ which implies to me that the value for the property now has v3 hard coded into it.  You can check this by running powershell to get the value: 

  `Get-PnPStorageEntity -Key MicrosoftCustomLearningCdn`

The result should be: https://pnp.github.io/custom-learning-office-365/learningpathways/

Assuming it's not you need to run the following PowerShell command:

   ```
  Connect-PnPOnline -Url $clSite -UseWebLogin
  Set-PnPStorageEntity -Key MicrosoftCustomLearningCdn -Value $cdn -Description "CDN source for Microsoft 365 learning pathways Content"
   ```
where $clSite can be the site url for your learning pathways site and $cdn should be

 `https://pnp.github.io/custom-learning-office-365/learningpathways/`

Even though you think the other web part is working I suspect it's working of the cache because it can't access the cdn endpoint to download the mainfest files to update itself.

**Comment by ehrlee** [comment]
I'm learning Powershell as I go but after a few fumbles, that worked! Thank you!
