### ISSUE TITLE
[QUESTION] Custom Content Pack

### ISSUE THREAD

**Issue by denzy134** [pnp/custom-learning-office-365#229]
**What is the context of your question?**
- [ ] Installation
- [ ] Administration
- [* ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
I created custom content packs. They all have no problem but this particular one. I am not able to save a picture. When I change the image of the playlist it won't save.  The images for this content pack are not showing up and i realized they have two URLs in the image URL link so it cant direct the link to a particular location. I decided to clean that up in the JSON and paste it back in the custom config where it belongs but every time i do that it goes back again to the same double URL.
I decided to add the image in the UI but it wont save.

**Provide related screen-shots to help us understand your question**
<img width="477" alt="Capture67" src="https://user-images.githubusercontent.com/35541187/77544180-4fa6a280-6e6e-11ea-80ba-5b5931be5ebf.PNG">

The image above shows the current url link.
When i edit it it will not not save the new URL.

<img width="579" alt="Capture68" src="https://user-images.githubusercontent.com/35541187/77544557-c5127300-6e6e-11ea-843b-aa24469b79a0.PNG">

I would really like help with this . Thank you

**Comment by juliemturner** [comment]
@denzy134  - If you open the browser's developer tools and refresh the page and then try and change the url in the UX and save it do you still get the fail message and if so what is the error message in the console or on the network tab.

**Comment by denzy134** [comment]
Yes so I refreshed it and still got the fail message.
<img width="274" alt="error1" src="https://user-images.githubusercontent.com/35541187/77701769-a4d0da00-6f7c-11ea-8868-2ab6ab511dbc.PNG">

<img width="277" alt="error2" src="https://user-images.githubusercontent.com/35541187/77701787-ad291500-6f7c-11ea-915a-a0d81adbc253.PNG">

**Comment by denzy134** [comment]
sorry i closed it mistakenly

**Comment by denzy134** [comment]
Hello Julie

We would like to set up a meeting with you to discuss this issue. What would be a good time?

Kekeli Madugu
Student Project Manager
Information Technology
2089705024
________________________________

**Comment by juliemturner** [comment]
@denzy134  - First, please be careful about responding to these notifications via email as it embeds the entire email message which includes a significant amount of PII in the GitHub issue which I suspect you prefer not to have posted. Either clear the rest of the body of the email or use the GitHub UI to respond. 

With regard to your request for personalized support, I'm sorry but I do not personally offer live in-person support. 

To address the error message, the console implies the playlist item in the "CustomPlaylists" list with ID 3 doesn't exist. I'm not exactly sure what to say about that. Have you successfully created and edited playlists inside the custom content pack before and now that you're trying to edit not only the list item in the list but through the UI at the same time you're having an issue?  It feels like your problem is a timing issue.  If you modify the item in the list then you need to completely refresh the admin page before you attempt to do anything else.  Please validate that you can create a playlist in the UX and edit it in the UX without having touched anything in the list itself.  If that works then I'd say you have some timing issue if that doesn't work then there is likely a bug with creating custom playlists with a custom content pack.  If it's the latter, I can look into that issue but probably not until next week at the earliest. Please let me know what you find out.

**Comment by denzy134** [comment]
Do know where i can find the manifest json file

**Comment by juliemturner** [comment]
There is no manifest.json file, that said I think there was a presentation I did where I had manifest.json on the slide instead of metadata.json.
