### ISSUE TITLE
custom learning admin settings option.

### ISSUE THREAD

**Issue by jrummer** [pnp/custom-learning-office-365#230]
**What is the context of your question?**
- [ ] Installation
- [X ] Administration
- [ ] Custom Content
- [ ] M365 learning pathways web part

**What is your question?**
We had issues getting the learning center installed so we ended up duplicating the pages on a new site, long story.  We got everything working and we've been able to update the current site and customize the content a little bit.  We are now looking to add our own content via the CDN option and noticed something.  From the Custom Learning Administration page, then settings cog wheel, it goes to the old site that was originally created.  Even the copy link is the old site.  I think it had to do with us copying pages and content from the old learning center to the new one.  is there a way to update that link?

**Provide related screen-shots to help us understand your question**

**Comment by juliemturner** [comment]
@jrummer  - so basically although you think you got the site up and running you didn't.  You cannot copy pages only to "set up a new site". You've pretty much put yourself in a partially installed situation. The gear is taking you back to the other site because that is the site currently configured as the "master" M365LP site collection, this is done through a tenant app property. Did you copy the "CustomLearningAdmin.aspx" page as well, is that how you got the admin web part running in the new site collection or was that missed?  I would suspect that page if you copied it won't load?

The ideal way to solve this situation would be to delete both site collections and the web part from the tenant app catalog and start from scratch, preferably provisioning the site from the provisioning service or by carefully following the manual deployment process documented.  If that's not an option I can try and step by step diagnose the situation with you but it'll obviously be a slower solution.

**Comment by jrummer** [comment]
When we originally installed it, most of the pages and site assets were missing.  So then, the dev guys had to update the install code to accommodate a vanity URL and it worked.  The app installed and some of the pages installed.  We then went to the other site and did some site page copies.  Everything worked as it should with no issues.  I was able to do the recent update.  Then as we were trying to add another CDN and the settings wheel took me to the original URL.  I hadn't noticed that before and I swear it went to the same URL earlier, but I could be wrong.  If that hard coded link can't be changed to the correct URL, you're saying we should start over.

**Comment by juliemturner** [comment]
Ok... well... this is a fairly complicated scenario then so it's hard for me to just give you generic guidance.  I can tell you that if you're seeing the gear go back to the old site then it's likely somehow the tenant app property: "MicrosoftCustomLearningSite" was left or reset back tot he original. You'll need to fix that tenant app property so it points to the correct site.

You can check the current value with this PowerShell command (which uses PnP PowerShell)

`Get-PnPStorageEntity -Key MicrosoftCustomLearningSite`

and to set it you can use this command, where $clSite is the URL of the site you want to be the "home" site for learning pathways:

`Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Microsoft 365 learning pathways Site Collection" `

The only other point I need to make is you will need to make sure the CustomLearningAdmin.aspx page is in the new site that you're going to make the home site of learning pathways.  The admin web part is hidden from the catalog so deploying it to a new site requires using PowerShell...

**Comment by jrummer** [comment]
It sound complicated, but so far it's all worked as intended.  We're going to use powershell and see if we can set it the way you've instructed.  thanks for the quick responses!

**Comment by juliemturner** [comment]
I suspect if you deleted the old site it wouldn't be working, so maybe that would be a useful step unless that's not an option.

**Comment by jrummer** [comment]
We could delete the old site and see what happens.  We might do that after configuring it with Powershell just to be on the safe side.

**Comment by juliemturner** [comment]
I would absolutely do that.

**Comment by jrummer** [comment]
Sounds like a plan.

**Comment by jrummer** [comment]
we ran the commands but now the settings wheel in the admin center no longer links correctly.  oh well.

**Comment by juliemturner** [comment]
Can you be a little more specific?  
- If it doesn't work what is it doing... are there any console errors in the browser? 
- Is your tenant one of the few tenants with a vanity url?
- Is your tenant GCC?
- Did you delete the old site?
- Does the admin web part run? That should be on a single app part page in the site pages library called 'CustomLearningAdmin.aspx'.

Honestly at this point that would be where I would start.  Get the admin web part working and the rest should be good.

**Comment by jrummer** [comment]
its going into a loop where the setting cog goes right back to the admin page and not the settings page.  i'm nervous to delete the old site at this point for fear that the new site is too far gone and we don't have time to redo the whole thing before we launch it. 

it is a vanity url

not gcc

not delete old site.  i could potentially rename it.  

i can get to the customlearningadmin.aspx.  but i can't edit the content through the settings option.

**Comment by juliemturner** [comment]
I'm confused, "going in a circle?" The cog, that is visible in the viewer web part should just take you to the customlearningadmin.aspx page.  That's what it does. The admin page is where you customize the content that shows up in the viewer web part, regardless of what page/site that web part is on.  Are you speaking of the viewer web part properties?  

Maybe it would be beneficial to you to watch the overview video I have posted on how the solution works: https://www.youtube.com/watch?v=-sLXl_rKGxQ&t=109s

**Comment by jrummer** [comment]
i can't get to the admin page at this point to customize the content.  that's my issue.  i could get there before and make changes.  is there another URL to get there that i'm missing?

thanks!

**Comment by jrummer** [comment]
correction.  the custom learning admin page no longer goes to where i can customize content.  i think its looping back to where i see all the icons and would normally hit the setting wheel to make changes.

**Comment by juliemturner** [comment]
So that's what I was trying to tell you before. It's not something that simply can be copied from one site to another. You didn't actually ever have it working correctly.  Now that you've corrected the tenant app property so that you have a new master learning pathways site you need to get that CustomLearningAdmin.aspx and CustomLearningViewer.aspx page created/fixed.  This cannot be done manually.  However, the manual deployment script can be run in "SiteAdminOnly" mode and that should correct the situation.  Please run this script https://github.com/pnp/custom-learning-office-365/blob/master/webpart/M365lpConfiguration.ps1 with the SiteAdminOnly flag set to true and the  SiteCollectionName setting set to the URL of the new site collection you want to set up.  More detailed instructions can be found here: https://github.com/pnp/custom-learning-office-365/blob/master/webpart/README.md#execute-powershell-configuration-script. Please read that section thoroughly and then things should be corrected and you can remove your old site.

**Comment by jrummer** [comment]
i didn't realize up until last week that it wasn't setup correctly.  it looked ok but in reality, it wasn't like you said, able to be copied over.  i'll have our dev guy run those additional scripts and go from there.  

thanks for your help.

**Comment by jrummer** [comment]
Success!!!  My dev was able to run a script and it recreated the admin and viewer pages.  everything lines up with the same URLs. 

Thanks again for your quick help!!

**Comment by juliemturner** [comment]
Awesome glad we could get it sorted!
