### ISSUE TITLE
Sharepoint app Microsoft 365 Learning Pathway removed and added again

### ISSUE THREAD

**Issue by AubinC** [pnp/custom-learning-office-365#234]
Hi,

We just removed the M365 LP app from our Sharepoint site and tried to add it again.

Background:
- We had change the Sharepoint site URL and for some reason we could not get the admin page to load anymore (while the user page was working fine)

Issue encountered:
- After re-adding the app, I get this error message : "Error: ***The value for "_manifest" must not be undefined"

Question: any way to solve this in a simple way?

Thanks a lot,

Aubin

**Comment by juliemturner** [comment]
So if you change the site URL you end up creating a redirect site and then all heck breaks loose 😊
There was a fix for that, you just needed to run a bit of PowerShell to update the tenant app property so that it points to the new URL and you would have been all set.
But, since that's not the case, moving on... Can you tell me exactly what you did to "remove" the app? Did you remove the app from the site or remove the app from the app catalog.  If it removes the app from the site, and adding it back is broke then we'll have to dig in as that should be ok, if it's removed from app catalog, did it not deploy properly we need more information.

The simplest answer is to delete the site collection altogether, delete the app out of the app catalog and reprovision the site from the provisioning service.  But if that's not an option we can work step by step to try and fix it.

**Comment by AubinC** [comment]
Thanks for your answer. I'll go with the simplest answer but would like to keep the current site collection (to keep some content available). If I delete the app out of the app catalog and reprovision to a new site collection, would it work ?

**Comment by juliemturner** [comment]
Yes, it should as long as it's a new site collection URL.
