### ISSUE TITLE
[BUG] Custom content missing after April 2020 content update

### ISSUE THREAD

**Issue by indyness** [pnp/custom-learning-office-365#237]
## Describe the bug

After the April 2020 content update, our custom content no longer shows up in the web part. The custom subcategories, playlists, and assets are still visible in the Admin view. I can add new assets to the existing custom content, but it doesn't show up in the web part. I also tried editing the existing custom content and changing the visibility off/on.

Searching for custom content created prior to the April 2020 update returns no results.

If I add new subcategories and playlists/custom assets to those new subcategories, the new content appears in the web part.

In the screenshot below, "What's New?" is a custom subcategory.

![image](https://user-images.githubusercontent.com/11835400/78513546-7cb25980-777a-11ea-9ffa-765cfd6bad6c.png)

![image](https://user-images.githubusercontent.com/11835400/78513557-8c31a280-777a-11ea-8f27-d3535440afb0.png)

### Learning Pathways version number

We had v3.0.0.0 prior to the April 2020 content update. We deployed v3 using the site provisioning service in 2019. I just upgraded to the latest version to see if that would resolve the issue. It did not.

### Additional context

We're in the GCC.

**Comment by indyness** [comment]
Here is the JSON for two custom subcategories - What's New? was added a few weeks ago, and My Test Subcategory was added last night. There are two visible playlists in the What's New? subcategory.

{
    "Id": "c812f0d8-63ad-42f2-b1a2-2b6fefeeeaaf",
    "Name": "What's New?",
    "Image": "https://pnp.github.io/custom-learning-office-365/learningpathways/v3/images/categories/customfeatured.png",
    "TechnologyId": "",
    "SubjectId": "",
    "Source": "Tenant",
    "SubCategories": [],
    "Path": [],
    "Count": 0
}, {
    "Id": "344ca857-f4ea-4ee9-9146-c280c29fa03b",
    "Name": "My Test Subcategory",
    "Image": "https://pnp.github.io/custom-learning-office-365/learningpathways/v3/images/categories/customfeatured.png",
    "TechnologyId": "",
    "SubjectId": "",
    "Source": "Tenant",
    "SubCategories": [],
    "Path": [],
    "Count": 1
}], "Path": ["646b4eb4-32c0-4fdc-93fa-0ef895470b74"]
}

**Comment by juliemturner** [comment]
So I see the issue, but I'm not sure why it's happening.  If you note in "What's New" the "Count" says 0. What that means is that it can't find any playlists that go with that subcategory. This could be a bug, but it's hard to tell what bug since I can't reproduce it. Would it be possible for you to share a screenshot of the admin center showing the playlists listed under What's New subcategory? And, since you seem to know what you're doing with the list items,  and if possible the JSON of the two playlists themselves that could help me diagnose it.

**Comment by indyness** [comment]
I just figured it out. The playlists did not have a value in the Technology field. Now that I have updated all the playlists with a Technology value they are showing up.

**Comment by juliemturner** [comment]
Interesting... that was a bug in 3.0.0 but it was fixed. I could go back and look but in a version before the current one, it might be 3.0.2.  Regardless glad it's working for you.

**Comment by CodingSinceThe80s** [comment]
Hi @juliemturner, I am experiencing the exact same issue with a customer. So what would be the steps to fix this? Is there a script to update all the Technology fields?

**Comment by juliemturner** [comment]
The above issue is closed, please start your own issue to address your unique issues.

**Comment by CodingSinceThe80s** [comment]
Well, as it is literally the same issue I see no need for a separate discussion. Now that I have tested the Technology-Field solution you hinted at I can build a script to automate this or just manually set the fields to some value to make them visible. Thank you for this one and for the very useful learning solution!

**Comment by juliemturner** [comment]
@CodingSinceThe80s  - I asked you to submit a separate issue because this shouldn't be an issue at all as I had thought the bug was fixed in an earlier release of version 3, and in saying that if you're running a version earlier than 3.0.4 you should update and the issue may fix itself. 

The user above fixed the issue in a way that shouldn't need to be done but since they're satisfied with the answer I let it go. The technology field is not required and should not cause this issue.  Since your environment is unique and I would ask for information regarding that environment and we would most likely come to a different answer and it's significantly easier for me to track what has been done if it's in its own thread. If you do not wish to open a new issue and have me attempt to track down what's going wrong for you and would like to solve it by writing your own script to assign a technology where one is not needed, you are absolutely free to do that. I make suggestions, you make decisions.
