### ISSUE TITLE
[BUG] PowerPoint Animation and transitions page has the video for Insert Pictures, Shapes and More

### ISSUE THREAD

**Issue by AussieMerched** [pnp/custom-learning-office-365#241]
## Describe the bug
Playlist asset showing the wrong video
The asset for PowerPoint for the web: Animation and transitions has the video for Insert Pictures, Shapes and More
### To Reproduce
https://support.office.com/en-us/client/07a941fb-b027-4f3e-b514-cd9866723f45?embed=true
>Steps to reproduce the behavior

### Expected behavior

>To be able to view the video that should be associated with the text in the asset.

### Screenshots

>If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/63657360/79241364-e31a3480-7e6a-11ea-803e-1eb2ac955bf0.png)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
@AussieMerched - I have passed this bug onto the team but the issue is with the content on support.office.com and not with learning pathways itself.

**Comment by AussieMerched** [comment]
Thanks, I wasn’t sure how to report it!

**Comment by juliemturner** [comment]
@AussieMerched  - No problems at all this is the right place just wanted to set expectations.
Also, just a best practice so you know, if you respond via email make sure you clear the body of the email otherwise your PII can end up in the github issue for all to see.  I tend to just always make sure I use the GitHub UX so I am sure what is getting posted.  Have a great day.

**Comment by peterjkrebs** [comment]
Thank you for reporting the issue. We are looking into it today.

**Comment by jsuddsjr** [comment]
This has been fixed.
