### ISSUE TITLE
Trying to deploy learning pathways multiple times in one tenant

### ISSUE THREAD

**Issue by juanjolli** [pnp/custom-learning-office-365#242]
>**PROVISIONING NOTE**: If you are having issues with the provisioning service while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the provisioning service to [https://github.com/SharePoint/sp-provisioning-service/issues](https://github.com/SharePoint/sp-provisioning-service/issues).
 
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

We have deployed the Learning pathways 3 times on our environment to provide portal in different languages
we have then 3 different URL
https://XXXXX.sharepoint.com/sites/O365CL
https://XXXXX.sharepoint.com/sites/O365EN
https://XXXXX.sharepoint.com/sites/O365ML
After upgrading to version 3.0.4, the Custom learning admin page does not work except for O365ML, the other two are stuck loading with no error message
https://XXXX.sharepoint.com/sites/O365ML/SitePages/CustomLearningAdmin.aspx
Based on the error collected with the Dev tools, the 3 admin portal seem to be trying to connect to ML
custom-learning-admin-web-part_8f85fa9c576514eaec9591ef354b4dfa.js:26 Message: This site is not the Microsoft 365 learning pathways site as defined by the tenant property MicrosoftCustomLearningSite
We need help repointing the admin page for the 2 additional portals

### To Reproduce

Access the Customlearningadmin page

### Expected behavior

>A clear and concise description of what you expected to happen.

### Screenshots
![image](https://user-images.githubusercontent.com/61012774/79352354-bb2cde80-7f07-11ea-94f6-bb7e73ba713b.png)
![image](https://user-images.githubusercontent.com/61012774/79352649-1fe83900-7f08-11ea-8a78-2734adee5088.png)

![image](https://user-images.githubusercontent.com/61012774/79352459-e31c4200-7f07-11ea-8cb3-f04a56366c6c.png)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog.

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
I'm sorry @juanjolli what you've done here is fundamentally not supported by this solution. The multilingual version of learning pathways will be coming soon but is dependent on the Multilingual pages solution being GA in SharePoint online. That may already tell you that our multilingual scenario will not be site based but page-based. Further, as the error message you're seeing implies, there is only 1 master learning pathways site. The solution can be added to other sites but that is to support a hub-spoke access model of that learning content where you can add the viewer web part to pages in any site collection where you enable the app. I would suggest you watch the [video](https://www.youtube.com/watch?v=-sLXl_rKGxQ&t=109s) I created that discusses the overall architecture of the solution. In the meantime I would choose which of these sites you want to be the "master" site -- in this case probably based on whatever language you want to be your default language for the administrative experience -- and then delete the other two.  If it happens that the site you pick is not one of the ones working right now you'll need to run a line of PowerShell to change the tenant app property that configures the tenant for which site is the master learning pathways site (where $clSite is the site URL):

`Set-PnPStorageEntity -Key MicrosoftCustomLearningSite -Value $clSite -Description "Microsoft 365 learning pathways Site Collection"`

**Comment by juanjolli** [comment]
Thanks for the clarification

**Comment by AndreSchiemann** [comment]
Hello @juliemturner,

my questions related to this issue here: 

1. Why is this property "MicrosoftCustomLearningSite" needed for the admin webpart of the solution?
2. It is possible to have peaceful coexistence of two (or more) learning pathways websites in one tenant by switching this property from one website to another just before administrative work in the related website!?

Many Thanks,
André

**Comment by juliemturner** [comment]
The setting is utilized for the viewer web part to know what site collection to get its content from... it's in the admin web part to validate that you only have one so and that if you're administrating content you know that it's tied to the web part when you use it. That is the architecture of the solution and was a conscious decision we made to do a distributed plan. To see an overview of the architecture you might watch this [video](https://www.youtube.com/watch?v=-sLXl_rKGxQ). 

So, then the answer is no, it is not possible to have multiple instances of the main learning pathways site in a tenant.  There are lots of ways to work around scenarios that leave you thinking you need more than one, if you want, I would suggest you open a new issue and propose your issues on why you think you need more than one so that guidance for options can be given.
