### ISSUE TITLE
Can I download the content from MS Learning Pathways from github?

### ISSUE THREAD

**Issue by lkinard01** [pnp/custom-learning-office-365#261]
>Our company blocks github.io for security reasons, so we cannot successfully install MS Learning Pathways at this time. Is there some where on here that I can download the content from MS Learning Pathways as a temporary workaround?

I'm a newbie on this platform, so any help is greatly appreciated, thank you!

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
The only option you have is if your organization has an internal platform that can host the json files for you.  You could then download the manifests and put them in the same file structure and then update your installation so that it changes your CDN path to point to your own internal source for those manifest files.  You'd probably want to confirm that they will let you access support.office.com and docs.microsoft.com or the exercise would be fruitless but that is a solution.  The only thing is that when an update is made to the manifests (which is generally quarterly) you would need to monitor that and download a new set of .json files so that you could refresh your cache.

**Comment by lkinard01** [comment]
Thank you for the quick reply. I'll see if this will work for them.

**Comment by lkinard01** [comment]
@juliemturner , we're going to try this workaround solution. My server team is asking if you could provide more details or documentation? Does the internal platform need to be a web server, NAS share work? What permissions need to be given to redirect the CDN, etc? Thank you so much for your help!

**Comment by juliemturner** [comment]
We have no documentation as this workaround is not supported.  All I can tell you is you need a CDN, you could use Azure CDN, a CDN from another 3rd party cloud provider, or a CDN that you build internally, and everyone who has access to the SharePoint site needs access to it without authentication unless you're going that some other way as these calls are being made from the code compiled into the web part and you cannot change them to add an auth header to them.

Once you have that then you need to copy the structure and contents from the [docs](https://github.com/pnp/custom-learning-office-365/tree/master/docs) folder into the root of whatever your new CDN endpoint will be.

Then you need to run a PowerShell script to change the endpoint from pointing to GitHub to pointing to your CDN (the place you copied the docs folder contents to). You can use this [script](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpCDN.ps1) as the source, and change the URL on line 30 to whatever URL points to your CDN.
