### ISSUE TITLE
URL from custom content package does not work, but same URL works if entered in UI

### ISSUE THREAD

**Issue by greg-e** [pnp/custom-learning-office-365#273]
### Context of question
- [] Custom Content
- [] M365 learning pathways web part

When adding an asset in a Custom Content Pack... the iFrame will not load in the webpart   The console shows the URL as (NOTE: "root" replaces our tenant name): 
`GET https://root.sharepoint.com/sites/thissite/SitePages/The-Waffle.aspx&fromOrigin=https://root.sharepoint.com 404`

On a copied playlist from the same Custom Content Pack the same exact URL renders the iFrame giving the following warning in the console:
```
Warning!
Use of this tool exposes you to potential security threats which can result in others gaining access to your personal Office 365 data (documents, emails, conversations and more). Make sure you trust the person or organization that asked you to access this tool before proceeding.

Learn more here: https://technet.microsoft.com/en-us/library/bb794823.aspx
```

-  Why are these behaving differently?
- What is the `&fromOrgin=` that has been amended to the original URL.
-  How is the URL to be fashioned in assets.json so it works the same as added in UI?

**Comment by juliemturner** [comment]
The screenshot of the warning message in the console shows up on every page, that's not indicative of anything.

I suspect your problem with a custom content back is the "source" property... There was really not use case planned to support putting SharePoint pages in a custom content pack, not that it can't work but it wasn't the intention.  If it were me I would be putting the URL in as just the absolute URL to the page.  The asset viewing code appends the fromOrigin, and I think it's doing that because it believes the content is from the external source... do you have "Microsoft" as the source for those assets?  Try changing it to "Tenant" as it appears in the JSONData blob for a custom asset.

**Comment by greg-e** [comment]
Huzzah! "Source" to "Tenant" worked!  We are trying this as an internal process and procedures library pulling together info from many different places in a single tenant.  Thanks for the insight! Your demo repository (LDCDNDemo) threw me off on "Source" where you had "JulieTurner".

**Comment by juliemturner** [comment]
Yeah, it can be anything you want... but since you're referencing your SharePoint pages inside your own tenant that's a special case because we're able to affect the styling of the content in the iframe and we treat "Tenant" as a special value which is really the value for any custom created content.
