### ISSUE TITLE
[QUESTION] Does Learning Pathways support more than once instance in the tenant?

### ISSUE THREAD

**Issue by pkbullock** [pnp/custom-learning-office-365#276]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [X] Installation
- [ ] Administration
- [ ] Custom Content
- [X] M365 learning pathways web part

### What is your question

Does Learning Pathways support more than once instance in the tenant? e.g. multiple learning pathways site. I have a large tenant with a requirement to have more than one site.

I see there are tenant properties which points to one. I have been following the installation script: https://github.com/pnp/custom-learning-office-365/tree/master/webpart - the admin page does not load with the error in the F12 console "This site is not the Microsoft 365 learning pathways site as defined by the tenant property MicrosoftCustomLearningSite".

Is there any workaround or does the web parts operation depend on these properties?

**Comment by juliemturner** [comment]
No, you can only have one instance per tenant. You can however put the web part on any site collection in the tenant you just have to manage the learning content from one central site. If you've tried installing multiple instances you now have things a bit scrambled as you've figured out.  If this is a test situation then you can just work in the last site that was created and delete the others. If this is a production scenario and you need to keep the original then you'll have to delete the others and run PowerShell to fix the tenant app property that points to the learning pathways site that is the master. [UpdateM365lpSiteUrl.ps1](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpSiteUrl.ps1)

**Comment by pkbullock** [comment]
Ok thanks, it’s only test environment thanks for the pointers.

Is the solution going open source or support for this coming? Reason is, we have a requirement for this but the tenant is shared with 11 orgs and various different uses and implementation.

If not, no worries, I’ll set client expectations.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by juliemturner** [comment]
It will not ever support multiple deployments. 

With regard to open source, I cannot really answer that question as that is not a decision I'm making.  But... since I did all the coding I can tell you that even if you had the source it would be a pretty heavy lift... the easiest way might be to hard code certain values and then do site collection deployments. 

One workaround I can think of, create custom assets for each of the orgs in separate site collections that are secured to people in those orgs.  Then create custom subcategories to address that content.  Then the web part is pinned to that subcategory.  Even though the other subcategories would be visible no one could access the content inside them.

Another option is to build custom content packs for each of the orgs, although that would mean maintaining the content manifests with no UI.

**Comment by pkbullock** [comment]
Ah, I just realized what I said re: open source, I am super sorry! hope I didn't offend, that didn't come across respectful towards you or your work. 

Thank you for your suggestions and your advice on this, I do appreciate this. I will have a look and see if I can get this working or if one instance would be fine.

**Comment by juliemturner** [comment]
Not even a little offended so don't worry about it, I was more meaning even with the source it's a pretty heavy lift to change it to work in a tenant app catalog deploy, it's just not architected for that. Let me know where you get and if you need to ask more questions feel free to submit them. I'll close the issue. Thanks.
