### ISSUE TITLE
Multilingual Support still not available...

### ISSUE THREAD

**Issue by nicht01** [pnp/custom-learning-office-365#280]
Q2 is over in a few days and still multilingual is not available.

I understand that this is a Community Driven Project, but you should consider to adjust the communication for new features. The first Date for Multilingual was more than a year ago.

This is very disappointing. I even contacted everyone involved and got no chance or possibility to be a early tester.

**Comment by juliemturner** [comment]
Unfortunately, your statement is inaccurate. We have a hard dependency on SharePoint's multilingual pages feature which didn't go full GA until mid-May of this year.  Because of the delay in the full release of that feature we have been unable to do proper testing with partners in the early adopter program. That is ongoing now and things are proceeding well but since I can not guarantee you a date I can't give you one, other than to say soon. We appreciate your patients on this matter as we would want to make sure that we don't rush the release and have an inferior end result.

**Comment by mhollinshead** [comment]
@nicht01 - we're sorry that you are having a negative experience here. As Julie mentions, we are hard at work ensuring the multilingual release is quality driven, considering the scope and complexity of this release. We're not updating our release roadmap at this time as an imminent release of multilingual is in the works. But again, we're being quality driven, so if that slips out of this month then we'll post an update. 
I would like to unpack your statement of attempting to join the Partner Early Adopter Program and not hearing back. As far as we can tell, we are current on all submissions, and respond in a timely fashion. Please email myself (mikeholl@microsoft.com) and include Karah (karahb@microsoft.com) so we can have a conversation on that topic. 
There is no customer facing early adopter program at this time and are considering how we fund and enable that in the future. But its only in planning at this point. 
Sincerely,
Mike

**Comment by juliemturner** [comment]
Version 4.0 was released. Please see the documentation on upgrading at [Adding Multilingual Support](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/AddingMultilingualSupport.md).
