### ISSUE TITLE
 Failed to load URL 'https://publiccdn.sharepointonline.com/<hidden>.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_e114746ed43501fdc6244d31b384916e.js' for resource 'M365LPStrings'

### ISSUE THREAD

**Issue by kapilmehtagit** [pnp/custom-learning-office-365#284]
## Describe the bug
CustomLearningViewer and CustomLearningAdmin pages showing web part loading error:  Failed to load URL 'https://publiccdn.sharepointonline.com/<hidden>.sharepoint.com/sites/appcatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/webpart-m365lpstrings_en-us_e114746ed43501fdc6244d31b384916e.js' for resource 'M365LPStrings' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

The sppkg was upgraded to 3.x.x.x a couple of months back and everything was working fine. This issue has suddenly occurred today. As a test, I've also provisioned a new Learning Pathways site collection from the service which shows the same issue. I've also accessed the site from a personal devices to rule out any firewall issues at our end.

I've also again run the UpdateM365lpCDN.ps1 with MicrosoftCustomLearningCdn -Value "https://pnp.github.io/custom-learning-office-365/learningpathways/ stored as the storage entity value. I've also tried resetting the default learning site URL with UpdateM365lpSiteUrl.ps1 but this issue persists. Would be grateful for any advice on how this could be resolved.

Many thanks,

CALLSTACK:
Error
    at r.t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_a5c001af28ebb9db01fe7777757c655a.js:1:839225)
    at new r (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_a5c001af28ebb9db01fe7777757c655a.js:1:1173394)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_a5c001af28ebb9db01fe7777757c655a.js:1:1227600)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_a5c001af28ebb9db01fe7777757c655a.js:1:1223645)
    at https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_a5c001af28ebb9db01fe7777757c655a.js:1:1217246

### To Reproduce

Deploy the Learning Pathways template via the service hosted via the SharePoint Online Provisioning Service with tenant admin permissions. Once the template has been deployed successfully, the page containing the Custom web part shows the above error such as SitePages/Get-started-with-OneDrive.aspx page. 

### Expected behavior

The web part should show the list of available learning packages. 

### Screenshots

![Learning Pathways web part error](https://user-images.githubusercontent.com/11500413/85875693-24f91c80-b7c4-11ea-9b21-baf213825e85.png)

### Learning Pathways version number

3.0.0.0

### Additional context

This has occurred recently without any changes from our end. I noticed the admin page was showing this issue initially, but the web part on the viewer page was ok. I uninstalled the app from the site, removed it from recycle bins, and then added that back in, but it didn't fix the issue. I then tried deploying a new Learning Pathways site using the service but the new site shows the same issue. I've also tried the two ps files mentioned above to update the storage entities.

**Comment by juliemturner** [comment]
So the error you're seeing has nothing to do with learning pathways but rather the SharePoint framework and your environment.  I think it's possible that by provisioning another site... I'm gathering you mean in the same tenant...  you've somewhat complicated the issue, but it's hard to know. At this point, I'm not sure how your configuration has been left.  Since you seem comfortable with "starting over" I might suggest you do that, as I'm gathering you have no customizations?  

If that is the case I would suggest you delete all the site collections that were created for learning pathways, and then also remove the solution out of the tenant app catalog.  Once you've done that, provision learning pathways from scratch and see where you are. 

If that is not the case, then I suggest you remove the new learning pathways site collection you created and go back to the original, including running the script to make sure that the tenant app property that identifies the master learning pathways site points to the right site, [UpdateM365lpSiteUrl.ps1](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpSiteUrl.ps1).

Once, you're back to 1 site, and you're fairly sure it's configured correctly, and you're still getting the error then we can address that but until I know that you have one master learning pathways site and that it's configured correctly it's a bit hard to move forward. The other question I might have, did you recently turn the SharePoint public CDN on? The URL's that it's trying to get to is the SharePoint public cdn endpoint.  Do you have any other SharePoint framework customizations in your tenant, and if so are they working?

**Comment by kapilmehtagit** [comment]
Hi Julie, thanks for a quick response.

This issue was occurring _before_ I provisioned a new site collection with the template to see if the issue occurred there too. I will remove the newly provisioned site from the tenant and reapply the PS1 scripts.

This original learning pathways site does have custom content so it won't be easy to simply delete that and replace it with a new one. 

We do have several SPfx solutions deployed in our catalog and all working fine, including those sourced from github repos. We do try and package them ourselves before deploying them, though, if sourced via open source repos. 

The learning pathway package, of course, was simply a sppkg file with no source code, so we are somewhat limited in trying to troubleshoot this issue. I wouldn't be too comfortable with deleting the current site and re-provisioning it if I can't be certain of the issue. We haven't turned on SP public CDN recently. But I will delete the newly provisioned site and re-apply the scripts to see if that resolves the issue. Thanks

**Comment by juliemturner** [comment]
There are several thousand tenants using the web part without issue so I'm certain that the issue is not with the sppkg but rather your environment. The scripts aren't going to do anything to solve the issue for you, unfortunately.  But at this point, you need to get back to a level playing field because your base configuration isn't correct.  What browser are you trying to run in?

**Comment by kapilmehtagit** [comment]
I've now deleted the recently created site collection and re-applied the scripts to point to the original site. This was working fine before today, so am not sure what has caused it to stop working suddenly. I have captured the console log showing several errors when loading the viewer. Any pointers would be useful and happy to try out any suggestions. Thanks,
![Learning Pathways web part error 2](https://user-images.githubusercontent.com/11500413/85883992-6e039d80-b7d1-11ea-9eaa-53c4ff54760c.png)

**Comment by juliemturner** [comment]
Can you find the call for that URL in the network tab and tell me if there's anything in the response?

**Comment by kapilmehtagit** [comment]
Hi Julie, looks like the issue has resolved itself today. I am not sure what caused it in the first place but whatever did has been fixed and therefore, the webpart now loads all the content fine. Thanks for you help and I think we can close this issue.

**Comment by juliemturner** [comment]
@kapilmehtagit  - Yeah I'm pretty sure the issue was with Akamai... but anytime you see this with something that was working that's usually the case, or an issue with guest access if you don't have the CDN turned on.  Glad it's working again.
