### ISSUE TITLE
 Issues with Custom Content Packs

### ISSUE THREAD

**Issue by dborchers-gc** [pnp/custom-learning-office-365#293]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Custom Content Pack URL switch automatic to /v4/ path

### To Reproduce

Add Custom Content Pack from GitHub Page and wait 5 Minutes ;-)

### Expected behavior

-

### Screenshots

hope the link worsk:
https://github.com/dborchers-gc/gc-adoption/blob/master/2020-07-08%2015_42_14-CustomLearningAdmin%20und%207%20weitere%20Seiten%20-%20Gesch%C3%A4ftlich%20%E2%80%93%20Microsoft%E2%80%8B%20Edge.png

### Learning Pathways version number

4.0.0.0

### Additional context

-

**Comment by juliemturner** [comment]
Yes, this is by design. The content packs need to support the version of the manifest that the web part uses.  There are changes to the manifest and structure for v4 so you will need to copy your v3 content into the structure under a folder titled v4. The up side is that the structure changes are not with the playlists.json and assets.json and only minor changes to the metadata.json.  You will need to put those three files into a subfolder for the language they are in... let's say en-us and there needs to be a root manifest.json that includes what was removed from metadata.json.  You can look at the contents of in this repo to get an idea of what that structure looks like: https://github.com/pnp/custom-learning-office-365/tree/master/docs/learningpathways

**Comment by dborchers-gc** [comment]
ah okay that make sense ;-) i will try it - you can close it for now
