### ISSUE TITLE
[BUG] Microsoft 365 learning pathways has a configuration issue error after upgrade to V4 - The site is in Swedish 

### ISSUE THREAD

**Issue by MCMatStoryals** [pnp/custom-learning-office-365#298]
## Describe the bug

I am receiving the error If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Here's the console log: [Browser console.log](https://github.com/pnp/custom-learning-office-365/files/4897483/Browser.console.log)

### To Reproduce

>The site works perfectly fine on V3.0.4, but creates this issue when updating to V4.0. The default site language is in Swedish.

### Screenshots

![Annotation 2020-07-09 112630](https://user-images.githubusercontent.com/48782895/87054000-aa90b980-c213-11ea-8fc0-02907d26690a.png)

### Learning Pathways version number

>V4.0

**Comment by juliemturner** [comment]
On a non-supported language site it should fall back to English but apparently something is wrong because it's trying to load sv-se. So, clearly something is broken and we'll have to fix it.

**Comment by juliemturner** [comment]
I believe I have the issue corrected please let me know if you have further problems.

**Comment by MCMatStoryals** [comment]
Hey Julie thank you for the quick reply. I just back on the site to test again, but unfortunately ran into the same error.

Here's the new browser console: 
[Browser console new.log](https://github.com/pnp/custom-learning-office-365/files/4911431/Browser.console.new.log)

**Comment by juliemturner** [comment]
Do you have multilingual support turned on? I can see in the console that it's loading the English version now but something else is happening after which I can only speculate on, which isn't happening in my test environment, so I need some more configuration information.  Also, is this a new install or an upgrade?  If an upgrade did you have custom playlists/assets or subcategories?

**Comment by MCMatStoryals** [comment]
> Do you have multilingual support turned on?
Yes, with support for English enabled

> Also, is this a new install or an upgrade?
Yes, this is an upgrade from 3.0.4

> If an upgrade did you have custom playlists/assets or subcategories?
Yes, there are custom playlists, assets as well as subcategories

**Comment by juliemturner** [comment]
Ok, I'll test the scenario but I think the issue is that you have multilingual on and are supporting English which effectively means it's trying to load English twice since Swedish is not a supported language and falls back to English.  I'll set up this scenario and see what I can find, but effectively if you turn off multilingual support then I suspect things will start working properly.

**Comment by MCMatStoryals** [comment]
I switched off multilingual support, but still no luck 
[browser console 14-07.log](https://github.com/pnp/custom-learning-office-365/files/4918110/browser.console.14-07.log)

**Comment by juliemturner** [comment]
No matter what combination of things I try I cannot recreate this issue now that it's been fixed... although I did tighten it up a bit so that it doesn't load the same language more than once, although even when that was still happening it worked for me. What I do notice is that you're in the web part not the admin web part. For the time being, can we work in the admin page just to reduce the number of other errors your seeing on the page which is making it more difficult to debug from the log. So in other words navigate to CustomLearningAdmin.aspx and not only give me the log but also a screen shot of the new "About" screen which can be reached from the ...

![image](https://user-images.githubusercontent.com/7570936/87424969-e9739600-c5aa-11ea-8886-624650cca6ec.png)

**Comment by MCMatStoryals** [comment]
The CustomLearningAdmin.aspx is blank and the web part does not show up at all
[browser console CustomAdmin.log](https://github.com/pnp/custom-learning-office-365/files/4918781/browser.console.CustomAdmin.log)

**Comment by juliemturner** [comment]
Can you please try deleting all the list items with the specific title of "CustomConfig" in the list "CustomConfig". Since you have custom subcategories there will also be a list item in CustomConfig for that... and if you've ever created a CDN there will be a list id for that... do not delete those.

**Comment by MCMatStoryals** [comment]
It finally works now! Although I did lose the custom playlists. But after running "/SitePages/CustomLearningAdmin.aspx?forceUpdate=v3" in the URL, it forced the upgrade and all playlists are now as it should.

Thanks for your help @juliemturner!

**Comment by juliemturner** [comment]
Ok, that actually makes sense I think the upgrade got broken with the original bug and you needed to clear it out and rerun the upgrade to fix it.  Makes me happy I changed that upgrade process, clearly useful.

**Comment by MCMatStoryals** [comment]
Very useful upgrade process indeed! Thanks again Julie!
