### ISSUE TITLE
Learning Path content is not displayed

### ISSUE THREAD

**Issue by JosefSvejda** [pnp/custom-learning-office-365#308]
Hello,

I have been able to deploy the Learning paths succesfully, but even that i dont see any error on page, all the courses are not displayed on their respective pages. For every course, I can see only empty web part space. See screenshot below.

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/68537641/87917702-a9faed00-ca75-11ea-96d7-98c1e3feeb8e.png">

**Comment by juliemturner** [comment]
If you could provide some details...
- Is this a new install, if so when did you install it and did you use the provisioning service?
- What version of the web part are you using (look in the tenant app catalog)?
- Have you go to the admin page ever (customlearningadmin.aspx)... if so does that page load?
- If you go to the development console of the browser does that show any errors, that specifically reference customlearning?

**Comment by JosefSvejda** [comment]
Hello Julie,


  1.  Yes, I provisioned the service using this guide: https://docs.microsoft.com/en-us/office365/customlearning (provision ended succesfully).
  2.  Version 4.0.0

[A screenshot of a cell phone  Description automatically generated]

  1.  Yes, I can see the content

[A screenshot of a cell phone  Description automatically generated]

  1.  I see some unauthorized access issues

[A screenshot of a cell phone  Description automatically generated]



And maybe this one: [cid:image004.png@01D65F57.210138D0]





Strange is that I can see the “First Six Steps” course properly (unless this one is different from others …) – this is the only one that works.

[A screenshot of a cell phone  Description automatically generated]



Regards


Josef Svejda | Product Manager | RWS Moravia
T: +420 54555 2353 | M: +420 736 272877
www.rws.com/moravia<http://rws.link/kod6ww>

**Comment by juliemturner** [comment]
@JosefSvejda -- unfortunately your screenshots didn't come through, probably because you replied via email instead of using the GitHub UI (and of note you want to be careful responding via email because your email signature and all your PII ends up posted in github, I removed that information for you.)

So my takeaway is that the admin page loads and shows you all the content, correctly... is that right?

**Comment by JosefSvejda** [comment]
Adding all images directly. Yes, it seems like everything is deployed properly, but the web part is not shown,

<img width="836" alt="image002" src="https://user-images.githubusercontent.com/68537641/88266530-a498df00-cccf-11ea-979c-f504d82f5cb5.png">
<img width="765" alt="image003" src="https://user-images.githubusercontent.com/68537641/88266537-a662a280-cccf-11ea-92ce-4f1939423d95.png">
<img width="1610" alt="image004" src="https://user-images.githubusercontent.com/68537641/88266542-a82c6600-cccf-11ea-9a98-2e22c7094aab.png">
<img width="1299" alt="image005" src="https://user-images.githubusercontent.com/68537641/88266544-a95d9300-cccf-11ea-89aa-6b7ed7806cfb.png">

**Comment by juliemturner** [comment]
I believe since you said you're on version 4.0.0 of the web part that your bug has been fixed in the more recent versions, you're using IE or Edge?  Please try updating to the latest version, see instructions here:  https://github.com/pnp/custom-learning-office-365#updating-the-solution and if you're still having issues let us know.

**Comment by JosefSvejda** [comment]
awesome, it works on 4.1.1. Thank you very much.
