### ISSUE TITLE
 Deployment failed. Correlation ID: e3e4679f-c0dd-2000-3a66-5c37bd8b6b5d

### ISSUE THREAD

**Issue by JulienRouleaud** [pnp/custom-learning-office-365#309]
I tried to provision and update Microsoft Learning Pathways, but i am facing this issue. The deployment failed, i deleted all the custom learning files from the appcatalog before and I deleted my old sharepoint sites but this is not working.
![Annotation 2020-07-20 144704](https://user-images.githubusercontent.com/68547872/87939746-ce1bf580-ca98-11ea-9ece-a62d8ab4f37a.jpg)
![Annotation 2020-07-20 145325](https://user-images.githubusercontent.com/68547872/87939799-e12ec580-ca98-11ea-94a8-0005813b25f2.jpg)
![Annotation 2020-07-20 144704](https://user-images.githubusercontent.com/68547872/87939802-e2f88900-ca98-11ea-88c8-145aa83f5997.jpg)

**Comment by juliemturner** [comment]
If you could provide a bit more detail I'm not sure where you're at. So you tried to provision it didn't work. You deleted the solution from the tenant app catalog and deleted the site collection and then tried again and it still doesn't work?  Is that correct?  

- Are you an owner of this site?
- Can you validate that the solution is in the tenant app catalog and what version the solution is (customlearning.sppkg)?

**Comment by JulienRouleaud** [comment]
Yes exactly, I am owner of the site and as well admin of the tenant. You can see with the screenshot below the version of the package 4.0.0 (i tried as well with 4.0.2 version, but it was the same)
It seems like there is a problem with our app catalog.

![Annotation 2020-07-20 145325](https://user-images.githubusercontent.com/68547872/87949559-76848680-caa6-11ea-8180-10eeec32877d.jpg)

**Comment by juliemturner** [comment]
I agree, something is definitely wrong with the deployment of the sppkg file. I would as a first test download the 4.0.2 sppkg file from the repo (forget about version 4.0.0). You can go so far as deleting the entry that's currently there and then upload version 4.0.2.  You can generally follow the steps outlined in the [Updating the Solution](https://github.com/pnp/custom-learning-office-365#updating-the-solution), but instead of just uploading over the top, delete and upload it fresh.

If after you upload it deploys successfully then you're going to want to go back to your site collection and start with the admin page in your pages library, `customlearningadmin.aspx`.  When that is loading successfully then I think you've solved your issue.

**Comment by JulienRouleaud** [comment]
I followed your guidelines : i deleted 4.0.0 sppkg file and i uploaded 4.0.2, but same problem "Deployment failed. Correlation ID"...
We previously had 3.0.4 version but it was working.
Do you think the problem could come from our appcatalog or our sharepoint configuration? 
Can we delete and create a new app catalog ? (if you have the process i would appreciate :)
Do you have any recommendation?

**Comment by juliemturner** [comment]
There isn't a problem with your app catalog, I feel like your problem is the sppkg you're trying to upload... how are you downloading it? You should be going here: https://github.com/pnp/custom-learning-office-365/blob/master/webpart/customlearning.sppkg and clicking "download"...
