### ISSUE TITLE
 WebParts now working today

### ISSUE THREAD

**Issue by SJHCtrain** [pnp/custom-learning-office-365#311]
![LearnO365_missingData](https://user-images.githubusercontent.com/55410511/87979044-6f0daf00-ca9f-11ea-9c00-f0559941fd25.PNG)
Hi Julie,

Some webparts have stopped working today. We have the July 2019 , version 2.0.15.0 of Microsoft 365 learning pathways installed.

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

please see screen capture below.
Thanks,
Craig
![LearnO365_missingData](https://user-images.githubusercontent.com/55410511/87979001-5f8e6600-ca9f-11ea-931b-0a1be0e39684.PNG)

**Comment by juliemturner** [comment]
So I should probably start by letting you know that we're not updating or supporting the web part before version 3. Is there a reason you haven't upgraded? You're effectively running the pre-GA release of the web part.  All that said, that error is the one that is in the message about doing the pre-check.

>WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the Diagnosing Pre-Check guidance before submitting your bug.

**Comment by SJHCtrain** [comment]
Thanks for that fast response! Where do I download the latest learning pathways web part?
Craig

**Comment by juliemturner** [comment]
Please read the following instructions on the upgrade process: https://github.com/pnp/custom-learning-office-365#updating-the-solution  

If you have no custom content (playlists or assets) you don't need to worry about backups or anything, version 4 which is where we're at is more robust in the upgrade process so you should likely be fine regardless but good to know.

Since you are so far out of date you will also most likely want to do the additional step of updating your CDN endpoint which can be done by running the following PowerShell script: https://github.com/pnp/custom-learning-office-365/blob/master/webpart/UpdateM365lpCDN.ps1

**Comment by SJHCtrain** [comment]
Thanks again Julie!

**Comment by SJHCtrain** [comment]
Hi Julie,

I"m going to get one of our SP admins, Gord, to create a github  account and add to this thread. He's done all of the above, but we're still having issues and when we attempt to access the "Microsoft Learning administration" from the home page menu, the content is blank. I'm in the middle, so it's best that the two of you communicate directly.
Take care,
Craig

**Comment by juliemturner** [comment]
Did you go to the CustomLearningAdmin.aspx page in the root learning pathways site, is that working?  That is the place to start to diagnose the issue.

**Comment by GordEnglish** [comment]
HI Julie, I am Craig's colleague. We are brand new to M365 and SharePoint this year. We did not previously have a SharePoint instance on premise so this is all new to us. I followed the upgrade instructions to upgrade our Learning Pathways. We did upgrade from version 2.x. I'm not sure if this has caused an issue for us. I also updated the CDN endpoint. The customlearningadmin.aspx page also does not load any content. If you have any suggestions to follow to troubleshoot I am happy to give them a try. 

thanks,
Gord

**Comment by juliemturner** [comment]
Please start with these instructions:
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

In general, I need details about whatever is being shows as errors/issues related to learning pathways (customlearning) in the browsers console log.

**Comment by GordEnglish** [comment]
Hi Julie, we have gone through the steps in the diagnosis pre-check. Here are the results. Please let me know if there is anything that I can do to resolve the issue. 

thanks,
Gord


[swohealth.sharepoint.com-1595876339129.log](https://github.com/pnp/custom-learning-office-365/files/4983965/swohealth.sharepoint.com-1595876339129.log)

**Comment by juliemturner** [comment]
Ok, so based on the logs I think the issue is that the upgrade didn't get done properly. When upgrading you really need to to to the CustomLearningAdmin.aspx page first. So, let's have you try the following process:

1. Go to the CustomConfig list and delete all the entries with a title "CustomConfig".
2. Manually type/paste in the URL for the CustomLearningAdmin.aspx page by using the following template:
`{site url for master learning pathways site}/SitePages/CustomLearningAdmin.aspx?forceUpdate=v2`
so for example:
`https://consoso.sharepoint.com/sites/M365LP/SitePages/CustomLearningAdmin.aspx?forceUpdate=v2`
3. Click the "Start" button to upgrade your content from v2 -> v4.
4. Assuming nothing errors out, click "Close" to return to the admin page.  
5. If the admin page loads fine, ie it looks something like the screen shot below, then try loading one of the other pages and see if you still get the error.
![image](https://user-images.githubusercontent.com/7570936/88711296-fbdeeb00-d0e5-11ea-87e0-4538e81bac41.png)

IF something errors during the upgrade or the admin page doesn't load or the other pages don't load after this send me a console log of that page that doesn't load like you did above.

**Comment by GordEnglish** [comment]
Hi Julie, thanks for your patience. We removed all the entries with a title "CustomConfig" from the custom config list. The only thing remaining here is "custom sub categories". Unfortunately when I run the force update command it does not do anything, just goes back to the same error message "Microsoft 365 learning pathways has a configuration issue". I saw the new 4.12 update so we pushed that update out and retried but still get the same error. I have attached the console log for review. 

Thanks again for your assistance,
Gord


[swohealth.sharepoint.com-1596048060853.log](https://github.com/pnp/custom-learning-office-365/files/4996953/swohealth.sharepoint.com-1596048060853.log)

**Comment by SJHCtrain** [comment]
Thanks Julie and Gord for your diligent work as you figure out this puzzle!!
Craig

**Comment by juliemturner** [comment]
The problem I see is that it's unable to update the lists properly... Given how this conversation started I have to wonder if permissions were changed or something.  Can you please try the forceUpdate again and give me a screen shot of the error messages that the update screen shows? Do you have custom sub categories? Do you have custom assets and playlists?

**Comment by GordEnglish** [comment]
Hi Julie, thanks for sticking with us. We were finally able to get the app to load after removing the "custom sub categories" from custom config and running the ?forceupdate=v2. Thanks again for your assistance!

Gord

**Comment by SJHCtrain** [comment]
Hi Gord,

Don’t swear at me …  😉

But I went in to update the site and got the message below. Looks like another update is needed:

[cid:image001.png@01D67C79.EC45C210]
