### ISSUE TITLE
Can We Create 2 instances of Learning Pathway in Single tenant?

### ISSUE THREAD

**Issue by SuryaSandeepMandarapu** [pnp/custom-learning-office-365#318]
- [] Administration

Can we create 2 instances of learning Pathway in Single tenant with different custom content in them? Will that still work without any issues?

**Comment by juliemturner** [comment]
That has not been the architectural model since the beta version of learning pathways.  We only support tenant level deployment in the tenant app catalog.  You then have a main learning pathways site collection which is the source of learning content in whatever site collection you want to put the learning pathways web part. Please see the video for an overview of the architecture: https://www.youtube.com/watch?v=-sLXl_rKGxQ  If you need more flexibility you can look at the custom content pack concept, this can allow you to segregate custom content by maintaining it as a set of JSON files, or you can use minimal versions of those files to set up categories and then create all your custom playlists/assets using the UI. An overview of custom content packs is covered in the video.
