### ISSUE TITLE
The CustomLearningWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator

### ISSUE THREAD

**Issue by freefitz** [pnp/custom-learning-office-365#34]
Still having issues when trying to go to the CustomLearningAdmin.aspx after I have setup the custom learning site for the first time.  I have used the SharePoint PnP provisioning option 3 times now and have 3 new sites setup but still unabel to run the .aspx.  I have tried 3 different browsers, IE11, Chrome and Edge, same result 

"The CustomLearningAdminWebPart has not been properly configured and you do not have Owner rights to complete the operation. Please contact the site administrator".

**Comment by juliemturner** [comment]
@freefitz  So I think some of your problem is that by creating 3 different sites you have changed the location in the tenant app properties for the location of the home site for custom learning. Most probably the 3rd one you created is currently the master and CustomLearningAdmin.aspx web part will only work in that site collection.  You can check by going to that page in that site collection, with a browser other than IE as the version of the webpart currently has a bug in IE. If even using Chrome in whatever was the last site collection you created you still see the error please open the browser console and check for errors related to custom learning. (Ctrl+Shift+i -- in Chrome).  If whatever site collection you're in is not the master this message will be in the console with the url of what it thinks is the current master: “Microsoft Custom Learning Admin is not in the web defined by the tenant property MicrosoftCustomLearningSite: {current master site collection}”.  When you get that value the other two site collections could be deleted to avoid confusion.  Let me know what other error you have if that's not the issue.

**Comment by freefitz** [comment]
@juliemturner ok great that works now thanks.  I will remove the other two.
