### ISSUE TITLE
[QUESTION] Is there a way to force the language of the LP web part content?

### ISSUE THREAD

**Issue by benoitfournier** [pnp/custom-learning-office-365#354]
### Is there a way to force the language of the LP web part content?

- [] Installation
- [] Administration
- [] Custom Content
- [x] M365 learning pathways web part

When we create multilingual content we have different pages per language. If we create a page for the french content and include the LP web part, we should be able to set the language to french in the web part properties. That way, we would be able to see proper content for the language (french content for french page and english content for the english page).

The way it currently behave is that I will allways see LP content in my browser's or user's language. If I switch the language selector to the alternate page, it would alternate from french to english text but the web part's dynamic content stays the same.

Thanks

**Comment by juliemturner** [comment]
Yes, this is a known behavior that is a function of how multilingual pages and SharePoint Framework solution work together.  Unfortunately, there is no uncomplicated way for you to force the language of the content. If you have a user that has not set the default language in their delve profile, then the browser language will determine the user's language in SharePoint.  So that's the easiest way to test the translations as it's a simple thing to switch the browsers language.

**Comment by benoitfournier** [comment]
It is harder to maintain content because of that automatic language. Also, it looks weird to have mixed language content on the same page because some comes from the page variation and other from user's settings.

Can this be an improvement or there is no way to control it at all?

**Comment by juliemturner** [comment]
There is no way for learning pathways solution (which uses the SharePoint Framework) to improve this.  As I said this is an issue with the out of the box SharePoint multilingual publishing pages and SharePoint Framework solutions, so the SharePoint engineering team would have to change the behavior.

That all said, if I understand correctly then you can just go look at the page directly instead of reviewing it through the playlist as iFramed content. They will automatically be displayed in whatever language the user is defaulted to, as you can tell since your default language is what the web part is always displaying in. So maybe the solution is just to change the way you review/author.  Sorry wish I had a better answer.

**Comment by benoitfournier** [comment]
Thanks for the answer.
