### ISSUE TITLE
[ENHANCEMENT] Allow SharePoint search to search learning pathways content.

### ISSUE THREAD

**Issue by Stevin8813** [pnp/custom-learning-office-365#359]
**Is your feature request related to a problem? Please describe.**
There was a discussion a year ago about the search dialogue at the top of the Learning Pathways page.  [https://github.com/pnp/custom-learning-office-365/issues/123#issue-495669273](url).  

**Describe the solution you'd like**
The search returns no results because there is actually no Learning content on the site collection.  I would like to see if we can hide the search, or understand what other users are doing.  I believe this will be very frustrating to our End Users at 3M.

**Describe alternatives you've considered**
Re-Initiate contract with Brainstorm.

**Additional context**

**Comment by juliemturner** [comment]
I understand your concern but as I stated in the early issue there is no way, at this time, for SharePoint Search to search content in learning pathways. 

That said we could investigate an option to hide search from our web part so that users would only be able to navigate content, but I'm not sure that solves your problem as I think your point is that they would use SharePoint search and not find learning pathways content. If that is what you want, then in general, you can already do that by putting the web part in "Content Only" mode in the web part properties, although that then also hides the breadcrumb navigation.

![image](https://user-images.githubusercontent.com/7570936/92963455-779bb980-f440-11ea-815c-3fb02a0fcd58.png)
