### ISSUE TITLE
Admin page isnt loading

### ISSUE THREAD

**Issue by aecole2** [pnp/custom-learning-office-365#363]
Currently running the newest version and recently the admin page stopped working.  It acts as if it will load but nothing ever loads properly.  Tried several machines and several users and all getting same experience.
<img width="670" alt="adminpage" src="https://user-images.githubusercontent.com/16577159/93602171-42d3b900-f990-11ea-8dcf-6916c78948b4.png">

**Comment by juliemturner** [comment]
Please follow the instructions outlined in a new bug report, that way we'll have the information to assist.

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

**Comment by djhavli** [comment]
The instructions outlined in a new bug report were followed as suggested by juliemturner.  After following these instructions, we discovered an error message in the console that shed some light on our issue.

After initially creating our Microsoft 365 learning pathways site we decided to rename the URL, which we did using PowerShell.  It turns out that renaming the URL caused the 'Admin page isn't loading issue' because it was attempting to access a URL it did not recognize.

We found a possible solution for this here.
https://github.com/pnp/custom-learning-office-365/pull/263/files

As directed under '## Changing the URL of your Microsoft 365 learning pathways site', we attempted to run script UpdateM365lpSiteUrl.ps1 to update the Tenant App property.  Unfortunately, get the following error as a result:
 
![image](https://user-images.githubusercontent.com/12340917/96269561-24ada880-0f90-11eb-9850-b8cbe342fbcf.png)

Any help would be greatly appreciated.

**Comment by juliemturner** [comment]
The person/account being used needs to have access to the tenant app catalog.

**Comment by djhavli** [comment]
I believe the account being used does have site collection admin access to the tenant app catalog.  We followed the steps under _How to ensure you are a Site Collection Owner on the Tenant App Catalog_ in the following URL: https://docs.microsoft.com/en-us/office365/customlearning/custom_troubleshooting#how-to-ensure-you-are-a-site-collection-owner-on-the-tenant-app-catalog.  Here is what we see as a result.
![image](https://user-images.githubusercontent.com/12340917/97908522-6ec2b800-1d0c-11eb-9cdb-42e74a86db30.png)

**Comment by juliemturner** [comment]
Then I suspect you're not logging in with that account.  We use the "UseWebLogin" switch, if you've selected another user recently it's going to bypass asking you and just use that previously selected account. I have never spent time trying to figure out how to clear the cache but I think closing down PowerShell ISE will do it...

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
