### ISSUE TITLE
 Webpart not Loading

### ISSUE THREAD

**Issue by glissmam** [pnp/custom-learning-office-365#364]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

The Webpart is not Loading on a Site that is not the "Base" Site of Learning Pathways.

### To Reproduce

Install Learning Pathways on Site A. Add the App to Site B and add the Webpart on Site B.

### Expected behavior

I Expect that the Webpart is still loading and i can use different Playlists as on the Main Site of LP.

### Screenshots

in the 2. Picture you can see i cannot Choose any Playlist. When i am at the initial Learning Pathways Site, i can choose the different Playlists there as you can see in the 3. Screenshot.
![image](https://user-images.githubusercontent.com/63236858/93788952-89940e00-fc31-11ea-9d56-5b5fec8a0972.png)
![image](https://user-images.githubusercontent.com/63236858/93789068-ad575400-fc31-11ea-8239-1fd6db1c8093.png)
![image](https://user-images.githubusercontent.com/63236858/93789214-dbd52f00-fc31-11ea-9fbf-44ca43b5d242.png)
![image](https://user-images.githubusercontent.com/63236858/93790373-3f139100-fc33-11ea-8836-613797ab5567.png)

### Learning Pathways version number

4.0.0.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
So, two things.

- When you said you installed learning pathways on Site A... I'm trying to verify that you don't mean you installed it in a site collection app catalog.  I don't think you're saying that, because you mention adding the app to Site B, but I want to make sure I'm super clear. 
- You mention you're using version 4.0.0.0.  We had several issues and there were a couple of early patches, could you please update your webpart to the most recent version using the instructions found here: https://github.com/pnp/custom-learning-office-365#updating-the-solution

Once that's done, please go back to the CustomLearningAdmin.aspx page in (Site A) based on your description and refresh the page to make sure the cache's update.  Then try again and let's see what errors show in the console if any.

Thanks!

**Comment by glissmam** [comment]
Hey,
thank you for the quick response, now i updated the solution to the new version.
I got the main Site for learning pathways A and another Site B where i want to use the webpart on. But when i choose it i cant pick my/ it doesnt show my playlists.
The problem still exists, these are the error messages when i open the admin page:

![image](https://user-images.githubusercontent.com/63236858/93812370-ca038400-fc51-11ea-9e89-de61f707a7f6.png)

thank you

**Comment by juliemturner** [comment]
Have you defined any custom SubCategories?

**Comment by glissmam** [comment]
Yes, you can see on the main Site i can choose them:
![image](https://user-images.githubusercontent.com/63236858/93860907-02da4200-fcc0-11ea-95a8-59c97636ad02.png)

**Comment by juliemturner** [comment]
I'm sorry that's not what I'm asking, that's a (I think - although I can't read German) custom playlist.  I was asking if you had created any custom sub-categories. Unfortunately, you're crossing your problems and so I'm not clear on where the actual issue is as you're also saying you get errors when you open the admin page.  So, let's start by forgetting about Site B. Can you please verify that the CustomLearningAdmin.aspx page loads without issue in Site A which I believe is your master learning pathways site collection. If it does not please follow the instructions [here](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) and provide that feedback.

**Comment by glissmam** [comment]
Yes, we have added custom Playlists and Sub Categories.
This is the error message that comes up when i open the CustomLearningAdmin.aspx on the master learning pathways site collecton.

![image](https://user-images.githubusercontent.com/63236858/94825782-d4b6d980-0406-11eb-9c45-bb49ab6c79f0.png)

**Comment by glissmam** [comment]
Thank you so far, do you have any idea if this is a tenant setting somewhere? We got a test tenant, and from there everything is fine and works properly. It must be a setting somewhere in the production tenant

**Comment by juliemturner** [comment]
Um, no... this would be a networking problem not an Office 365 problem.  So what you're saying is that you are able to log into a test tenant, on the same computer and it works fine but doesn't work fine on your production tenant, on the same computer connected to the same network?

**Comment by glissmam** [comment]
yes, this is exactly what happens

**Comment by juliemturner** [comment]
It's a bit hard for me to debug remotely but based on that error it really seems like your network admin has some type of proxy set up on the production domain.

It would be helpful to see a screenshot of the browsers network tab... looking for the errors there.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
