### ISSUE TITLE
How to track progress?

### ISSUE THREAD

**Issue by thiagottss** [pnp/custom-learning-office-365#369]
Hi there,

I'm trying to find a way to track user progress. Is there any option to achieve this?

In short, I loved the solution and it is very handy! But managers want to know:

- How many users have watched "xyz" playlist.
- I want my whole team to read/watch a mandatory "playlist". How to track and remind the users to watch the training content?
- And others questions related to the same subject...

Thanks! :)

**Comment by eemancini** [comment]
Hello @thiagottss! So exciting to hear how you are using Learning Pathways to track learning across your organization. 

Since it is not a direct replacement for a Learning Management System, the reporting will be a bit more manual and you will not be able to see the length of time spent on the pages in the playlist. There were some teaser previews at Ignite this week showing more advanced page analytics with time spend (not shown in demos by user though) so maybe this will change. 

Since the playlist is a set of pages, you will need to run an audit for who viewed _each_ page in the playlist (https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#search-the-audit-log). This will only work for your custom assets though, not any of the Microsoft content that comes with Learning Pathways as this is outside your tenant and therefore outside the audit scope. You can set up an alert policy ahead of time if you know the list of users so you receive an email once this has been done. Depending on the size of your organization, this can become a bit cumbersome and the alert policy does not have the customizations I'd like to see to make this a truly scalable solution (listing Microsoft 365 Groups, scheduling the cadence of receiving the alert, etc). 

In addition to using the audit log to confirm each user viewed the page, you can create a Microsoft Form, embed it in a page, and add that page as the last in your playlist. This Form can be structured as a training attendee sign off-putting the accountability on the trainees to acknowledge they completed the training. Of course, this can be fact-checked with the audit log to see if they actually viewed those pages. The need to add the audit log step will really depend on the culture of the organization and the importance of the training.

To remind users that they need to watch the training, you could set up a flow in Power Automate based off a SharePoint list including the link to the Learning Pathways playlist and names for who needs to complete each. When they complete the Microsoft Form to acknowledge training, this can trigger a flow to your SharePoint list for training and update a field like "email reminder" to "no" so they no longer receive the reminders after training is completed.

A lot of this functionality comes out of the box with a Learning Management System so depending on the size of your organization, it might be easier to get the reporting and reminders you are seeking from a system built for this functionality. At a previous organization, the LMS couldn't house the content itself, it just handled the emails and reporting so we actually used it in combination with Learning Pathways. Learning Pathways is excellent at supporting a decentralized content model while centralizing all training content in one easy to navigate location for end users to find what they need.

**Comment by thiagottss** [comment]
Hi @eemancini, 
What an amazing answer. I appreciate that! 👍 

I think I got it. I'll try to add a custom content to check how it works when using my own pages.

As you said above, when consuming MS content the webpart renders the content inside the "same" page, so I can't get what the user is consuming... unless they use a "direct-link" like this one below:
https://tenant.sharepoint.com/sites/M365LP/SitePages/CustomLearningViewer.aspx?cdn=Default&playlist=959166d8-1cb7-4315-af20-541598ebecaa&asset=365-378767af-7ac3-4d68-9d0f-709b6948a76b

But when the user navigates through the content by themselves, the url will become "vague" as it won't change.

Anyway, thanks again!

**Comment by juliemturner** [comment]
@thiagottss -- to clarify an assumption you've made here that isn't exactly correct... The reason you cannot get information about the Microsoft content is not because it's iFramed into the page, it's because microsoft content is not hosted as a SharePoint page and thereby there are no metrics stored in SharePoint about the asset itself.  Whereas, when SharePoint pages are viewed in the iFrame metrics are being stored about page views as if the user went directly to that page.

**Comment by juliemturner** [comment]
Also, to further clarify you can embed the viewer web part on any other sharepoint page in any site collection and filter it to a specific category, subcategory, or playlist.  So you could effectively have page stats on that container page as well and have the link to the form on that page instead of as the final page in the playlist.

**Comment by thiagottss** [comment]
Hi @juliemturner -- thanks for the clarification. I got it right the first time. Sorry if I confused you. :D

I was thinking of something to put in the page (a custom extension or webpart) to get the url path (+querystring) and track usage.

**Comment by juliemturner** [comment]
Yep you could for sure do that with a SPFx app customizer extension and app insights for real power or just a SharePoint list or something for a simpler implementation.
