### ISSUE TITLE
Playlist > Asset > Custom Page not showing

### ISSUE THREAD

**Issue by hwaterman** [pnp/custom-learning-office-365#375]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

When I create the custom page (asset), I can create it and add my content, and publish the page. However when I go to the playlist and navigate through the assets, the custom page will only show for about 3 seconds, then the previous asset (URL link) shows again.

### To Reproduce

>Steps to reproduce the behavior

### Expected behavior

I expect that when I navigate from one asset to the other, they will load as expected.

### Screenshots

>If applicable, add screenshots to help explain your problem.

### Learning Pathways version number

4.0.0.0

### Additional context

>Add any other context about the problem here.

**Comment by juliemturner** [comment]
I can't say that I have ever heard of that issue but, based on the version number you've stated you are using a version with known bugs.  I would suggest starting by updating to the current released version by following the instructions outlined here: https://github.com/pnp/custom-learning-office-365#updating-the-solution

**Comment by hwaterman** [comment]
I updated and still have the same issue. Here is the video of the issue in action.

https://www.dropbox.com/t/yPUyCrgIMZ0NNHIF

**Comment by juliemturner** [comment]
That's interesting... can you share the url for the Microsoft asset you have right before your custom page (unless it's one of the Assets already loaded)?  I'll try and reproduce the issue.

**Comment by hwaterman** [comment]
I used different ones and it produced the same results. I was creating demo pages for a client site and have removed those.

**Comment by juliemturner** [comment]
Ok... but my issue is I cannot reproduce this in general. I have lots of examples of playlists with mixed content that are working perfectly, so I was hoping that your issue was related to the asset that you were specifically using. It feels like there is some type of redirect on your custom page but obviously I can't really debug anything from a video.  Maybe you can inspect the browsers debug console and see if there are any messages that would help identify the problem.

**Comment by awaller98** [comment]
This seems like a duplicate of #266 . @hwaterman can you confirm if enabling comments on the asset page has any impact?

**Comment by juliemturner** [comment]
@awaller98 -- similar but didn't seem the same, I thought your issue was content overlaying each other? If you create a new dev tenant and deploy learning pathways there, can you reproduce the issue... if yes then it's likely environment related, if not then it's likely related to the tenant.  Do you have any application customizers installed in the tenant, specifically in that site or globally deployed that could be interfering?

**Comment by Scu-OSN** [comment]
I am experiencing the same problem. If I activate the comments on the custom assets page, it works without problem. I am using the following versions:
M365 LPW 4.1.3
Edge 86.0.622.69 (Official build) (64-bit)
I will gladly give you more information/insights. But as I am an end-user, I will need detailed instructions.

**Comment by juliemturner** [comment]
@Scu-OSN -- I have been in discussion with my colleague @eemancini (my out of the box UI expert) and we're discussing ways to try and replicate the situation so that we can debug it.  Her suggestion is that you share a screen shot of the full browser window with the page in question in edit mode so that we can see all the web parts on the page (obviously you can blur out any proprietary details like the URL).  Then if you can record a video of the issue and share that as well, we can attempt to reverse engineer the situation and see if we can figure it out. Also, if you could tell us a little about the playlist that you created. Ideally if you can replicate the issue with a minimal amount of extra content.  Like copy one playlist and add one custom asset to the playlist to demonstrate the issue.

**Comment by Scu-OSN** [comment]
Hi @juliemturner . Here are the details you asked for. In the screen capture you can see, how the custom asset page does not get displayed. The content body just keeps displaying the previous content. If I switch on the comment feature in the custom asset page, the custom asset page gets displayed normally.
Another thing: if I am browsing back and forth in the playlist too quickly, suddenly the content body gets distorted. You see it happen in the screen capture. This problem also only happens if there is a custom asset in the playlist. With default playlists I have never seen it happen.
Thank you for your help. I hope you and @eemancini will be able to reproduce the problem.
![Custom Asset Page](https://user-images.githubusercontent.com/74588489/99792975-3b639400-2b28-11eb-89cd-c54bee780232.png)
![Custom Playlist](https://user-images.githubusercontent.com/74588489/99792978-3bfc2a80-2b28-11eb-8b9e-7242630af07e.jpg)
[Screen Capture.zip](https://github.com/pnp/custom-learning-office-365/files/5573086/Screen.Capture.zip)

**Comment by Scu-OSN** [comment]
Hi @juliemturner. Were the details helpful? Any news on this? Let me know if you need more information. Thank you!

**Comment by juliemturner** [comment]
@Scu-OSN -- We are still unable to recreate this scenario, but I also didn't see that you attached a video and just now watched it.  What I'm seeing is simply that the custom asset page isn't loading not that it's being skipped... if you repeat the process but with the browser console open i suspect there are error messages in the console.  Can you please capture those so I can review it. Instructions on how to do so can be found [here](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md)

**Comment by Scu-OSN** [comment]
@juliemturner , I have attached a screenshot of the browser console. I hope this is helpful. Let me know if you need more information. Thank you for your support!
![error messages browser console](https://user-images.githubusercontent.com/74588489/104001404-e34c2400-519f-11eb-90f8-11ca64d462a5.png)

**Comment by juliemturner** [comment]
I see you're pointing out a line item but that couldn't be it because that is for the page CustomLearningAdmin.aspx... which is not the page you're on... is it possible it was the page you were on previously?

Can you try this again but first clear the console before you click the next button... to clear it you click that circle with the line through it in the header of the console pane... 

Also, is it possible that the url for the asset is in tenant or site with a different host header or that the permissions on the page were changed so that maybe there's a security issue?

The other thing that is odd there is the 404 I'm seeing going to your sharepoint server to a site x.sharepoint.com/teams/search... is that the M365lp site... are you on the CustomLearningViewer.aspx page in the M365lp site?

**Comment by Scu-OSN** [comment]
Hi @juliemturner , I have cleared the console and taken new screenshots. Screenshot 1: clear console before clicking next (next is the custom page). Screenshot 2: console after having clicked on next. Screenshot 3: same as screenshot 2, but including warnings.

The custom page is in Site Pages of the M365lp site. I did not change the permissions. The page is as when added from the "new asset" dialogue in the playlist. And anyhow, it cannot be a security problem because the custom page is loading when the comment feature is activated on the page. The problem with the page not loading exists only when the comment feature is deactivated on the page.

The URL of our M365lp site is https://x.sharepoint.com/sites/M365LearningPathways (x=placeholder for our tenant name). I have no idea where this 404 is coming from. 

![2-errors](https://user-images.githubusercontent.com/74588489/104095491-67350780-5297-11eb-99c8-9cf3556a9770.png)
![3-errors and warnings](https://user-images.githubusercontent.com/74588489/104095493-69976180-5297-11eb-8434-bfc1c95fd29e.png)
![1-clear start](https://user-images.githubusercontent.com/74588489/104095495-6bf9bb80-5297-11eb-9711-f5360fffbb59.png)

**Comment by juliemturner** [comment]
Can you do it again with Info on... i'm not seeing anything that's related to your issue at all, also, if you could let is sit for about 1-2 minutes before you take the screen shot as I'm wondering if there's just a loading delay before the error

**Comment by jellis-thrive** [comment]
Closing issue due to request age and lack of further engagement

**Comment by Scu-OSN** [comment]
I am sorry for not replying earlier - I did not realize that @juliemturner asked me to redo the screenshots. I will deliver a new set of screenshots as soon as possible.
