### ISSUE TITLE
 Unable to display custom subcategories

### ISSUE THREAD

**Issue by X1M3N** [pnp/custom-learning-office-365#376]
I created a custom sub category and add a playlist to it, but the category and playlist do not display.
I followed various videos, but can't see what I am doing wrong.

Could you please help?

Thanks in advance.

![sub cat playlist](https://user-images.githubusercontent.com/72074119/94542569-3fbab180-0249-11eb-82cd-2f5dc030a734.png)
![sub cat paylist not shown](https://user-images.githubusercontent.com/72074119/94542581-434e3880-0249-11eb-86f3-3bb52af1ad9f.png)

**Comment by juliemturner** [comment]
I'm going to guess because I don't have quite enough information, but it looks like you're using multilingual and your view is showing French but the UI shows you only have the playlist in English.  You need to add the languages for each one you want the playlist to show up in.  Same with the subcategory, but you're not showing a screen shot of that so I can't confirm that.  But that's what I would check.

**Comment by X1M3N** [comment]
Thank you for your quick answer.

I know I did not give much information, but I did not know what else to share 😢 

Anyway, I did add the languages, but the sub category did not appear:
![image](https://user-images.githubusercontent.com/72074119/94691880-293c5500-0332-11eb-8c3c-799ac9bf38de.png)

I did the same with the playlist:
![image](https://user-images.githubusercontent.com/72074119/94691932-39eccb00-0332-11eb-9ac1-822a148284d7.png)

I know there is probably something I am doing wrong, but I can't figure out what...

**Comment by juliemturner** [comment]
So after you added the translations for the playlists and subcategory you then went and refreshed the page where you were viewing the results correct?

**Comment by X1M3N** [comment]
All the things I added are not being displayed, whether I am displaying the page in french or in english.
And a weird thing is that when I display the page in english, all the contents remain in french...

**Comment by juliemturner** [comment]
Understood, but I'm verifying that you refreshed the page because it won't show the content that got added until that happens as it has to re-read from the cache list.  Regarding showing in French regardless, that's actually not weird that's how multilingual pages work with the SharePoint framework.  The only way you can test the other languages is to either create a test user who's user profile is set to the other language or remove all languages from your profile which then lets you control the language SharePoint selects via the browsers language.

Regarding what you're showing me, you're also not seeing the Getting started with Teams playlist... so I'm assuming that you're not seeing that because you hid the Teams Technology... did you perchance hide the Excel technology as well?

**Comment by X1M3N** [comment]
Alright, noted.

My sincere apologies... Closing the tab and reopening it made it display the new sub category 🤦 

But it only worked for the sub category created under "get started".
I also created a "Power automate" sub category (under products), but that one is not getting displayed:
![image](https://user-images.githubusercontent.com/72074119/94697208-33615200-0338-11eb-88d7-310f9836ed22.png)

![image](https://user-images.githubusercontent.com/72074119/94697241-407e4100-0338-11eb-823c-b572fba534d5.png)

I should be seeing it under products, is it correct?
![image](https://user-images.githubusercontent.com/72074119/94697675-c13d3d00-0338-11eb-8063-fd6740fcdb81.png)

**Comment by X1M3N** [comment]
Well... I don't know what is wrong with that sub cat, but it won't show up.

I created another one which is being displayed:
![image](https://user-images.githubusercontent.com/72074119/94698314-75d75e80-0339-11eb-98d4-6f743185c2d1.png)

How can I delete the sub category "PowerPlatform"?

**Comment by juliemturner** [comment]
If it's a custom sub-category then you'll see the "edit" icon (pencil) and you can edit it and then a trash can to delete it.  If it's an out of the box sub-category then your only option is to hide it by clicking on the "eye" icon.

**Comment by juliemturner** [comment]
I'm going to close this due to lack of activity.  If you're still having issues, please feel free to open a new issue and reference this one providing more details.
