### ISSUE TITLE
Is it possible to add new categories?

### ISSUE THREAD

**Issue by susanlennon** [pnp/custom-learning-office-365#38]
My customer loves the idea of technical training being provided from Microsoft for all things Microsoft, but they're wanting to extend the site to all things training, e.g. new employee on-boarding, annual refresher training, etc. In order to do so we thought we'd want to add new categories for content not related to O365. Is that even possible? Thanks! Love the offering!

**Comment by juliemturner** [comment]
At this time, there is no way to add a Category although we've been discussing it.  That said the current categories really have very little to do with Microsoft... they are First Days, Products, and Solutions.  You can add as many sub categories as you like under any of these headings and in the future if we add the ability to add Categories you will be able to move existing playlists to that new Category.  Further, you can pin the web part (which can be enabled in any site collection) to a sub category effectively making a custom learning starting point of your own content.

**Comment by susanlennon** [comment]
Thanks for the info and quick feedback!

Thanks,
Susan
________________________________

**Comment by ggalipeau** [comment]
I feel categories have a lot to do with customer adoption. This training is touted as “customizable” for the end user. But, without the ability to add categories it is really just a Microsoft training vehicle because the categories are geared towards the Microsoft training. This product could be so much better if categories could be added. Then we can truly build custom training for our clients and integrate with Microsoft training. Subcategories aren’t good enough. We’ve already had many cases at our current client we’re the current category set just doesn’t meet our needs. In those cases we can’t use the very valuable WebPart in this solution and have to roll in our own navigation. Anyways, point is - I really think that the one thing holding this product back from being a truly integrated, customizable training that can mix Microsoft and client specific training is the inability to add categories.

**Comment by ggalipeau** [comment]
Sorry, I misspoke. The categories aren’t Microsoft specific. They are technology specific. It’s very hard to fit in training for non technology things in this setup. In addition, some clients speak about categories in terminology specific to their culture. Point is, we are really struggling using this product as a training center (which we really want to use it as)

**Comment by juliemturner** [comment]
@ggalipeau this issue was marked closed.  Please in the future if you have feedback create a new issue as others will not see your feedback. As far as your question goes, this issue will be addressed in a future release.
