### ISSUE TITLE
[QUESTION] Do the Global Admin (Tenant Admin) need to have their Display Languages disabled PRIOR to provisioning Learning Pathways?

### ISSUE THREAD

**Issue by Sunnysethi1** [pnp/custom-learning-office-365#387]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question
As a Global Admin, I am NOT able to disable the Display Language.  It is set up as English.

Does this prevent me in provisioning the multi-lingual Learning Pathways.

I was reading the documentation closely for Learning Pathways on this page:
https://docs.microsoft.com/en-us/office365/customlearning/custom_provision#ensure-the-tenant-admin-account-doesnt-have-a-language-selected

In the PROD tenant, I have the default language as English selected….how do I make the change to have “No languages selected”?

Currently, it is not allowing me to disable this.
 
In the final end, I was to use only the English & French content.

Thank you

>Provide related screen-shots to help us understand your question

**Comment by juliemturner** [comment]
I have honestly zero idea why that directive is there... I've never had it matter.  So, let me ask you this, do you want your default language to be English or French?

If English, then just ignore that step and provision and then turn off all the languages except French and you should be all set.

If you want the default language to be French then you're going to have to provision learning pathways manually without the page templates into a site collection you create with a default language of French.  For more information on this process see the documentation here: [Adding Multilingual Support](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/AddingMultilingualSupport.md)

**Comment by Sunnysethi1** [comment]
Thank you Julie for your quick response & guidance.

I provisioned the site in our PROD tenant.   We are making progress 😊

I have a regular user with the following profile (screenshot 1 attached):
Display language:  Set to English   (the Change Display language is greyed out)

Preferred language:  French (Canada)

Screenshot 1
[cid:image003.jpg@01D6AB0B.1EA94CD0]

Now when I navigate as a regular user with this profile,  I am directed to the French pages automatically (with Page title in French as expected)….however, the content is still displayed in English (screenshot 2)

Screenshot 2
[cid:image004.jpg@01D6AB0B.1EA94CD0]

Questions:

  1.  How do I get French content to render on French pages?
  2.  Does Display language & Preferred language play a role in the content that is displayed?  What should the setting be?
  3.  How do I get the French menus to display on French pages?

Thank you & greatly appreciate your guidance.

Cheers,
Sunny

**Comment by Sunnysethi1** [comment]
Thank you Julie for your quick response & guidance.

I provisioned the site in our PROD tenant.   We are making progress 😊

I have a regular user with the following profile (screenshot 1 attached):
Display language:  Set to English   (the Change Display language is greyed out)

Preferred language:  French (Canada)

Screenshot 1
 

Now when I navigate as a regular user with this profile,  I am directed to the French pages automatically (with Page title in French as expected)….however, the content is still displayed in English (screenshot 2)

Screenshot 2
 

Questions:
1.	How do I get French content to render on French pages?
2.	Does Display language & Preferred language play a role in the content that is displayed?  What should the setting be?
3.	How do I get the French menus to display on French pages?

Thank you & greatly appreciate your guidance.

Cheers,
Sunny

**Comment by Sunnysethi1** [comment]
![screenshot 1 - user-profile languages](https://user-images.githubusercontent.com/73409572/97123002-f7839780-16ff-11eb-885b-3a09bb13426a.jpg)
![screenshot 2 - french user - navigate to frech pages](https://user-images.githubusercontent.com/73409572/97123005-fbafb500-16ff-11eb-9088-0bf403833520.jpg)

**Comment by Sunnysethi1** [comment]
Here is also a screen shot of the MLP in the App Catalog - which I had provisioned on **Oct 15.**

Wondering if I need to delete this from the App Catalog & start all over again?

Thank you

![screenshot 3 - MLP in App Catalog](https://user-images.githubusercontent.com/73409572/97123280-76c59b00-1701-11eb-84d3-d505b395ba84.JPG)

**Comment by juliemturner** [comment]
This is the correct instructions for changing your language settings in SharePoint online: https://support.microsoft.com/en-us/office/change-your-personal-language-and-region-settings-caa1fccc-bcdb-42f3-9e5b-45957647ffd7

The MUI (or language the menus will show up in) is set in order of the profile, the browser settings, and finally the site setting.  If you're an admin sometimes it's easier (so that you can see what others are seeing) to remove all languages from your delve profile and therefore SharePoint will pick up your language from the browsers default language.

The webparts on the page do not honor the multilingual page setting, this is just the way SharePoint framework extensions work in SharePoint and there is no way for me to code around them that makes sense.  So whatever MUI you have the menu's will show in that language but if you move to a multilingual page the page content will show up in the translated language but the content in the web part will still show in your MUI language.  Other users will see the content translated if their MUI is in the language that the translated page is in.

I'm not sure why deploying on Oct 15 is any kind of issue, no, you don't need to delete and start over.

**Comment by Sunnysethi1** [comment]
Thank you Julie for the information.  It is very helpful.

Couple of questions related to "The MUI (or language the menus will show up in) is set in order of the profile, the browser settings, and finally the site setting". 

In the Profile - do you mean Display language or Preferred language (any precedence here)?

The browser settings - I am use Chrome, is there a language setting that needs to be activated in the Chrome browser?

The  site settings - is this within the Learning Pathways UI - on the right hand side (where I can select to toggle between English & French)?

Thank you Julie & greatly appreciate your help.

**Comment by juliemturner** [comment]
>In the Profile - do you mean Display language or Preferred language (any precedence here)?

I always go to Delve to set this... but you can also do it from the [settings in the suite bar](https://support.microsoft.com/en-us/office/change-your-display-language-and-time-zone-in-microsoft-365-for-business-6f238bff-5252-441e-b32b-655d5d85d15b). In Delve it's called "My Display Languages". I've only ever had the first one change anything so I can't speak to precedence.

>The browser settings - I am use Chrome, is there a language setting that needs to be activated in the Chrome browser?

I googled 'Change your browser language in Chrome' and this article tells you how to [change the language of your chome browser](https://support.google.com/chrome/answer/173424). As my above statement says if I'm in an admin role it's often useful to remove all the languages from "My Display Languages" in delve so that the browser is what drives your MUI and that way you can change it more quickly as changing your display language can take up to 24 hours to take effect.  You can also just create another test user that already has their display language set... many do this.

>The site settings - is this within the Learning Pathways UI - on the right hand side (where I can select to toggle between English & French)?

No this is not related to Learning Pathways this is a SharePoint thing. And in this case I mean the site collection's language. You can find it by going to Site Information -> View all Settings -> Language Settings.

**Comment by Sunnysethi1** [comment]
Thank you Julie.  Greatly appreciate your help.
