### ISSUE TITLE
CustomLearningAdmin.aspx site does not appear after successful provisioning

### ISSUE THREAD

**Issue by marosonda** [pnp/custom-learning-office-365#388]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [x] Installation
- [] Administration
- [] Custom Content
- [] M365 learning pathways web part

### What is your question

Hi Guys,

After getting "Provisioning completed" on sharepoint provisioning web-page, my Learning365 site is created but there is no CustomLearningAdmin.aspx created + I can't use Learning Pathways app on site. When i try to add new app i don't have it in "Apps You can add" list. I have to click  on " From Your organization" tab and there are Pathways marked as "You can't add this app here."

>Provide related screen-shots to help us understand your question
<img width="740" alt="pathways3" src="https://user-images.githubusercontent.com/73488676/97199276-20fbfc00-17b0-11eb-90b0-db9407835dcc.PNG">

**Comment by juliemturner** [comment]
Did you click on the "Find out why" link?

I don't really have enough information at this point to help you. Does the site have the pages, is the CustomLearningViewer.aspx page there, is the CustomLearning.spfx package in your tenant app catalog and is there any errors? Those are some of my initial questions.

**Comment by marosonda** [comment]
Hello Julie,

Of course I clicked :) but there's not much info unfortunately
<img width="734" alt="pathways4" src="https://user-images.githubusercontent.com/73488676/97201369-a97b9c00-17b2-11eb-91df-48ad502fae64.PNG">

The site has only Home.aspx and no other page was created. The customlearning was provisioned to the Apps for Sharepoint automatically and successfully. "No errors" message is there.

**Comment by juliemturner** [comment]
Actually, this is a lot of information... it's telling me the site was created and that the solution was properly deployed to the tenant app catalog and to this site but none of the template pages were successfully applied, so now I know where you're at and how you can either fix it or start over depending on what your needs are.

Basically, the provisioning process, although maybe it told you it was successful it was not. You could use the powershell command outlined [here](https://github.com/pnp/custom-learning-office-365/tree/master/webpart#execute-powershell-configuration-script) with the -SiteAdminOnly switch to fix the site collection so that you have the necessary pieces and that would solve your problems. 

However, you would not have any of the template pages which are there as examples and guidance for learning pathways but not necessary for its proper function... so, if you want those pages and that's important to you then I would delete this site collection and remove it from the recycle bin and delete the learning pathways solution from the tenant app catalog and try the provisioning process again.  If you continue to have problems with that then I would see this support information

>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

**Comment by marosonda** [comment]
Actually I tried deleting all the stuff few hours ago and recreate it and I ended up with same result. But now after running the script You suggested the CustomLearningViewer.aspx and CustomLearningAdmin.aspx pages were created.
It will sound stupid but am I finished now or is there still some config that I'm missing from config side? I have also disabled telemetry collecting successfully.

**Comment by juliemturner** [comment]
No there is no configuration missing if you successfully ran the PowerShell script.  So, odd that it won't provision for you but if you're satisfied to not have the templates then that's all you really need to do.

Bummer about telemetry because that's how we justify our existence for funding, but privacy is at the user's discretion as it should be, so glad you're all set 😁

**Comment by marosonda** [comment]
Can You give me little bit more insight on the templates I'll be missing ? Cause maybe the communication team will want them.

**Comment by juliemturner** [comment]
Um... no... 😁 Honestly it's not really my area.

I mean it's a built-out site of a bunch of pages with some content on them and the learning pathways web part and also includes some navigation to those pages, there are 11 in all... it's meant to be a getting started with learning pathways site.  Maybe try spinning up a development tenant and see if you can get it to provision into that because I have no idea why it's not provisioning.

![image](https://user-images.githubusercontent.com/7570936/97225186-b1364300-17a8-11eb-9296-42e2981ed312.png)

**Comment by marosonda** [comment]
I am actually trying it on development tenant unfortunately :D if I do the re-stage of the site and do everything manually and from the scratch...is there a step where I still can get the templates to the site or are they included only in automated provisioning ?

**Comment by juliemturner** [comment]
The templates are public, but you would have to build the deployment mechanism. Honestly, I would really suggest you just submit a ticket to the afore mentioned repository so that someone can figure out why they're not provisioning.

**Comment by marosonda** [comment]
Ok, I'm posting it there. Thanks a lot for Your help!
