### ISSUE TITLE
 Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. 

### ISSUE THREAD

**Issue by HeadrickJ** [pnp/custom-learning-office-365#399]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/master/webpart/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Each page on the SharePoint Success Site gets an error when trying to reach the Microsoft 365 learning pathways site.

### To Reproduce

>Steps to reproduce the behavior
 
I expected learning pathways content to appear on my SharePoint Success Site

>A clear and concise description of what you expected to happen.

### Screenshots
![Console-Errors-customlearningadmin](https://user-images.githubusercontent.com/32205054/99450927-0fa59b80-28e7-11eb-9f11-d18a3f299006.png)

### Learning Pathways version number

4.1.3.0

### Additional context

Both sites were added today to the tenant.

https://psav.sharepoint.com/sites/365LearningPathway
https://psav.sharepoint.com/sites/SharePoint-Inspiration

**Comment by juliemturner** [comment]
Looking at the console screen shot you provided lots of CORS errors trying to authenticate.  So... let's put SharePoint Success Kit aside for now and first go to your learning pathways site and validate that it's working since you said you added it today.

Can you please navigate to https://psav.sharepoint.com/sites/365LearningPathway/SitePages/CustomLearningAdmin.aspx.  Verify it loads and then can you share a screen shot to verify that you have two tabs at the top...

- Microsoft 365 learning pathways
- SharePoint Success Site

Assuming that is the case then we can move on to see if we can figure out what specifically is wrong with the SharePoint Success Site...

**Comment by HeadrickJ** [comment]
Hi Julie – I think I missed a step – and just found it – the “complete” button after adding the content pack.

SO sorry I wasted your time!  I think I am good now –




Jan Headrick
SharePoint Application Manager — PSAV®
■ office: 224.218.9594 ■ mobile: 817.929.5158

**Comment by juliemturner** [comment]
Glad you're all set!
