### ISSUE TITLE
Error after upgrading to latest version of the Learning Pathways  

### ISSUE THREAD

**Issue by gmparky** [pnp/custom-learning-office-365#402]
I have just upgraded the solution to version 4.1.3.0 and when accessing the CustomerLearningViewer.aspx page i receive an error. This is also the same error on the view pages. 

![image](https://user-images.githubusercontent.com/40665509/100234955-b0b5d700-2f23-11eb-973f-846acd3c57f4.png)

This is the information in the Browser Console 

![image](https://user-images.githubusercontent.com/40665509/100235285-1d30d600-2f24-11eb-8f9a-7625cc4335f1.png)

Learning Pathways version number 4.1.3.0

**Comment by juliemturner** [comment]
You didn't say what version you upgraded from... but you need to start with going to CustomLearningAdmin.aspx page. If you upgraded from version 3.x then by not doing so you skipped the upgrade process... if an earlier version of 4 then the upgrade messed up your cache and by going to the Admin web part you'll reset it.

**Comment by gmparky** [comment]
Hi, it would have been 2.x it's been upgraded from. Can i re trigger the upgrade process?

**Comment by juliemturner** [comment]
Ok, yes, then that's your issue you need to do the upgrade... so yes, you can retrigger it.  Use the query string parameter on the CustomLearningAdmin.aspx page of `?forceUpdate=v2`.  In this case you want that last bit to reference the version you're upgrading from so since you said v2.x then use v2 (if you had come from version 3 you would have used v3).

So in other words your URL in the browser will look something like:

`https://contoso.sharepoint.com/sites/M365LP/SitePages/CustomLearningAdmin.aspx?forceUpdate=v2`

**Comment by gmparky** [comment]
Thanks, I am sorted now I actually just reinstalled on the Site Collection 👍
