### ISSUE TITLE
 Issue after provisioning SharePoint Success Site

### ISSUE THREAD

**Issue by bhoekstra** [pnp/custom-learning-office-365#407]
## Bug description

After provisioning successfully SharePoint Success Site from the SharePoint lookbook, I see an error on /sites/SharePointSuccessSite/SitePages/Success-site-administration.aspx that says "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]"

### To Reproduce

1. Attempt to provision SharePoint Success via https://lookbook.microsoft.com/tenant/home/provision?packageId=0b860749-56a0-4c4c-992c-536d56d9accf; receive message that customlearning.sppkg is out of date
2. Update and publish customlearning.sppkg in App Catalog to version 4.1.3.0 using instructions from here: https://github.com/pnp/custom-learning-office-365
3. Navigate to CL (/sites/O365CL) site collection and update the app within the site contents
4. Successfully provision SharePoint Success from lookbook
5. Navigate to /sites/SharePointSuccessSite/SitePages/Success-site-administration.aspx and receive error message

### Screenshots
![image](https://user-images.githubusercontent.com/7408319/100783649-0c78d800-33dc-11eb-95e9-c01d6ba3ade1.png)

![image](https://user-images.githubusercontent.com/7408319/100783423-c02d9800-33db-11eb-99c3-bc5eabb5dc0d.png)

![image](https://user-images.githubusercontent.com/7408319/100783878-59f54500-33dc-11eb-84a7-0ee42156caa7.png)

![image](https://user-images.githubusercontent.com/7408319/100783958-772a1380-33dc-11eb-8e45-38ee20f42605.png)

![image](https://user-images.githubusercontent.com/7408319/100784068-9d4fb380-33dc-11eb-9196-3d32b440738e.png)

![image](https://user-images.githubusercontent.com/7408319/100784137-bb1d1880-33dc-11eb-94e1-e2c9176633f3.png)

### Learning Pathways version number

4.1.3.0

### Additional context

I hope I followed all of the correct procedures in reporting this issue!

**Comment by AZCounrtsMicsmith** [comment]
My users reported the same error starting today, although I successfully provisioned last week following the exact same procedure as listed by bhoekstra . Maybe there is an issue with the CDN?

**Comment by bhoekstra** [comment]
I don't know enough of how it should work, but I would guess that the main problem is the URL of metadata.json has a few extra forward slashes in it: https://pnp.github.io/custom-learning-office-365/learningpathways//v4//metadata.json (called from sp-pages-assembly_en-us_79d67b8bfeaa274e2496c682dae31da9.js)

![image](https://user-images.githubusercontent.com/7408319/100798351-8b2c4000-33f1-11eb-9163-e04ab570e9db.png)
![image](https://user-images.githubusercontent.com/7408319/100798952-4fde4100-33f2-11eb-8122-fd50d1cabf4c.png)

**Comment by AZCourtsMicsmith** [comment]
Now that is interesting. Good catch though. My error has only one extra slash in the URL. I tried the URL without the extra slashes and still a 404.

![image](https://user-images.githubusercontent.com/75337358/100800102-56b18780-33e3-11eb-8cb7-afaec46e695e.png)

**Comment by juliemturner** [comment]
So, I can only address one person at a time as the reasons why you're having issues don't necessarily have anything to do with each other although they might. So, since this is @bhoekstra issue I will try to address what I see posted from them. 

The double slashes in the URL imply something else, but let's ignore that for now.  

Looking at what you posted above I'm not sure I see where you completed step 10 & 11 in the following documentation: https://docs.microsoft.com/en-us/sharepoint/provision-sss#provision-the-sharepoint-success-site-to-your-tenant-from-the-learning-pathways-administrative-page

So my ask is that you review those steps, and then go to the Microsoft 365 learning pathways main site and navigate to the "CustomLearningAdmin.aspx" page.  **Microsoft 365 Learning Pathways** should be the left most content pack and then (assuming you have no others like I do -- i.e. Julie's Content) you should see **SharePoint Success Site** next to it.

![image](https://user-images.githubusercontent.com/7570936/100877196-6cbc5800-3476-11eb-8f16-358c9505e9be.png)

Assuming you do and you click on SharePoint Success Site there, what do you see?

**Comment by bhoekstra** [comment]
Thank you, @juliemturner! The trick was going back to the SharePoint Success Site tab in the Microsoft Learning Pathways admin page and clicking the button "Update Content Pack" or "Confirm" -- I can't remember what it was called, but that solved it. 

I do think that the documentation that you land on from https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/introducing-the-sharepoint-success-site-drive-adoption-and-get/ba-p/1927436 might need to be updated because I just followed the instructions to provision directly from the SharePoint lookbook, and I didn't see the update content pack step. 

Thank you again!

**Comment by AZCourtsMicsmith** [comment]
Thank you @bhoekstra! That did the trick! What was strange, is the complete box wasn't there for me. There was the little ad box at the top right to provision the SharePoint Success site which took me to the look book page. Once I went there, the "complete" box then appeared. Thank you both for your help!
