### ISSUE TITLE
[QUESTION] Upgrade from v2 to v4

### ISSUE THREAD

**Issue by rachoksh** [pnp/custom-learning-office-365#419]
Has any one upgraded from v2 to v4?

Any known issues?

Was it as seamless as the upgrade from v3-v4?

Our v2 site is deployed, customized, and permissioned in SPO and  we are preparing to pin Learning Pathways in Teams for Government (GCC).

Any gotchas to be aware of?

Thanks

**Comment by juliemturner** [comment]
If you already have it working in GCC you should be ok. I would recommend you make sure you go to the most recent release of learning pathways which is 4.1.3 (although I anticipate and update to 4.1.4 on Thursday). 

Also please [read through](https://github.com/pnp/custom-learning-office-365#current-release-version) the procedure for updating as well as backing up your custom list content. Specifically pay attention to this last step in the process as it's often skipped.

>Finally, in your main custom learning site, navigate to the Site Pages library and to the CustomLearningAdmin.aspx page. Make sure this admin page load successfully without error. You may be prompted to complete a 'Data Upgrade' if you are updating to a new major version of the solution. Please run the update and assuming everything works as expected you would then close the update and the admin web part will load the content. If you have problems at this point, please open a new issue for assistance.

If you get an error while performing the update, it can be re-run. Also given how significant your migration is you may end up with some abandoned playlists which will show up on the admin page in a category at the top called "Abandoned".. it's simply a matter of editing those custom playlists to assign them to a new "home" category.

**Comment by rachoksh** [comment]
Thanks Julie for your support. The cx installed the update package, but couldn't finish the install because there's no prompt to update on the page referenced in the guidance. 

The Cx noted that the Deployment says Yes, but the Tenant Deployment says No when looking in the App catalog.

Attached screenshot.

Any suggestions? 
Thanks
![LP](https://user-images.githubusercontent.com/26829811/102357587-7a94d180-3f7c-11eb-8a9c-07a70a8537e0.png)

**Comment by juliemturner** [comment]
It should say No for Tenant Deployment... that would indicate that the web parts were set to be deployed to every site collection existing now and that are created in the future, and that is not how this solution is configured... each site collection you want to use learning pathways in you need to add it.  

Effectively, you have now already upgraded and may end up with problems if anyone hit's any of the instances of the web part out there.  I am hoping that you did the backup step ahead, in case... and that you now with all priority navigate to the CustomLearningAdmin.aspx page so that it can process the update with regard to your custom content and setup.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.
