### ISSUE TITLE
[QUESTION] Permissions

### ISSUE THREAD

**Issue by JesseBrandsma** [pnp/custom-learning-office-365#433]
Hi,

When installing, you'll need to set a persmission scope. The guide says this is only for installation. Is there a discription or declaration that nothing will be send to another party? 2. is there a way to disable rights after installation?

We work in a company with a medical files stored on SharePoint.

Thank you

Jesse

**Comment by juliemturner** [comment]
Sorry for the delay in my response I was verifying the first part of your question.  Unfortunately, there is no official statement I can point you to that says nothing will be sent to another party, that just doesn't exist... I can tell you that the reason for the permission scope is so that the automation engine can provision the site collection and deploy the solution to your app catalog for you. Unfortunately to do that, the amount of permissions needed is quite broad. That said you can absolutely remove the app registration(s) after the fact by going into the Azure Portal, to Azure Active Directory -> Enterprise Applications and deleting it. The one called `SharePointPnP.ProvisioningApp.Tenant` would have been the one used for provisioning learning pathways.  It is never used again other than to provision.  That said if that isn't enough you can manually deploy learning pathways you just will not get the templated site pages with translations. They are not needed to make the solution run but some people like the "getting started" nature of it.

**Comment by juliemturner** [comment]
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Comment by JesseBrandsma** [comment]
Thanks for the reply!
