### ISSUE TITLE
Edge browser not consistently offering to translate the content on the Microsoft 365 learning pathways site.

### ISSUE THREAD

**Issue by swallace2020** [pnp/custom-learning-office-365#435]
The Microsoft 365 learning pathways site has been set-up to include Spanish and Portuguese. Delve profile and Edge language settings have been updated to include these other languages. I have recordings showing the translation box in the browser that offers to translate the play lists into another language. I cannot consistently get this to work. Is this a known issue or is there something more we need to consider to get this to work consistently for all our employees? Have screen shots available but do not see an option to add them here.

**Comment by juliemturner** [comment]
To add images, you drag and drop or copy and paste them into the editor text box and it will upload the image.

As to your question I have no idea what you're referencing. I will say learning pathways doesn't "translate" content with a button, the content appears in the MUI language of the user viewing the site which has to do with either the delve profile language or the browser language depending on what is set where. If you have a delve profile language that will take precedence.  All learning pathways content will be shown in the language of the delve profile (or if not set the browser language) ... there is a multilingual page feature you're utilizing that's a feature of SharePoint where you can switch to another version of the page in a different language. It is by design -- not of learning pathways but of the development framework for extending SharePoint -- that the custom web part that shows content uses your delve profile language to pick the language of the learning content to show.  I have no idea if that's the question your answering.

**Comment by swallace2020** [comment]
@juliemturner thanks these are the images I wanted to provide.

![Edge Translations Feature](https://user-images.githubusercontent.com/61441493/103819577-efad7100-5027-11eb-8932-f669c1774275.jpg)
![Edge Translations Feature Icon](https://user-images.githubusercontent.com/61441493/103819595-f4722500-5027-11eb-9c90-cb0a8265a40f.jpg)
![Edge Translations Working on Custom Learning Admin Page](https://user-images.githubusercontent.com/61441493/103819602-f76d1580-5027-11eb-90a4-23a1eca720c8.jpg)

**Comment by juliemturner** [comment]
Yeah I mean that's a browser feature and has no bearing on how learning pathways works... I don't think I can help you.

**Comment by swallace2020** [comment]
@juliemturner ok thanks.
![Playlist Webparts](https://user-images.githubusercontent.com/61441493/103819878-84b06a00-5028-11eb-8cbd-7c7d236a7582.jpg)

**Comment by juliemturner** [comment]
So that you understand based on this last screen show your delve profile (or your browser setting if you don't have a delve profile language) is clearly set to English. When you change your delve profile language it can takes several hours for that change to take effect.  If you are really a person who needs to test this there are two options to make this easier.. 1, remove all languages from your delve profile and then the UI will respond to the language your browser is set to and responds basically immediately.  2. Create a second user who's profile is set to the language you'd like to test.

**Comment by swallace2020** [comment]
@juliemturner thanks. I'll test what you suggested. Currently I have a regular account (which is a read only account for Learning Pathways), then I have an admin account and am set-up as an Owner. I have adjusted settings to move Spanish as the default and have waited a day to check. 

![Delve Languages](https://user-images.githubusercontent.com/61441493/103820849-4320be80-502a-11eb-9b94-1837bfdbaeb2.jpg)

![Edge Language Settings](https://user-images.githubusercontent.com/61441493/103820858-461baf00-502a-11eb-8d65-512adb9d6bd7.jpg)

**Comment by juliemturner** [comment]
Um, i guess I'm confused, in the screen shot you show delve (so that takes precedence and nothing you do in the browser languages will have any effect), and Spanish is the second language down, so that makes English the default and what I see in your other screen shot is that your UI is showing in English... this is correct based on what you're showing me.

**Comment by swallace2020** [comment]
@juliemturner yes sorry I just moved Spanish to the second spot in that screen shot, but it was on Spanish when the previous screen shot was provided. I will follow the steps you shared and check again tomorrow.

**Comment by juliemturner** [comment]
You probably need to clear the bowser cache and restart it to see the udpate.
