### ISSUE TITLE
Provisioned 2 CLP sites in a same tenant,both point to the same admin Page

### ISSUE THREAD

**Issue by batilcl** [pnp/custom-learning-office-365#48]
Repro steps:

1. Run PnP provisioning on site collection#1 https://contoso.sharepoint.com/sites/clp1
2. Run manual web part installation on site collection#2 https://contoso.sharepoint.com/sites/clp2

Access file https://contoso.sharepoint.com/sites/clp2/sitepages/CustomLearningAdmin.aspx

Redirected to https://contoso.sharepoint.com/sites/clp1/sitepages/CustomLearningAdmin.aspx

1. Would like to understand the reason of this
2. How to do if customer has pilot and production sitecollections

Thanks.

**Comment by juliemturner** [comment]
You cannot have two "master" custom learning sites in the same tenant.  To be honest your scenario doesn't sound right.  If you have run the manual installation (which include a powershell script) then the master (assuming you did it in the order you said) should be the site clp2.  Which would mean if you access the CustomLearningAdmin page in clp1 it should give you an error message on the page not redirect you.

If you feel you need an entirely separate instance of custom learning then you need to create a separate tenant, maybe using a free developer tenant.  The reasoning for this is so that the custom content is all administrated in one site collection but the web part can display content in any site collection.
