### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by GiseliS** [pnp/custom-learning-office-365#485]
I'm a beginner in the forum. I configured Microsoft 365 Learning Paths, but my users are unable to access the learning pages.

**Comment by jnewgard-thrive** [comment]
Hi @GiseliS,

We will need additional information in order to assist.

Please provide the information requested in the new issue template and review the pre-diagnostic steps:

[Diagnosis Pre Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md)

![image](https://user-images.githubusercontent.com/80363676/113018990-5b423e80-913e-11eb-8350-60a83656e983.png)

**Comment by eemancini** [comment]
Hello @GiseliS, quick architecture explanation to get you started: You will need to provide access to the Learning Pathways site as well as every single site where you are pulling content. In the example of a SharePoint Champions site, the end user needs access to Learning Pathways, the IT Communication Site where the assets are being added from, as well as the site where the playlist is surfaced.
![image](https://user-images.githubusercontent.com/61661610/113027175-cb10f300-9157-11eb-80ef-1d39a87927bc.png)
