### ISSUE TITLE
Deployment to SharePoint Online CDN [QUESTION] 

### ISSUE THREAD

**Issue by cjwdormer** [pnp/custom-learning-office-365#503]
>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [X] Custom Content
- [ ] Viewer Web Part

### What is your question

Hi there just a quick question before I start down the road of custom content creation. 

**Backstory if you want it:**
Working for a gov entity that are looking to use Learning Pathways as a hub for their knowledge/guide/How To's etc.... obviously they are not keen on hosting data github due to the nature of some information so I am looking at alternatives such as azure cdn as a possibility. Using that platform though will pull in a ton of paperwork and architects that will slow the project down massively (we are looking to have this built inline with the move to 365 basically) so we are looking to towards using the SharePoint CDN instead (the private not the public).

**Actual question:**
If I deploy this to a private SPO CDN and then re-point the PnPStorageEntity  to said CDN will this work as a host for the custom content?

**Comment by juliemturner** [comment]
I think you have a bit of a disconnect about how learning pathways works... the content itself is not stored in github, just the manfiests... and for custom content almost everyone creates that in SharePoint itself to augment the content provided by Microsoft. However if you want your own custom content pack so you can have your own categories, technologies, levels, audiences, etc, etc then yes you can certainly make your own content pack and yes you can host those json files on an azure cdn but the content that is displayed is an iFrame to content living elsewhere. As I mentioned above normally SharePoint pages but it could be from some other system in your ecosystem.. the json files would only point to the urls for the assets it's displaying and only in the case where you wen't building custom content right in the learning pathways UX. The user trying to view the content needs to have access to that location of the asset urls and the content at that location needs to support being iFramed (this is where we're having a problem pointing to docs.microsoft.com content because it doesn't like being iFramed) otherwise I would stick with the SharePoint pages customization and for that you can do it entirely in SharePoint with only empty arrays as the playlists and assets json files. You may want to deploy this solution to a dev tenant so you can review the architecture more and also watch the [architectural overview video](https://www.youtube.com/watch?v=-sLXl_rKGxQ) if you haven't.

**Comment by cjwdormer** [comment]
Thanks Julie for the quick response and the clarity around the . I probably worded that better if I am honest it was before my first coffee of the day. That all makes much more sense now, much appreciated!
