### ISSUE TITLE
Lookbook failed to provision

### ISSUE THREAD

**Issue by ESWCodeBase** [pnp/custom-learning-office-365#506]
![lookbook](https://user-images.githubusercontent.com/28893353/116614799-65f01f00-a908-11eb-910f-91c6c7465ce4.png)

Screenshot has full details.

Correlation ID: 60893969-4752-4d71-b068-3944d1c1296d !

**Comment by ESWCodeBase** [comment]
Is anyone monitoring this 'ticket system'?  We were told by Microsoft to log the issue here instead of the main 'Submit a Ticket' through Office 365.

**Comment by jellis-thrive** [comment]
Hello ESWCodeBase,

This is the correct place to submit issues. However, from the screen shot we do not have enough information to provide you the best help.

Please review the pre-requisite steps here and ensure each has been met. If your configuration differs, please align it with the pre-reqs and try to provision again:
https://docs.microsoft.com/en-us/office365/customlearning/custom_provision

Did you receive an email with any additional information about the failure? If so, what did it say?

What happens if you try the provisioning again? 

Do you always receive the same error?

Is there anything special about your tenant? For example, is it a GCC tenant or other secured tenant?

We will be glad to follow up with you once we have more info to help!

**Comment by jellis-thrive** [comment]
Closing issue; requestor was advised of the proper place to present the issue with the Provisioning service
