### ISSUE TITLE
Unable to install via Lookbook or PowerShell - Permissions error?

### ISSUE THREAD

**Issue by glblinck** [pnp/custom-learning-office-365#507]
I'm working with someone who's trying to install Learning Pathways, but is unsuccessful. The problem doesn't get detailed when trying to install with Lookbook (it just says unsuccessful), but trying a PowerShell install yields this error:

> C:\Users\ajwilliams\Downloads\custom-learning-office-365-main\custom-learning-office-365-main\installation\M365lpConfiguration.ps1?
> 
> [D] Do not run [R] Run once [S] Suspend [?] Help (default is "D"): R
> Microsoft collects active usage data from your organization’s use of Microsoft 365 learning pathways and the use of Microsoft’s online content. Microsoft will use this data to help improve the future Microsoft 365 learning pathways solutions. To learn more about Microsoft privacy policies see https://go.microsoft.com/fwlink/?LinkId=521839. If you would like to opt out of this data collection, please type Ctrl-C to stop this script and see Readme file ("Disabling Telemetry Collection section") for instructions on how to opt out.
> 
> Press Enter to Continue:
> 
> Failed to authenticate to https://kcmo.sharepoint.com/sites/LearningPathways
> AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0ff1-ce00-000000000000'.
> Trace ID: ab17f03b-46dd-468c-b460-38076b3be600
> Correlation ID: 6c1edc06-6672-4d48-88ef-c5d6cb14316b
> Timestamp: 2021-05-03 13:55:43Z
> PS C:\Users\ajwilliams\Downloads\custom-learning-office-365-main\custom-learning-office-365-main\installation>

I've done many of these installs before where MFA is used, so this doesn't seem like it would be the only problem. Is this an error that someone has run across before? The incomplete install seems to be the same for attempts via Lookbook and via Powershell.

**Comment by jnewgard-thrive** [comment]
Hi @glblinck 

Please confirm the pre-requisites have been reviewed and confirmed
[Learning Pathways Prequisites](https://docs.microsoft.com/en-us/office365/customlearning/custom_provision#prerequisites-for-multilingual-support)

Additionally, any issues that occur during provisioning should send an email notification to the address provided in the Look Book UI:
![image](https://user-images.githubusercontent.com/80363676/116937930-35212a00-ac27-11eb-9141-089afffae967.png)

Check for this message which could possibly have hit the Junk folder or otherwise been caught by email security configurations

Regarding the message you received with the Manual Script, this is not indicative of a configuration failure, rather, if you provide credentials using the -Credentials switch, your tenant cannot require MFA. For MFA, do not use the -Credentials switch.

**Comment by juliemturner** [comment]
@glblinck  - I think your issue is that you're trying to launch the PowerShell with credentials and you're using MFA so that doesn't work and you need to use the weblogin method which will happen if you don't pass credentials.  That said I would encourage you to use the lookbook for provisioning as you'll get a richer experience.  If you're still having problems provisioning you can submit issues for SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).
