### ISSUE TITLE
[ENHANCEMENT] We would like to have the option to enable multiple languages but have the option to have certain pages translated and the rest should be displayed in the standard language

### ISSUE THREAD

**Issue by Annanas-12** [pnp/custom-learning-office-365#527]
We have currently the learning pathways with the multilanguage feature enabled. This works fine. However, we noticed that for learning pathways, we only have 2 out of 4 enabled languages, the multilanguage feature does not work perfectly.
I would like to give an example. We have used a customized learning path (combination out of customized plus standard Microsoft pathway) and translated it in 2 (German,English) out of four languages. For the remaining two languages (Spanish and French) we want to let it displayed in our standard language English. However, when colleagues access the learning path using a browser language that we have enabled but not translated into the appropriate language (Spanish in this case), only a blank page is displayed and not the default English page. We need to enable all four languages so that we can translate and offer other learning paths in 4 languages. Therefore, we would like to propose a new feature enhancement. The function should use the default language page (as a fallback page) for browsers that are set to one of the enabled languages (e.g. Spanish), but where certain learning paths are not offered in that language.

**Comment by juliemturner** [comment]
We made a very deliberate decision to make it work the way it does because that then gives the opportunity for both scenarios to exists. If you want to use the English version for a language you support but haven't translated, then you just need to copy the English version and call it Spanish or whatever. This way those who want to not show a playlist or subcategory for a language they haven't translated for also have the ability to do so, if I force it to show the default language than those that want to not have a translation show up cannot do so.

**Comment by dcashpeterson** [comment]
Removing enhancement on this as it was built as designed to accommodate the functionality requested. If you would like the non-translated languages to have the default language content then you can copy it into the Spanish page as Julie suggested.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
