### ISSUE TITLE
Fails to install 

### ISSUE THREAD

**Issue by castilld5797** [pnp/custom-learning-office-365#528]
The Microsoft Learning Pathways fails to install on our production tenant. I believe it is due to our vanity URL's (https://sites.bms.com for our SharePoint tenant and https://tenadmin.bms.com for our SharePoint Admin Center.  Screen shot of error message is attached. Note  that I'm able to install it in our sandbox tenants (which conforms to the standards URLs for the SharePoint tenant and sp admin portal). 
![pnp_error](https://user-images.githubusercontent.com/8749850/120315299-338c6580-c2aa-11eb-9af7-ba06ef1f5ebe.png)

**Comment by jellis-thrive** [comment]
Hello @castilld5797 

You are correct, the issue is a result of the vanity URL variable in the automated provisioning process. Please use the manual setup instead:

https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup

In the script you will have to run per the instruction, you can manually specify the tenant values which are causing the automation to fail. Here is a reference to the script itself:

https://github.com/pnp/custom-learning-office-365/blob/main/installation/M365lpConfiguration.ps1
