### ISSUE TITLE
Expanding any section of accordion, the sections and content below accordion disappears

### ISSUE THREAD

**Issue by SandeshGawdeLSEG** [pnp/custom-learning-office-365#533]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

Expanding any section of accordion, the sections and content below accordion disappears.

### To Reproduce

Go to Learning pathway webpart and then > Excel > Common use of functions > Calculate the difference between two dates > Other date and time calculations
Click on first section of accordion. After clicking on first section, rest of all the accordion sections along with page content below accordion disappears.

### Expected behavior

Accordion content along with page content below accordion should be visible irrespective of expanding the accordion.

### Screenshots

![Accordion_beforeExpand](https://user-images.githubusercontent.com/85348498/121322592-bbb6de80-c92c-11eb-8f6a-606f691759f3.png)
![Accordion_afterExpand](https://user-images.githubusercontent.com/85348498/121322617-c5404680-c92c-11eb-9801-ef76955d55e5.png)

### Learning Pathways version number

4.1.4.0

### Additional context

>Add any other context about the problem here.

**Comment by jellis-thrive** [comment]
Hello @SandeshGawdeLSEG

We will work to reproduce this in an unchanged Learning Pathways installation and let you know if we experience the same.

**Comment by juliemturner** [comment]
@SandeshGawdeLSEG  - Unfortunately this is not something we can fix. Because the contents of the iFrame are not available to us we do the best we can to size the frame according to the content size when it's loaded based on the page telling us how big it is.  That implementation by the support.office.com team isn't perfect and doesn't send new messages about it's size when the content is resized (as an example expanding an accordion section). The other alternative is to make the pages grossly oversized, which is what we do as a fallback position when the pages don't communicate their size and many, many people complain about that. So, there is no good technical solution at the moment that the learning pathways solution has any control over.

**Comment by SandeshGawdeLSEG** [comment]
Hi @juliemturner @peterjkrebs Thank you for your reply. So, as mentioned by Julie, this is something known issue with Learning pathway webpart and cannot be fixed?

**Comment by juliemturner** [comment]
@SandeshGawdeLSEG - Again this is **NOT** an issue with the webpart it is an issue with the content that is hosted at support.office.com (and docs.microsoft.com). Because the content is in an iFrame and it is not hosted at the same origin because of browser security limitations we cannot programmatically tell anything about the content inside the iFrame. We rely on that content issuing a post message back to the host of the iFrame telling us what size the content is and if that size changes. Unfortunately that code has bugs and isn't working. We have no recourse to get it fixed.
