### ISSUE TITLE
Enable custom additions to "Technology"

### ISSUE THREAD

**Issue by BostonO365** [pnp/custom-learning-office-365#542]
I'm adding multiple non-Microsoft products to LP and would like to be able to tag them accordingly to the built-in technology dropdown when creating a playlist or asset.

**Comment by juliemturner** [comment]
Although I can see why you would want to, since the technology doesn't manifest itself in any way to the end user and is only used to help admin's hide technologies, they don't want to show to their end users. Because of that reason we have not seen a good reason to enhance the solution in this way due to the overhead of managing and merging custom technologies into the cache which already struggles with the heavy lifting over merging custom categories and playlists into multiple languages.

If you want to build your own metadata schema there are multiple ways to do so, you can build your own custom content pack from scratch (demo available here), or you can fork or copy the contents of this repository and host them yourself in either your own github repo or any CDN source and modify the json content at will as long as you don't break the data model. Of course, when content updates happen you will have to make sure to merge them together. 

What is your use case for needing a custom technology other than cleanliness in the admin view?

**Comment by juliemturner** [comment]
I would suggest watching this entire architectural overview video, it is somewhat out of date in that it's referencing v3, but the enhancement for v4 was around multilingual support so as long as you're only using one language it's effectively the same.  You can find the Custom Content Pack demo in the video as well, towards the end.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
