### ISSUE TITLE
[ENHANCEMENT] Custom metadata for Assets

### ISSUE THREAD

**Issue by BostonO365** [pnp/custom-learning-office-365#543]
I'd like to see Assets utilize a custom content type in the site pages library.  It'd be great if this content type contained columns that would surface an asset's assigned categories, subcategories, playlists and technologies.  Yes that does mean each of those columns would need to allow multiple values.  

This would enable a ton of search driven UI, and provide a bunch of out-of-the-box ways to group/cross-reference assets outside of the native playlists.  For extra credit, a keyword filter added to the webpart would be a game changer.

Imagine a tag cloud webpart on the LP landing page, click on a tag, get a custom list of all assets with that tag.

Just a thought.  :)

**Comment by juliemturner** [comment]
@BostonO365 -- All of that is a great idea but it's completely out of scope for learning pathways itself which is only an aggregator and viewer of pages from support.office.com and docs.microsoft.com and your own custom pages. You certainly can do everything you're saying but then that is outside the scope and purview of learning pathways itself because search has no concept of the external content that learning pathways surfaces.  It's not a search solution in that way... if you want a search solution then I think your points are excellent but then you don't need learning pathways to get that.
