### ISSUE TITLE
Error after updating from 4.1.x to 4.2

### ISSUE THREAD

**Issue by Teknia92** [pnp/custom-learning-office-365#548]
![microsoft learning sharepoint error after update](https://user-images.githubusercontent.com/86308161/122944268-aa66cc80-d345-11eb-8a83-dfec2dae49e9.jpg)

Just attempted to update the module.  Our site is now not accessible.

Initially the update installed and loaded was customlearning (2).sppkg    Tried to repeat the process making sure the correctly-named file was uploaded  customlearning.sppkg      Must have something to do with this?

**Comment by jellis-thrive** [comment]
Hello @Teknia92 

Please take a screenshot of what you see in the Tenant App Catalog for "customlearning.sppkg" . Please also make sure that the new file has been checked in, in the app catalog.

**Comment by Teknia92** [comment]
![tenant app catalog](https://user-images.githubusercontent.com/86308161/122947226-ffa3dd80-d347-11eb-8034-bade3a6abeec.jpg)

**Comment by Teknia92** [comment]
Thank you! Just checked the file in and we're UP!

**Comment by Teknia92** [comment]
I guess it is working for me, but not for my users.  I deleted the incorrect copy of the update from the library.  Does it have something to do with "Tenant Deployed?"

**Comment by jellis-thrive** [comment]
Hi @Teknia92 

The solution is intended to be a tenant wide deployment, yes. If you left the updated package in place - the one you checked in - it should not affect user's accessing the site in any way. What do they see when they try to load the page? If you check the site security, do they have at least Read rights, given through a group or individually?

**Comment by Teknia92** [comment]
Yes, I left the one I checked in in place.  

This is the error they are getting...

![ryans error](https://user-images.githubusercontent.com/86308161/122952667-295f0380-d34c-11eb-8290-1af668bd241b.jpg)

These are my site permissions
![site permissions](https://user-images.githubusercontent.com/86308161/122953103-7642da00-d34c-11eb-8c3e-3c24d6eaea04.jpg)

**Comment by Teknia92** [comment]
Looks like I might not have permission to deploy to the tenant?  
![deploy permission](https://user-images.githubusercontent.com/86308161/122953797-e81b2380-d34c-11eb-944a-1875b04390d2.jpg)

**Comment by jellis-thrive** [comment]
Hi @Teknia92 

To work on Learning Pathways you should be in the Owners group of the Tenant App Catalog - this is a pre-req to set up LP and generally those permissions stay in place after setup. If you are missing these permissions for maintenance, please work with colleagues to provision security for yourself as an Owner, or get someone with rights to deploy this for you. After that is done, let us know if you are still having issues.

**Comment by Teknia92** [comment]
Okay, thank you.  I'll take a look at that.

**Comment by Teknia92** [comment]
We are still struggling with this.  Not sure why its not working for other users (other than me).  Where do I go to ensure I'm in the owners group of the tenant app catalog?  I am the one who set up LP in the first place.  It isn't working since I updated it to the latest version.

**Comment by juliemturner** [comment]
Just jumping in here... unfortunately I think you got some misleading information... so let me backtrack:

- in this comment https://github.com/pnp/custom-learning-office-365/issues/548#issuecomment-866053896 I see two version of the solution package, I assume you've rectified that?
- in this comment https://github.com/pnp/custom-learning-office-365/issues/548#issuecomment-866075415 that isn't correct, the solution is NOT meant to be tenant wide deployed.  It looks like it was installed correctly in this link: https://github.com/pnp/custom-learning-office-365/issues/548#issuecomment-866085259
- If you can upload a new solution into the tenant app catalog then you have the rights you need.  By default, all the other users need to be in the visitors group of the tenant app catalog. I cannot tell from this comment https://github.com/pnp/custom-learning-office-365/issues/548#issuecomment-866082457 if you're sharing the permissions in the tenant app catalog or the main learning pathways site. To be blunt your tenant app catalog should have `Everyone except external users` added to the visitors group, they need to be able to have read access to be able to load the code for the solution to run.  If any of these "other users" are guests (i.e. external users) then they're going to have a problem and not be able to view the web part unless you do one of two things, either a, add `Everyone` including external users to the visitors group or turn the public CDN on so that they can anonymously access the code in the tenant app catalog. If that's your issue I can give you more guidance.

**Comment by Teknia92** [comment]
Thanks so much for your comments, Julie. 
I did remove the extra version of the solution package.  
Here is a screenshot of the Visitors group of the app catalog (they have read access)
![image](https://user-images.githubusercontent.com/86308161/123158291-98665600-d439-11eb-9ff4-af1e6d5707a7.png)
We are not including guests at this time.  
This is the permissions for the main learning pathways site: 
![image](https://user-images.githubusercontent.com/86308161/123158698-20e4f680-d43a-11eb-80b9-1694d14bf094.png)
Hope this helps.  :)

**Comment by Teknia92** [comment]
oops - sorry - the first screenshot is the wrong one. 
should have been this:  
![image](https://user-images.githubusercontent.com/86308161/123158872-4ffb6800-d43a-11eb-8f6f-ed40b93a6c5d.png)

**Comment by juliemturner** [comment]
Ok, that all sounds correct... so at this point can you confirm this (https://github.com/pnp/custom-learning-office-365/issues/548#issuecomment-866082457) is what all other users see when they try to load a page with the learning pathways web part on it. 

If so, can we simplify this somewhat...  Are you in the main learning pathways site? And the page they're trying to load... can you just confirm it with the page CustomLearningViewer.aspx?  If so, can you look at `site contents` and see if learning pathways shows as one of the installed apps?

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
