### ISSUE TITLE
customlearning.sppkg source code

### ISSUE THREAD

**Issue by felix-antoine-dion** [pnp/custom-learning-office-365#57]
#### Category

- [x ] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

First of all, thank you for these great contents. It will for sure support adoption in multiple organization.

I currently work for different french speaking clients who would greatly benefit from this webpart if it could be localized. I do understand that it migth be in the plans ( #12) but in the meantime, would it be possible from you to release the source code of the customlearning.sppkg's webpart? 

It would enable us to contribute or at least fork the project to meet our clients' language AND content needs. To be completely transparent, I was thinking about creating a content provider based a custom SharePoint list instead of relying on a remote json file, this would enable me to easily import new content from assets.json file's updates and at the same time modify the url to match the french rendition of the content (ie: translate support.office.com/**en-us**/client/0cf0055d-49f8-464e-9dfa-8f582b32453b?embed=true&ns=trainingservices&version=1 to support.office.com/**fr-ca**/client/0cf0055d-49f8-464e-9dfa-8f582b32453b?embed=true&ns=trainingservices&version=1).

Would that be doable?

Regards

**Comment by juliemturner** [comment]
Thanks for your question.  Yes it's absolutely possible and our intention to share the source code, however, the reason we haven't yet is because we're making fairly significant changes to the manifest JSON structure to handle multilingual content... I do not have actual dates but I can tell you the goal is sometime in Q3.  I think there might also be other updates that would negate your plans for changing the way the content it stored. If you're in a hurry the current solution could be made to work for multilingual by creating custom assets for the other versions of pages you want to use.  Then by creating a custom playlist you can add each of those Microsoft assets to your own playlist (and hide the Microsoft versions).

**Comment by felix-antoine-dion** [comment]
Hello Julie,

Many thanks for your quick answer, I'm glad that a multilingual feature is on its way. Is there any plan regardind the support of on premise installation (SharePoint 2019)?

**Comment by juliemturner** [comment]
Unfortunately no, as the code was written using version 1.8 of the SharePoint Framework.  SharePoint 2019 only supports solutions written using version 1.4 of the Framework and thereby it wouldn't be install-able... otherwise it would theoretically work but this is where you'd have to fork the code, create a new project and manually bring in all the code from the other version to make it install-able on the on prem server and then obviously also make sure that the .json files could be downloaded through any firewall...

**Comment by felix-antoine-dion** [comment]
Would it be possible none the less to have access to the code? One of my client is quite eager to have access to this solution but may take several years to switch from on-prem to online. I'm aware that the retrofit to spfx 1.4v may be tedious and that the playlist will have to be curated to remove SharePoint Online only material but am willing to give it a try.

**Comment by juliemturner** [comment]
I'm sorry, we're completely in flux, we will release the source code as soon as we can but it's not in a state that we can do so at the moment.

**Comment by felix-antoine-dion** [comment]
Well, I tried:) 
Thanks a lot for your prompt answers and your time. 
You can close the issue.
