### ISSUE TITLE
Learning Pathways content not rendering in Teams client - permissions issue? (follow-up to #569 )

### ISSUE THREAD

**Issue by RebeccaHallO365** [pnp/custom-learning-office-365#577]
## Describe the bug

Previously reported as Issue #569. Content not loading in Teams client. Sometimes just get a blank screen, and sometimes getting error: WEB PART NOT LOADING: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". 

Upgrading to v4.3.0.0 did not actually resolve the issue. We are thinking it may be a permissions issue - the attached log shows errors communicating with GitHub. GitHub is blocked for the majority of our employees. Can we bypass that call to GitHub?

### To Reproduce

Launch Learning Pathways from within Teams using link in Teams nav bar or from a link on SharePoint

### Expected behavior

When launched from the nav link in Teams, the full Learning Pathways page opens with links to all catalogs.

### Screenshots

![image](https://user-images.githubusercontent.com/88344495/129752551-3bff1594-549c-412e-8391-8efcadf54cf3.png)

### Learning Pathways version number

4.3.0.0 (upgraded from 4.2.0.0 since this issue began to occur)

### Additional context

The issue appeared to be resolved last time since I have access to GitHub so it was working for me, but other users don't, and are still seeing the issue.

**Comment by dcashpeterson** [comment]
@RebeccaHallO365 in looking at that log you are correct. This is most likely an issue with your organization blocking GitHub traffic rather than an issue with Learning Pathways. Unfortunately, all the Microsoft content in hosted in GitHub and there wouldn't be a way around that unless you created a custom build of Learning Pathways.  I would suggest seeing if your network folks can allow that domain.

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
