### ISSUE TITLE
[QUESTION] Error Running Powershell script while manual installation

### ISSUE THREAD

**Issue by chandni-agarwal** [pnp/custom-learning-office-365#578]
I was trying manual installation and while trying to run the powershell script, I got this error :
![image](https://user-images.githubusercontent.com/23003280/130051166-99e183e7-b439-488d-9296-6e21685743b6.png)

Any suggestion on resolution?

**Comment by ToddKlindt** [comment]
The Custom Learning Pathways installer was written when the older SharePointPnPPowerShellOnline module was the current one. We haven't updated the scripts for the PnP.PowerShell module because that introduced a dependency on an Azure Application being registered. It got complicated, quick. :)
You can install the SharePointPnPPowerShellOnline module with this line in an Admin PowerShell window:
`Install-Module -Name SharePointPnPPowerShellOnline -AllowClobber`
Then open up a new PowerShell and import it directly with 
`Import-Module SharePointPnPPowerShellOnline`
Run the Learning Pathways installation in that window. It should work. You can remove that module after you have LP installed and configured.

**Comment by chandni-agarwal** [comment]
Hi @ToddKlindt,

Can you help me with steps for manual installation. I I cannot install it from CLI due to some restrictions. So can you please help me with it. Thanks!.

**Comment by dcashpeterson** [comment]
@chandni-agarwal the instructions that @ToddKlindt provided should assist you with installing Learning Pathways manually. The errors you are receiving are because you are running the script against a different version of the PnP PowerShell library. If you follow his instructions should you be able to do the installation.

**Comment by chandni-agarwal** [comment]
Hi @dcashpeterson, I meant the manual installation of powershell module. I am asking about this is because of parameter "-AllowClobber". Does the manual installation of SharePointPnPPowerShellOnline includes any additional measure?

**Comment by ToddKlindt** [comment]
The "`-allowclobber`" parameter sounds scarier than it really is. :) You have the `PnP.PowerShell` module installed, and it and the module you're trying to install, `SharePointPnPPowerShellOnline`, have a lot of functions that have the same name. Without the `-allowclobber` parameter `Install-Module` won't install` SharePointPnPPowerShellOnline `because of that overlap in function names. Imagine if I wrote a malicious module that had a function called `Connect-PnPOnline` and that function send me your credentials before it connected you to SPO. To keep bad guys from sneaking stuff like that in, `Install-Module` stops installing the module and lets you know there is an overlap in function names. 
You are wise to question some random guy on the Internet telling you to run `-AllowClobber`. :) Go ahead and run `Install-Module -Name SharePointPnPPowerShellOnline `without it. You'll get a pretty good error message explaining the problem and telling you to run it with `-AllowClobber`. 
If you have more problems, post here. We'll help you out.

**Comment by dcashpeterson** [comment]
Closed as answered. If you are still having an issue please create a new issue.
