### ISSUE TITLE
Customize the playlist administration playlist assets

### ISSUE THREAD

**Issue by aisa0906** [pnp/custom-learning-office-365#58]
The playlist administration lists allow you to customize the lists; hide or show playlists depending on what you want to train your users on or have configured in your tenant. But within an each playlist asset, there are some "steps" that we may not have yet release or configured in our tenant that we do not want to train our users on. I would expect that the playlist assets are configurable as well. to hide/show. Instead, I need to create an entire new playlist even if there is a set of 8 steps in the playlist asset and only 1 is not needed; I need to create one with the 7.

example: Playlist Details: OneDrive QuickStart
Playlist Asset - step 4:  Set up your mobile apps  ( not everyone is licensed for mobile so we do not want this but we would need to recreate the entire Playlist without this step)

**Comment by peterjkrebs** [comment]
Thanks you for the feedback. We are currently looking at ways to best handle the scenario you mention. We can't promise a timeline but it's something we definitely want to include in our future roadmap.

**Comment by juliemturner** [comment]
We believe we've addressed this issue the best way we can given the complexities by adding a "Copy Playlist" feature that will allow you to duplicate any playlist so that you can customize it, which would allow you to remove any steps you don't want or reorder them. This new feature was released in version 3.
