### ISSUE TITLE
Some customized learning pathway modules cannot be opened in the admin view anymore.

### ISSUE THREAD

**Issue by Annanas-12** [pnp/custom-learning-office-365#596]
We have some problems loading certain customized learning pathway modules. The following error message is thrown: 
![image](https://user-images.githubusercontent.com/85163358/137868905-f65316bd-78be-4c9f-92ae-1216f0b8a590.png)
Instead of getting the normal admin learning pathway view, we only receive a blank space for these modules. In the learning viewer, the modules are still visible. 

### To Reproduce

> We copied one of the existing learning path modules and added some assets. 
 The learning pathway can be openend in the viewer mode and all assets are visible. When opening the assets pane in the admin area, we only see a blank space.
 
![image](https://user-images.githubusercontent.com/85163358/137899520-8c8c2037-a3c1-4571-a334-b5a8358716e3.png)
 
When copying this module, the asset area is still blank, while copying the originial module leads to a correct working module. 
We tried to open the affected module in several browser versions and cleared the cache but that didn't help.  This is the case for two learning path modules.

### Expected behavior

> We want to open the learning pathway module in the admin area and see all associated assets (similar to this screenshot). 
![image](https://user-images.githubusercontent.com/85163358/137900109-60369889-bcbd-444b-b6bf-49d9eb4cd033.png)

### Learning Pathways version number
4.1.4.0

**Comment by dcashpeterson** [comment]
@Annanas-12  Thanks for reaching out. We will need some additional information in order to assist you. Can you please use the issues template and fill in all the parts with steps to reproduce the issue? We are happy to help, this just isn't a lot to go on.

**Comment by Annanas-12** [comment]
@dcashpeterson I tried to extend the bug report, please tell me if you still miss some information.

**Comment by dcashpeterson** [comment]
@Annanas-12 I am trying to reproduce this issue and am not having any luck reproducing it. This is what I am doing to try and reproduce it. Let me know if this isn't what you are doing.

1. Navigate to the Admin Center
2. Click on Microsoft Teams in the left navigation
3. Click on Manage Meetings
4. Click Copy Playlist
5. At this point for you the list of assets is empty???

**Comment by dcashpeterson** [comment]
@Annanas-12 I did some more digging on this and while I still can't reproduce it I think the issue is that there is an asset that has some bad data in. Here is my suggestion.

- Make a not of the custom playlist and custom assets that you are using
- Delete the Custom Playlist that isn't working
- Create a new Copy of the playlist and make sure that works as expected.
- One at a time add back in the assets that you have in the playlist that isn't working and test after each asset is added. You will need to find the one asset that isn't working. I assume that this is a custom asset and there is some missing data.
- Once you find the asset that isn't working try to edit it to fix any issues with the data or recreate it and ensure it works.

Give these steps a try and let us know how things go.

-Derek

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new ticket and reference this one.
