### ISSUE TITLE
[QUESTION] Fetch Error When Adding Content Pack

### ISSUE THREAD

**Issue by KRReilly** [pnp/custom-learning-office-365#610]
### What is the context of your question

- [x] Custom Content

### What is your question

>Unsure the reason for 'fetch error'. When searching https://krreilly.github.io/IT-Enablement/index.html/ our forked repository, the page loads however we are also getting a 404 error when adding to Sharepoint as a new content pack. Please see screenshot with errors below: 
<img width="1726" alt="Screen Shot 2021-11-22 at 11 43 35 AM" src="https://user-images.githubusercontent.com/93666495/142901043-20fb03ae-6026-4bd4-94f9-24ac67c643c3.png">

Could this be a problem with the forked repository or the permission settings on our Sharepoint page?

**Comment by dcashpeterson** [comment]
Hi @KRReilly, In general when we see this error it is because github is going to be blocked by your firewall. Is this a development tenant or a company tenant. If it's a company tenant you might need to have the url put on the allow list. If this is a developer tenant then it could be that your repo is private.
