### ISSUE TITLE
Assets become not visible in CustomLearningAdmin

### ISSUE THREAD

**Issue by Mike4IT** [pnp/custom-learning-office-365#615]
## Describe the bug

Several playlists clearly have assets within them and can be accessed as a user in the CustomLearningViewer.aspx but when you look at that playlist in CustomLearningAdmin.aspx, assets are invisible and "+ New Asset" button is not present. 

The custom playlist in question is a copy of one created by Microsoft, the original by Microsoft currently being hidden. Here is the playlist in question:
![image](https://user-images.githubusercontent.com/95828431/145298899-5defdd2d-b49b-4cbe-8a20-031448350081.png)
Here is the section to view the assets and the missing "+ New Asset" button.
![image](https://user-images.githubusercontent.com/95828431/145302213-c03ec3f9-1900-44bd-9e48-62b401d63f3d.png)

### Expected behavior

We should be able to see the assets and be able to add/remove them. Here's what other, still functioning, playlists look like:
![image](https://user-images.githubusercontent.com/95828431/145302445-91c72159-435c-47ef-8e9a-cab14f9c14c2.png)

### Learning Pathways version number

4.3.1

**Comment by amitkh22** [comment]
Hi @Mike4IT, Thank you for bringing this to our attention. I tried creating a custom playlist by creating a copy from the original playlist and was able to see the assets and was able to add/remove assets from it.

Can you please share the steps to reproduce this issue?

**Comment by Mike4IT** [comment]
Hello @amitkh22, thank you for your quick reply! 

I can also create new playlists and be able to add/remove assets to them. What happens is that only some of my older playlists have that issue, not all of them.

Let me explain to the best of my ability what I did and what I see happening:
-Microsoft provides a list of playlists offered under the various categories/subcategories which can't be modified. Since I need to be able to control the content offered on the site, I hid all of the Microsoft original playlists.

-Then, I went into every Microsoft playlists and created a copy of each of them which creates exact copies which I could modify. I didn't make major modifications yet, I kept the playlists titles and descriptions the same and only removed a few assets here and there that we didn't like, based on our environment requirements. We have these playlists at least since April 2021. I was able to go back to them and view the assets and still make modifications as required through most of the year.

-I didn't really make any changes to the playlists on the site since. Only lately, I've been wanting to review all the content on the site and noticed that when I go to "some" playlists, the issue above appears when I can't see the +New asset button. Of course, I could delete them and start over but I don't have a track record of every single asset modifications we made in the past. I can't even view what it contains before deleting it and creating a new one. Now, this "blank playlists" issue is starting to appear all over the site in almost every product such as SharePoint, Teams, and more.

-I know we went through a few updates since April and we updated the site within a week when patches became available. We are now at the latest 4.3.1.  

I hope this describes the situation well for you. I can't think of anything else that has been done. It was working fine before but now the playlists seems to be hit-and-miss.

**Comment by Mike4IT** [comment]
@amitkh22 
Oh yes, I forgot to mention that we have a main tenant and a test tenant and it is happening on both. 

I didn't make a full item per item investigation on it yet... but it "seems" like it is affecting the same playlists. As an example in the Teams product, here are the playlists affected by this issue in both tenant:

- Explore apps and tools
- Work with posts and messages
- Upload and find files
- Manage meetings

Here are the playlists in the Teams product that still works on both tenant:

- Teams Quick Start
- Intro to Microsoft Teams
- Collaborate in teams and channels
- Start chats and calls
- Manage your activity feed
- Teams on the go

I hope this helps!

**Comment by dcashpeterson** [comment]
@Mike4IT I have seen this happen before. It generally happens when there is an element in the playlist with bad data. For example, an asset is deleted but it's still attached to a playlist or a GUID is changed. Check the administration screen and see if there are any orphaned items. I check for this when we do a content update but something might have slipped through the cracks. If you know you can see one of the playlists in question then try to create a new playlist and add the items you can see one by one and see if that works.

**Comment by dcashpeterson** [comment]
@Mike4IT You are probably already seeing the admin screen if you can create a new playlist. https://mytenant.sharepoint.com/sites/MYSITE/SitePages/CustomLearningAdmin.aspx. Orphaned items usually only happen on during the upgrade process but it's good to check for them. In your earlier explanation you said you upgraded. Did you create the custom playlists and then upgrade from version 3-4 or were these all V4 upgrades? Do the Microsoft playlists work? 

This sounds like a data issue with those playlists. Because these are copies of the Microsoft provided playlists it's hard to troubleshoot as there could be custom assets in the playlist, someone could have deleted the data from any of the custom config lists, an upgrade from V3->v4 could have failed. Depending on your level of comfort with JSON you could try to get the data from the customization list and check the GUIDs of the assets. Each custom playlist has an entry in the CustomPlaylists list and every custom asset has an entry in the CustomAssets list. If you didn't add custom assets to the playlists then any asset attached to the playlist should be found in our repo in the docs/learningpathways/v4/en-us folder. You can search by ID of the asset. For example Explore Apps and Tools under Teams should have 2 assets (e.g. 089ff1b2-6cd7-4e86-ab50-a4390b4bcb21). If you run across a GUID that you can't find in the list let me know and I can search the history for it. Try that and see if you can pinpoint the issue. My guess is that this is an issue with a custom asset(s) or some issue with an upgrade.

I know that's a lot but many different things could cause this issue.

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue.
