### ISSUE TITLE
[QUESTION] Teams Deep Links not showing

### ISSUE THREAD

**Issue by larbre** [pnp/custom-learning-office-365#644]
I came across this video showing Teams deep linking https://www.youtube.com/watch?v=howBVCQ2fqs (around minute 6) and tried it myself in three different tenants. It always only shows the SPO deeplinks, not the teams based ones.

**Comment by Ashwini-Shrirao** [comment]
@larbre, thank you for reporting this issue. 

Request you to provide steps you followed. This will help us to understand the issue better.

**Comment by larbre** [comment]
I used the Teams App provided here https://github.com/msft-teams/tools/tree/master/M365%20Learning%20Pathways - uploaded it to my tenants, created policy and everything required to add the app to teams. All is working fine. I wanted to use teams links to directly get into the app when sending information to users. According to the video linked in my first post all you need to to is open the app within teams and using the link button should give you a deep link to Teams but it only shows the SPO versions:
![image](https://user-images.githubusercontent.com/12843764/157177754-10370900-9230-4af1-97bd-f2a3d0df1441.png)

**Comment by v-ashrirao** [comment]
@larbre Thank you for your patience. We are looking into this and will let you know once we have some solution for it.

**Comment by dcashpeterson** [comment]
hi @larbre,
I looked into this and spoke with the person that created the video. The short answer is that the Getting Started Teams app doesn't support deep linking. The tabs are brought in via an IFrame into Teams. Because of that the webpart doesn't actually know it is in Teams. What was shown in the video was a custom Teams app that link directly to a Teams Personal app. You can create one of these yourself using App Studio in Teams. 
[manifest.json.txt](https://github.com/pnp/custom-learning-office-365/files/8223109/manifest.json.txt)
![color](https://user-images.githubusercontent.com/45491456/157656816-2bb1752b-1d0b-46c4-9fe3-c62be1e27584.png)
![outline](https://user-images.githubusercontent.com/45491456/157656826-4cf9bc10-efda-41fd-a206-c016edb0fe29.png)

- Take the manifest file I am providing here rename it to be manifest.json
- Click on App Studio from the left rail in Teams
- Import an Existing app
- Upload the Manifest
- On the App Details tab add the images you would like to use or use the ones I am providing
- On the Tabs tab click on M365LP ... to edit the tab
- Under Content URL Replace <YOUR TENANT> with the name of your tenant (e.g. contoso.sharepoint.com)
- Under Content URL Replace <LEARNING PATHWAYS SITE> with the url of your learning pathways site. (e.g. M365LP)
- Click Save
- Click on Test and distribute
- Click Publish > Publish to yourorg app catalog (This will send the app to the Teams admin center for approval) > Submit
- You need permissions to approve apps in Teams to approve this
- Navigate to the Teams Admin Center https://admin.teams.microsoft.com/
- Teams Apps > Manage Apps > Search by name "M365"
- Click on M365 Learning Pathways
- Click Publish
- The app is now available for everyone in your org

I hope this helps sorry for the confusion.

**Comment by larbre** [comment]
perfect, I now got the point! So the main difference is the referenced URL for the tabs! It works as you described!
While the one I used is based on something like
https://somedomain.sharepoint.com/_layouts/15/teamslogon.aspx?SPFX=true&dest=/sites/somesite/SitePages/Get-started-with-Microsoft-Teams.aspx

it should be like
https://somedomain.sharepoint.com/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/sites/somesitename/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=someid%26forceLocale={locale}
