### ISSUE TITLE
Can't reach (old) page CustomLearningAdmin.aspx 

### ISSUE THREAD

**Issue by Durksweb** [pnp/custom-learning-office-365#647]
## Describe the bug
At issue [624 ](https://github.com/pnp/custom-learning-office-365/issues/624 ) i mentioned that we should do a manual installation for a new Microsoft 365 learning pathways site. So i did.

Now on the old installation, which is a seperate site collection, i **can't** reach the page /CustomLearningAdmin.aspx
On the new installation, which is also a seperate site collection, i **can** reach the page /CustomLearningAdmin.aspx

I now no longer have access to our scenarios and playlists on the old Learningsite. I also cannot reach them from the frontend because that was the problem and therefore we decided for a new installation.

I have gone through all the steps as mentioned in https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup and mentiond at https://github.com/pnp/custom-learning-office-365#manually-installing-and-configuring-microsoft-365-learning-pathways. 

I tried another browser, admin account, deleted cookies but nothing did help.

**Comment by v-ashrirao** [comment]
@Durksweb Thank you for reporting this. Please allow us sometime to check this. We will get back to you at the earliest.

**Comment by dcashpeterson** [comment]
@Durksweb You can't have more than one Learning Pathways site be active at a time because they all operate off the tenant app property which can only be set to one thing at a time. So it is expected that the webpart wouldn't work in the old site. 

My advice if you had customizations in the old site would be to use a tool (like ShareGate) to copy the assets from the old site pages library to the new site pages library and then manually recreate the metadata for the assets and click use existing asset instead of creating a new page for the asset. That will be much safer.

You could potentially access the data directly from the configuration lists and try to copy the data over with a migration tool but this is risky as there are many hidden fields with configuration data in it. In addition, if the customized items didn't have the correct metadata or language data then copying them over might not work properly. This would not be the recommended approach.

Try navigating to https://<YourTenant>.sharepoint.com/sites/<YourOldSiteName>/_layouts/15/viewlsts.aspx?view=14
Custom Assets are in the SitePages library
Metadata for Custom Assets is in the CustomAssets list
Custom Playlists are in the CustomPlaylists list
Custom Subcategories are in the CustomConfig list with a title of CustomSubCategories.

**Comment by v-ashrirao** [comment]
@Durksweb, is there any other information you need on this? If not, can we close the issue?

**Comment by Durksweb** [comment]
@v-ashrirao sorry i did not answer earlier. You may close this topic. Thx
