### ISSUE TITLE
 microsoft learning paths : access for guest users?

### ISSUE THREAD

**Issue by abpolspoel** [pnp/custom-learning-office-365#649]
>**PROVISIONING NOTE**: If you are having issues with the SharePoint look book while trying to provision M365 learning pathways please do not post that issue to this repo as we cannot help you here. Please post all questions and issues for the SharePoint look book to [SharePoint/sp-provisioning-service GitHub Issues List](https://github.com/SharePoint/sp-provisioning-service/issues).

>**WEB PART NOT LOADING**: If you are getting the error: "Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance". Please review the [Diagnosing Pre-Check](https://github.com/pnp/custom-learning-office-365/blob/main/installation/DiagnosisPreCheck.md) guidance before submitting your bug.

## Describe the bug

I added the webpart for MS learning paths, it's working fine for all users except for guests. Is it possible to grant guest users access?

error message : Microsoft 365 learning pathways has a configuration issue. Ask your administrator for assistance. [Administrators: Please see the browser console for detailed logs. For technical assistance check out the issues list at https://github.com/pnp/custom-learning-office-365/issues.]

+ trace in attach

### To Reproduce

>access sharepoint site as a guest user

### Expected behavior

>MS learning path content to load as for internal users.

### Screenshots

see error message in description

### Learning Pathways version number
4.3.1.0

### Additional context

>Add any other context about the problem here.
[trace guest.txt](https://github.com/pnp/custom-learning-office-365/files/8305263/trace.guest.txt)

**Comment by v-ashrirao** [comment]
Hi @abpolspoel , Thank you for reporting the issue.
We assume that external sharing is configured in order to allow guest users to access the site.
However, in order to access Learning Pathways webparts and its functionality, guest users will also need read access to the tenant app catalog.

https://techcommunity.microsoft.com/t5/sharepoint-developer/site-collection-app-catalog-external-users/m-p/153777/highlight/true#M4280

You can also refer below issues 
https://github.com/pnp/custom-learning-office-365/issues/481
https://github.com/pnp/custom-learning-office-365/issues/83

Please let us know if additional details are required.

**Comment by v-ashrirao** [comment]
@abpolspoel , is there any other information you need on this? If not, can we close the issue?
