### ISSUE TITLE
Can I use one instance of Learning Pathways on 2 Modern SP sites? I have a site that is dedicated to MS Teams and we are using LPW there. But want to expand and use playlists for the remaining tools. Thanks!

### ISSUE THREAD

**Issue by Darkstar307** [pnp/custom-learning-office-365#653]
Can I use one instance of Learning Pathways on 2 Modern SP sites? I have a site that is dedicated to MS Teams and we are using LPW there. But want to expand and use playlists for the remaining tools. Thanks!
### What is the context of your question

- [ ] Installation
- [x] Learning Pathways Content
- [ ] SharePoint Success Content
- [ ] Administration
- [ ] Custom Content
- [ ] Viewer Web Part

### What is your question

>Provide related screen-shots to help us understand your question

**Comment by v-ashrirao** [comment]
@Darkstar307, Thanks for your interest in the app.
It is possible to add the Learning Pathways web part to other site collections instead of only having it on the default provisioned Communications site.
You can only have 1 master learning site per tenant. That site collection is where content is provisioned and administrated. All users that you intend to view your content need to have view access to that site but they do not need to use it as their main learning site, although you can. You can then use the learning pathways viewer web part in any other site collection and configure the web part to show all, or only a subset of content.

**Comment by dcashpeterson** [comment]
Closed as answered. If this doesn't answer your question please open a new issue and reference this one.
