### ISSUE TITLE
Request for Learning Path URL for whitelisting

### ISSUE THREAD

**Issue by batilcl** [pnp/custom-learning-office-365#66]
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [x] Additional article idea

Customer need a list of URLs that Learning Path uses for whitelisting purpose. The environment by default blocks everything and only whitelist when required.

O365 services is published  URLs here,
https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges

However the URLs that Learning Path's uses are different from the list published above.
Example: **_pnp.github.io/custom-learning-office-365, akamaized.net_**, ... doesn't exists as part of O365 URL list

I can run a trace to get the URL but customer is not confident that this will be the full list. Chances that their users hit an inaccessible page does exists.

**Comment by justin-lisi** [comment]
Hello,

All of the source content references for the web part are pulled in and managed through the https://pnp.github.io/custom-learning-office-365 endpoints so if a wildcard exception for that endpoint can be implemented, that would be ideal (if you'd like to avoid wildcards we can look into providing you the specific endpoints themselves but those may change in the future so a wildcard is best). Otherwise, the content itself is loaded through https://support.office.com which is included in the O365 published URLs link you posted prior (the same goes for URLs like spoprod-a.akamaihd.net). Let me know if this helps or if there are any other questions. Thank you!

Regards,
Justin
