### ISSUE TITLE
[ENHANCEMENT] Re-name the default categories

### ISSUE THREAD

**Issue by bongo-ho** [pnp/custom-learning-office-365#669]
I would like to be able to rename the default Categories in the Admin UI.
![image](https://user-images.githubusercontent.com/49170074/170011881-e6417dd7-824c-4cd0-8b56-2dd529af9a83.png)

**Comment by dcashpeterson** [comment]
@bongo-ho Thank you for your suggestion for an enhancement. We discussed this as a project team when we created the architecture and decided against offering this as a feature due to performance reasons. I will keep this on the enhancement request list and we can see if other users would benefit from this enhancement but at this time we will not be moving forward with this. If we get sufficient requests for it we can see if we can put it on the backlog.

**Comment by bongo-ho** [comment]
Thank you for your response Derek. I would like to better understand how a change in display-labelling on the page category impacts the webpart and content load-performance to extent it is detrimental to solution? Is there any additional design documentation I can have a look-at incase I've missed something when unpacking the sppkg and JSON? I've picked-over the videos, wiki and docs but its quite limited on the apps design (other than content packs and playlists). Links greatly appreciated.
Cheers.

**Comment by dcashpeterson** [comment]
@bongo-ho All the Microsoft provided data comes from the CDN. That data is translated into 10 different languages. If we need to check for deltas between what is in the CND and any customizations every time we rebuild the cache then it would take the cache a very long time to build. That is why we chose not to go that route but to provide the opportunity to change that data with a custom content pack. We don't have specific documentation on the architecture but you can check out this YouTube video that explains the architecture. https://www.youtube.com/watch?v=S-QFDNRZkGE
