### ISSUE TITLE
 CustomLearningViewer.aspx shows a blank page for some users

### ISSUE THREAD

**Issue by Janieih** [pnp/custom-learning-office-365#674]
CustomLearningViewer.aspx shows a blank page for some users, regardless of web browser. Some are using Google Chrome, IE and others Edge. The page is loading so you can see the local and global site navigation and header, but the CustomLearningViewer with content is not showing. 

Learning Pathway version: 4.3.1.0

**Comment by v-ashrirao** [comment]
@Janieih, Thank you for reporting this. We would need some more details to figure out the reason behind this.
Please confirm if users see error in browser console. If yes, please share the screenshot of that error.
Also confirm if this is happening with new installation or after upgrading to 4.3.1.0 version.

**Comment by Janieih** [comment]
Hi. No error in browser console. This has been an issue over time. Thus has happened both before and after upgrading to 4.3.1.0 version.

**Comment by dcashpeterson** [comment]
@Janieih I was on holiday and as this is a community effort, I don't arrange coverage. We need more information here in order to troubleshoot. A screen shot of the error, reproduction steps, what kind of assets are not showing (custom or Microsoft), something that would help us. I know you said there is nothing in the console but there are generally no reason why the web part would not display and also not show an error so if you could please check that again.

**Comment by Janieih** [comment]
That's understandable. Nb. Don't share this email externally.

Here's an attached screenshot of the error. The link they are using is this one: https://yara.sharepoint.com/sites/digitalworkplacelearninghub/SitePages/CustomLearningViewer.aspx?cdn=Default&subcategory=aa63dafe-cc26-4139-b43f-3634f520826f (don't share this externally). It's a custom asset (referring to SharePoint pages).

Janne Huse
Email: ***@***.******@***.***>
[Yara - Knowledge Grows logo]
Yara International ASA
Drammensveien 131
N-0277 Oslo, Norway
www.yara.no<https://www.yara.no>

**Comment by dcashpeterson** [comment]
@Janieih I deleted your update because when you respond via email it doesn't include any attachments. It also adds in lots of personal information such as your domain and location. If you can add the screen shot from the browser and add a comment via the web that would be great. If it's a custom asset check the permissions on the site pages library to ensure that the user has access to that site.

**Comment by Janieih** [comment]
Unfortunately, I'm not allowed to share the screenshot to the public, as this is a company SP site..

All end-users in the company have permissions to view the site.

**Comment by dcashpeterson** [comment]
Feel free to redact the content but without a kind of error there really isn't any other support I can offer. With no way to reproduce it and no documentation on what is happening there isn't much else I can offer.
