### ISSUE TITLE
Exporting Changes or Customizations to another Sharepoint Tenant

### ISSUE THREAD

**Issue by shirazgaff** [pnp/custom-learning-office-365#679]
We hide playlist that are nor required for our clients. We have also re arranged the navigation to what is more appropriate to our clients. few other Text changes as well.

I Need to know instead manually making these changes for each client if this can be exported. ?

**Comment by dcashpeterson** [comment]
@shirazgaff I am not sure I understand your question completely. Are you saying you have made changes to the visibility of out of the box playlists and created copies of the playlists so that you chance the titles or have you created a custom content pack? Any customizations you make are stored in the Config lists that are stored in the CustomConfig, CustomPlaylist, and CustomAsset lists. If you need to back that content up you can export the contents to a CSV and import it to another instance of learning pathways. If you have a custom content pack then you own that fork so you can do what you want with it and just point new instances of learning pathways to the custom CDN and they will get your changes. I hope this helps and thanks for using Microsoft 365 learning pathways.

**Comment by shirazgaff** [comment]
I will give example as I am not really a developer

We remove Yammer from the Playlist and change the text on ask questions page

How can I have this repeatable for a new client or tenant, instead of manually doing this as our client profile is similar?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dcashpeterson** [comment]
@shirazgaff You might need to get a developer involved in this case. Regarding removing Yammer it depends on how you did it. I am going to guess that you did it through the administration screen so you would need to export the data from the lists as i mentioned above. If you made changes to the content on the learning pathways site pages themselves (e.g. ask-questions-and-get-help.aspx) then you can either export the entire site using [PnP Site Provisioning ](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine)or using a migration tool.
