### ISSUE TITLE
Sorry, something went wrong - Trying to provision

### ISSUE THREAD

**Issue by AdamPJones** [pnp/custom-learning-office-365#68]
- [x] Bug

#### Expected or Desired Behavior
Trying to Provision Microsoft 365 learning pathways per instructions

#### Observed Behavior

Successfully signed in to https://provisioning.sharepointpnp.com/home/details?packageId=3df8bd55-b872-4c9d-88e3-6b2f05344239 as a tenant administrator

accepted the permissions

Browser clears and after waiting get the following error:
Sorry, something went wrong
There was an unexpected issue. Please try again after a while.
IDX21324: The 'nonce' has expired: '[PII is hidden]'. Time from 'nonce': '[PII is hidden]', Current Time: '[PII is hidden]'. NonceLifetime is: '[PII is hidden]'. 

at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateNonce(OpenIdConnectProtocolValidationContext validationContext) at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateAuthenticationResponse(OpenIdConnectProtocolValidationContext validationContext) at Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationHandler.<AuthenticateCoreAsync>d__1a.MoveNext()

#### Steps to Reproduce
Tried a few times ended up with the same result.

**Comment by juliemturner** [comment]
@AdamPJones Unfortunately your issue is related to the SharePoint online provisioning service and not Microsoft 365 learning pathways which means we have no expertise to be able to assist you. You will need to submit this issue to their repository to get assistance which is at[ https://github.com/SharePoint/sp-dev-docs/issues]( https://github.com/SharePoint/sp-dev-docs/issues).

**Comment by AdamPJones** [comment]
Thanks, resubmitted as suggested.
