### ISSUE TITLE
Introduction WIP WE security causes blocked Learning Pathways webpart

### ISSUE THREAD

**Issue by SylvM1** [pnp/custom-learning-office-365#680]
Dear Community,

In our company we are introducing WIP WE (Windows Information Protection Without Enrollment) to force our users on private devices (bring your own devices) to enroll their device in Intune and can continue to use Office 365 desktop apps but in a secure manner. We have also made sure that if users choose to not enroll their device in Intune, that they will get limited acces (web only) when they use Office 365 functionalities (such as Teams, Outlook etc.) -> for details see: https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices

All users that cannot (old windows versions, MacOS etc.) or do not want to enroll their device in Intune however cannot use Learning Pathways anymore. The webpart of learning pathways does not seem to load properly anymore because of this limited acces (web only) setting. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/57954528/177533950-73233e3e-8553-494a-951e-51afb8e3a197.png)

This is a big problem because all our Office 365 e-learnings are now in Learning Pathways. We have many users working from home on devices such as MacBooks or other non Windows OS that cannot follow our e-learnings anymore. 

Is this a known issue? It seems weird that such settings disable or block a solution that is also a Microsoft (and hence trusted) solution? Hopefully there is a solution, please let me know!

With kind regards,

Sylvester Muts

**Comment by dcashpeterson** [comment]
@SylvM1 This is a pretty unique situation but my guess is that the users have app catalog blocked so they can't access the web part or possibly the CDN. Is there anything in the browser console? The issue is that the users trying to use learning pathways are having their access blocked by the policies. Check the console and see if there are any errors and feel free to post them here. I can look at them but given that these types of settings are unique to each company my suggestion would be to reach out to the team at your company involved in those settings and make sure that there are exceptions made for learning pathways.

**Comment by dcashpeterson** [comment]
@SylvM1 The error in yellow is based on your access policies. Learning Pathways has nothing to do with those errors. The errors in the UI are because the web part can't access the files that it needs to load the page. This is caused by one of two things. 1) The web part isn't loaded properly or there was an error during installation. Based on the fact that some users can access the web part correctly I doubt this is the cause but if it is this can be resolved by reinstalling the web part and ensuring that it deploys without error. 2) Access to the files in the app catalog are not accessible. Based on the fact that your organization added new access policies, my guess is that those files are being blocked for users on an unmanaged device. I would reach out to the folks that set up the access policies and ensure that they set up access for users to the app catalog. This isn't just a learning pathways issue it will affect any custom web part you install.
