### ISSUE TITLE
[ENHANCEMENT] Multi-select Audiences

### ISSUE THREAD

**Issue by tandrasi** [pnp/custom-learning-office-365#690]
### What is the context of your question

- [ ] Installation
- [ ] Learning Pathways Content
- [ ] SharePoint Success Content
- [x] Administration
- [ ] Custom Content
- [x] Viewer Web Part

### What is your question

Is it possible to select multiple audiences per playlist? Right now I don't think there is or am unaware of a configuration option which would make this possible. If a change is made, it would have to be on both the Administration and Viewer Web Part side of things.

It seems logical that a playlist could be targeted towards, say, a Change Manager and a Content Editor.

![image](https://user-images.githubusercontent.com/72114492/182738058-8dad5be6-262b-4ce0-a0a1-f75bdd5e72d6.png)

I'm prepared to take the code and modify it myself so please let me know if I've missed something :).

Many thanks!

**Comment by v-prigunasek** [comment]
Hi @tandrasi , 

Thank you for submitting your query here. Unfortunately, there is no option available in the webpart to configure the Audience dropdown to MultiSelect. This has to be changed/configured in the code only and it requires changes in multiple other places which will impact the current functionality, so I will let @dcashpeterson to advise on this.

Hi @dcashpeterson, Could you please advise on this query? Thanks

**Comment by dcashpeterson** [comment]
@tandrasi Thanks for the interest in adding multiple audiences. This is an open source project and we would welcome your contribution. If you would like to submit a PR for this that would be great. A few things to keep in mind here. 

- This might require an update to the data model - if so that will require a major version update and with that an update path (see Update Service)
- As you mentioned you would need to update both the Admin web part and the Content web part
- This change would only apply to custom content as the Microsoft provided content only supports 1 audience.

Please reach out in this ticket if you have any questions.

**Comment by tandrasi** [comment]
@dcashpeterson hi, just an update, I had a quick look and it's relatively simple, but the client has opted for a different approach meaning that we no longer need multiple audiences (well, they declined the additional cost of development time) so I won't be able to complete this work. Even if it would take me a couple of hours, I'm stretched very thin in professional and personal life.
