### ISSUE TITLE
Removing or Disabling Admin Success Centre for Site Members or all users[QUESTION] 

### ISSUE THREAD

**Issue by shirazgaff** [pnp/custom-learning-office-365#692]
Please see the screenshot below , I don’t want regular users or site members to be able to access the admin success Centre. I Have removed the button on the top menu. However there is another tile in the screenshot below. Will removing the tile button and menu button for Admin Success be the best way to achieve this? Lastly will this not break anything.

![image](https://user-images.githubusercontent.com/31412544/184331356-940852f3-c96a-4659-9474-6373222eb70a.png)

 
I

**Comment by v-prigunasek** [comment]
Hi @shirazgaff ,

I see you want to restrict the access to this page /SitePages/Learning%20pathways%20Admin%20Success%20Center.aspx. 

The better way to do that is to manage the access on that specific page. Go to Site Contents -->Site Pages --> Select the "Learning pathways Admin Success Center" page and click on More ( 3 dots) icon --> Manage access and then "Stop Sharing" for the users/groups that no longer need access to that page.

![image](https://user-images.githubusercontent.com/98514691/184387483-9f73d9c8-d595-4756-a8a0-115806b81c92.png)

This way, the link in the Mega menu will be visible only for users who have access to that page, others cannot see that link. So you don't need to manually remove it there.

![image](https://user-images.githubusercontent.com/98514691/184388180-9ef10596-b03b-4578-8bee-04f40f51c8b4.png)

However the button in the Home page will be still visible for all users but the users who don't have access to the "Learning pathways Admin Success Center" page will get an Access denied error when they click on it.
![image](https://user-images.githubusercontent.com/98514691/184388376-8ccf4822-e869-44b5-be3d-7696b24651c6.png)

![image](https://user-images.githubusercontent.com/98514691/184388742-1405bf21-c647-4638-829a-7e404cd80869.png)

If you are fine with this, you can keep that button otherwise it can be removed from the Home Page.

Please let us know if you need any additional details.

**Comment by shirazgaff** [comment]
Perfect .thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
