### ISSUE TITLE
Search returns results that are from the hidden playlists and assets

### ISSUE THREAD

**Issue by Rafou2** [pnp/custom-learning-office-365#70]
On the latest version of the site, when doing a search from inside the viewer field "Search for Playlists and Assets" then the returned results show items that exist in the hidden that I want to hide from users. For example, even when the "Outlook/Set up and customize" playlist is hidden, a search for "Set up" returns "Set up Gmail accounts" when it should stay hidden.

#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
The search should not return hidden content, Thks

#### Observed Behavior
See above

#### Steps to Reproduce
For example, even when the "Outlook/Set up and customize" playlist is hidden, a search for "Set up" returns "Set up Gmail accounts" when it should stay hidden.

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
So this is a gray area.  Assets can be used in multiple playlists. So, even though you've hidden a playlist, that doesn't hide the assets because that could break other playlists that depend on it. That said if you tried to search for the playlist you hid, it wouldn't show up, and also if you hide an entire technology none of the assets or playlists associated with that technology will show up.  We do not at this time have the idea of hiding a particular asset, and therefore search will show them. We will look into doing so in future releases but at this time that is not a supported scenario.

**Comment by FormerlyJelly** [comment]
Closing due to advanced age and lack of further response

**Comment by juliemturner** [comment]
This is an enhancement request and needs to remain open until Microsoft team has a chance to review and decide if the enhancement can be addressed.

**Comment by juliemturner** [comment]
After discussing with the entire team, we feel like to limit the search scope would create more problems regarding finding assets to use in other playlists and/or potentially blocking assets that are used in other playlists.  As such we think currently this is not something we'll address. However, if you have a specific scenario that you're trying to address and being able block certain assets from being searched is required please open a new issue and reference this one so that we can address your particular need.
