### ISSUE TITLE
 SharePoint Success site not configuring correctly upon provisioning

### ISSUE THREAD

**Issue by JCcoding120** [pnp/custom-learning-office-365#705]
## Describe the bug

When we follow the steps to provision the SharePoint Success site, we are noticing that the site does not provision as expected - with key Learning Pathways functionality within the site failing to install correctly. When we provision the site via the provisioning page, there is no prompt that follows after the provisioning stage reaches 'Provisioning completed'. There is no new 'CustomLearningAdmin' tab in the browser that provides the 'Complete' option and there is no email received to confirm successful provisioning (as it states should happen). 

When I view the error reports in the console as per recommendation from this community, the following errors are shown:

M365LP:CustomDataService (getCustomConfig) No configuration was found for CDN a748d357-1879-436f-96fc-20dd1fed87bb and Language 
M365LP:DataService (getMetadata) Fetch Error: Not Found
M365LP:DataService (refreshCache) Could not retrieve metadata from CDN source: https://pnp.github.io/custom-learning-office-365/learningpathways/v4/
M365LP:CustomLearningWebPart (configCDN) -- Could not get a valid configuration; Please contact your learning administrator.
M365LP:CustomLearningWebPart (firstInit) - TypeError: Cannot read properties of null (reading 'TelemetryKey') -- Could not initialize web part.

### To Reproduce

We follow the steps from the SharePoint Success provisioning guide here (https://learn.microsoft.com/en-us/sharepoint/provision-sss). This included ensuring that the Learning Pathways site was on the most recent version, that a Global Admin was completing the operation and that they were the App Catalogue administrator.

### Expected behavior

The Learning Pathways-enabled webparts should load correctly, with SharePoint assets being available to the user in a Learning Pathways-style interface.

### Screenshots

![SharePoint Success site not configuring correctly error](https://user-images.githubusercontent.com/118176119/201641750-28efd697-6e19-4f38-bbdb-f654bdc6486f.PNG)

### Learning Pathways version number

4.3.1.0

**Comment by v-prigunasek** [comment]
Hi @JCcoding120 ,

Thanks for reporting the issue here.

Can you perform the below steps?

1. From the learning pathways Home menu, select Learning Pathways Administration.

![image](https://user-images.githubusercontent.com/98514691/201656112-db5ccbbb-594c-4cff-811f-0499ec54b367.png)

2. Select the ellipses (...) and then select Add Content Pack.

![image](https://user-images.githubusercontent.com/98514691/201656157-11824eb2-8121-449f-96fc-789c05b34371.png)

3. Select SharePoint Success Site.
4. It will open the SharePoint Success Site provisioning page in a new tab, and you have already provisioned this site.
5. Click on the previous "CustomLearningAdmin" tab and click on the Complete button on that page.

![Screenshot (236)](https://user-images.githubusercontent.com/98514691/201656483-564e73ab-5b28-4c9f-8056-0897f413f4e6.png)
6. Once you click on "complete" button, you will see the "SharePoint Success Site" custom content pack added in the page
![image](https://user-images.githubusercontent.com/98514691/201656823-dd4931e6-5918-41cf-bf04-d1f39d302121.png)
7. Then navigate to SharePoint Success Site that you already provisioned, select Get Started > Plan your site.

**Comment by JCcoding120** [comment]
Thanks, much appreciated!
