### ISSUE TITLE
Provision Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by mark-lane** [pnp/custom-learning-office-365#71]
The provisioning service requires these permissions (see attachment) 
![inst_perms](https://user-images.githubusercontent.com/51422802/58994044-de99df80-87b4-11e9-8e59-2ff7950e5bc4.png) to create the tenant app catalog, install the application into the tenant app catalog and provision the site template. 

Although we just want the basic online catalog of Microsoft training content - our Security team cannot live with "read and write items and lists in ALL SITE COLLECTIONS". We all realize this is how its set up to provision so question we have in mind is, can we provision and then subsequently, after provisioning, remove the that permission? If so, can you please send us instructions on how to do so? Please remember a few things: 
1) We realize that MS says no harm will come from this setting - Okay we'll just trust a third party - NOT
2) We just need the basic functionality to get our users some additional training tools
3) is there an alternative provisioning method such as: https://docs.microsoft.com/en-us/office365/customlearning/custom_manualsetup

Please help us get to a point where we can install and have our Security team love it too! 

Thanks,
Mark 

![inst_perms](https://user-images.githubusercontent.com/51422802/58994470-36851600-87b6-11e9-8084-9670bdd91c0c.png)

**Comment by juliemturner** [comment]
You certainly could follow the manual deployment instructions and circumvent the need for allowing the app registration access.. 

Just to clarify a misconception, the provisioning service is a microsoft app registration so it isn’t 3rd party but certainly if your security people are concerned there is the manual work around.

**Comment by mark-lane** [comment]
Thank you, we will try manual work around....and funny....MS is a third party to us - we don't work for them - they work for us 😊

**Comment by juliemturner** [comment]
I did not intend to imply that you work for Microsoft.  I was just making sure there was no confusion. Normally the term 3rd party implies there is a 3rd entity involved. So you the customer are the 1st party. Microsoft the vendor is the 2nd party and by aspect of you using their service it implies a level of trust. Wholly agree that if then there were a 3rd party either another vendor or a consult that would be much more concerning from a security perspective. I wanted to make sure it was clear for anyone else reading the thread that Microsoft (ie the 2nd party) provides the provisioning service and are therefore the party seeking those permissions and not a 3rd party (ie another vendor or consultancy). Absolutely understand that some organizations still don’t feel comfortable with that which is why we provided the manual install option to give your admins more visibility into the process.
