### ISSUE TITLE
Sources in SOC - the /client endpoint? Searchable? Any index?

### ISSUE THREAD

**Issue by emwes** [pnp/custom-learning-office-365#73]
#### CATEGORY

- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Is there a way to explore or search Support.office.com for this new **/client** endpoint (https://support.office.com/en-us/client/{id}?embed=true&ns=trainingservices&version=1) ?

#### Observed Behavior
When you create custom playlists and extend the Custom Learning solution, it would be great to know what resources at support.office.com there is to refer to (**as an url**)? The other way - to create local assets in the site library - doesn't seem like a good Evergreen way to go?

Please advise,

BR / Emil

**Comment by juliemturner** [comment]
When you create a custom playlist, there is the option to either search or add a new asset to that playlist.  Search is looking at articles coming from Microsoft (i.e. support.office.com or docs.microsoft.com pages) or custom assets you added which would be pages in a library in your tenant.

With regard to your comment about creating local assets, this is a storage mechanism by which a consumer of learning pathways can assemble either their own pages and/or the Microsoft provided pages together into their own custom playlists. Since the playlists are specific to your own needs, Microsoft is not providing a separate secured storage area outside of SharePoint for this content.

We hope to provide even more flexibility to the creation and maintenance of customized content as the solution evolves.

**Comment by emwes** [comment]
Thanks for quick reply @juliemturner.

Yes, I experienced that the search function in playlist editing gives an answer "Is there any good help for...". But two problems I encounter:
1. Have I put the search question right? I don't get any match?
2. Is there any material in our prefered language?

Being able to browse/search the SOC content **index** for the **/client** endpoint would be a much easier way I think.

BR / Emil

**Comment by juliemturner** [comment]
To answer your first question, yes we had only the most basic search implemented in the first version of the UX. You're not the only one who would like to see more options there and we have plans to do so in future releases.

To answer your second question we are looking at implementing a solution to bring resources in for the preferred language, this is tied in part to Microsoft supporting multilingual pages as well as us expanding our manifests to support pointing to the language variations of Microsoft assets.  This is all WIP and I cannot give you an exact date that we'll be releasing it but it is a current effort.
