### ISSUE TITLE
Page CustomLearningAdmin not available 

### ISSUE THREAD

**Issue by Magali12345** [pnp/custom-learning-office-365#744]
Hi all,

I have set up the M365 learning pathways site on a client tenant. But I can not access the Custom Learning Admin page that allows to hide content. The page is empty (see picture below). 
The page Custom Learning Viewier is fully accessible, as well are the training content.

Do you have an idea on how to solve this issue?

Thank you 🙂

<img width="932" alt="image" src="https://github.com/pnp/custom-learning-office-365/assets/136699809/493a4500-2aa0-4849-864a-d586a5f706a6">

**Comment by v-prigunasek** [comment]
Hi @Magali12345 , 

Thanks for reaching out to us. 
By any chance, have you installed Learning Pathways in 2 different site collection? You can't have more than one Learning Pathways site be active at a time because they all operate off the tenant app property which can only be set to one thing at a time. So, it is expected that the webpart wouldn't work in the old site.

If you have only installed the Learning Pathways in one site collection, then please open the admin page and share us the console logs to look into the errors for further troubleshooting. Thanks!

**Comment by Magali12345** [comment]
Hi @v-prigunasek 
Thank you for your reply. No I haven't installed the site in 2 different site collection. 
We manage to solve the problem with my colleague by running a powerShell script. It seemed to be a missing property in the page library.

**Comment by ISCSimonFinlay** [comment]
Hi @Magali12345, 
I've recently come across this issue, would you be able to provide some additional detail about what property was missing from the page library? Thanks in advance.

**Comment by ISCSimonFinlay** [comment]
Hi, I've fixed this issue. The issue for me was the Microsoft Learning pathways site collection url set in the storage entity had a forward slash at the end of the url. Therefore when the admin web part loaded, it said the urls were not the same. Example: 
https://contoso.sharepoint.com/sites/learningpathways/ - incorrect
https://contoso.sharepoint.com/sites/learningpathways - correct
