### ISSUE TITLE
Wrong video in Recommended Playlist

### ISSUE THREAD

**Issue by Rafou2** [pnp/custom-learning-office-365#75]
There is the wrong video in the default Recommended playlist: 
'Create impactful content together' show the same video as 'Save and share files with OneDrive' when it should be about collaborating on content.

Can you please have someone QC all the default content ?
Thank you

#### Category

- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Thanks for your contribution! Sharing is caring.

**Comment by peterjkrebs** [comment]
Thank you for the feedback. We are in the process of updating the content. In some cases, videos are shared among scenarios - but we agree with you it's not a good experience and will be fixed in the upcoming updates. We do QC all our content.

**Comment by Rafou2** [comment]
Question: for an existing Learning site with some custom content already, how will we benefit the updated content in coming upgrades ? 
Can we keep our existing configuration and load the new content, OR will we need to reload a fresh site and reapply any configuration ? Thks

**Comment by juliemturner** [comment]
All the Microsoft provided content is updated every time you run the admin web part because it loads the manifest files from out repository which is external to the web part.  The viewer web part uses a cached version of this information which expires every 24 hours and then the first person to hit it after 24 hours refreshes the cache for everyone.  So you will automatically receive any modifications to Microsoft's content in sometime less than 24 hours after release.

**Comment by Rafou2** [comment]
Thank you Julie, so I understand that I will both benefit from the new content AND get to keep all the custom configuration, custom Assets and custom playlist. Just checking :-)
