### ISSUE TITLE
 Content URLs appear to be pointing to broken pages

### ISSUE THREAD

**Issue by ChrispyBites** [pnp/custom-learning-office-365#750]
## Describe the bug

Users accessing content in the Learning Pathways solution are seeing embedded pages without working videos.  The videos never load.

### To Reproduce

Verify the pages are broken to end users:
1. Open any playlist from Learning Pathways.
2. Navigate to a playlist item with a video.
3. Video fails to load with a static "Please wait while the media loads."

To verify that source links are broken: 
1. Navigate to the Learning Pathways administration page.
2. Open any playlist.
3. Locate an asset with a video, open the associated URL in the browser.
4. Video fails to load with a static "Please wait while the media loads."

As an example, a broken page for the asset **Get started with Microsoft Teams**:
https://support.office.com/en-us/client/b98d533f-118e-4bae-bf44-3df2470c2b12?embed=true

### Expected behavior

Accessing any page with a video should display a functional video player with the expected content.

### Screenshots

Broken video in Learning Pathways frame:
![broken_video_app](https://github.com/pnp/custom-learning-office-365/assets/6919243/7b1ce44d-ec89-4096-af98-c09dceac06f1)

Broken video accessing URL directly from Learning Pathways Administration:
![broken_video_link](https://github.com/pnp/custom-learning-office-365/assets/6919243/bb5f2e8b-66d3-4b77-9296-43c30bc44dde)

### Learning Pathways version number
4.3.1.0

**Comment by dcashpeterson** [comment]
@ChrispyBites Thank you for reporting this. We will see what we can do to get to the bottom of it. M365 doesn't control the content on these pages just the curation of the playlists but we can bring it to the attention of the correct folks.

@jhwang-ms this is a rehash of #496 which was reported a while ago. Previously it was only happening in IOS but I can confirm it was happening on a PC as well using Edge. Is this something you can look into?

**Comment by exactmike** [comment]
I can confirm this issue - seeing it on multiple tenants that have deployed the M365 Learning Pathways app.  It consistently happens from multiple network locations. My testing has been with Windows 10 / 11 machines running Edge and I also tested with Chrome.

**Comment by justinfabin** [comment]
I as well...I just deployed the Learning pathways to determine if our institution could use the resource.

**Comment by v-prigunasek** [comment]
@ChrispyBites  - This issue seems to be resolved now and it is working as expected. Can you please check and confirm?

**Comment by justinfabin** [comment]
It is, thank you!


Justin Fabin

Saint Vincent College

Chief Information Officer | Information Technology Department

Office: 724.805.2669 | Service Desk: 724.805.2297 | ***@***.******@***.***>



Please remember that Information security is everyone's responsibility.

________________________________
From: v-prigunasek ***@***.***>
Sent: Wednesday, August 9, 2023 4:05 AM
To: pnp/custom-learning-office-365 ***@***.***>
Cc: Fabin, Justin ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [pnp/custom-learning-office-365] Content URLs appear to be pointing to broken pages (Issue #750)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

⚠ This email was sent from outside of the Stvincent.edu email system.

Do not click links or open attachments unless you recognize the sender and know the content is safe. ⚠

@ChrispyBites<https://github.com/ChrispyBites> - This issue seems to be resolved now and it is working as expected. Can you please check and confirm?
