### ISSUE TITLE
Breadcrumb is visible when you get down to the asset layer despite being hidden up until this point

### ISSUE THREAD

**Issue by tiapatel** [pnp/custom-learning-office-365#76]
When using the web part, I have opted to hide the breadcrumb and only display the content. This works when viewing the list of playlists for a product, however when the user gets to the assets, they are able to see the breadcrumb.

Would it be possible to only display the content throughout the journey?

**Comment by juliemturner** [comment]
If you check I suspect you'll see that's because you're being redirected to the CustomLearningViewer.aspx page away from the page with the web part on it.  That is done because without the top navigation area you can't get to the playlists controls.  Yes we could in a future release separate those things but today that's how it works as certain controls need to be on the page even though you've specifically turned them off when viewing the assets of a playlist.

**Comment by juliemturner** [comment]
This feature has been enhanced and updated in the latest 3.x release, please update your web part and if you have further feedback please open a new issue.
