### ISSUE TITLE
 New Version of the Microsoft 365 learning pathway Not Working after upgrade

### ISSUE THREAD

**Issue by JoNico5** [pnp/custom-learning-office-365#760]
## Describe the bug

Upgraded the SharePoint app catalog with the new version of the Microsoft Learning Pathways app. Installed it into Teams, and when I click on the app, I get an error message

"Sorry, something went wrong
Can't load the application on this page. Use the browser Back button to retry. If the problem persists, contact the administrator of the site and give them the information in Technical Details.
[TECHNICAL DETAILS](https://berkshirehealthcare.sharepoint.com/_layouts/15/error.aspx?ErrorCorrelationId=82c8f4a0-20f5-7000-bf31-fac6d1bc5a65&ErrorText=Can%27t%20load%20the%20application%20on%20this%20page.%20Use%20the%20browser%20Back%20button%20to%20retry.%20If%20the%20problem%20persists%2C%20contact%20the%20administrator%20of%20the%20site%20and%20give%20them%20the%20information%20in%20Technical%20Details.&ErrorDetails=Error%3A%20Error%20initializing%20application.%20Error%3A%20TypeError%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27componentType%27)&ErrorCategory=spfx&Workload=TeamsWebPartApplication&Name=SpfxLoad#)
Error details: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

[Troubleshoot issues with Microsoft SharePoint Foundation.](javascript:HelpWindowKey('WSSEndUser_troubleshooting'))
Correlation ID: 82c8f4a0-20f5-7000-bf31-fac6d1bc5a65

Date and Time: 12/5/2023 6:21:54 AM"

### To Reproduce

>Go into Microsoft teams and find the Microsoft Learning teams app click open which produces the error message.

### Expected behavior

>To load the Microsoft learning path apps

### Screenshots

![image](https://github.com/pnp/custom-learning-office-365/assets/104829479/e9393b2e-6c46-49ab-9ea5-99b3f55e75eb)
![image](https://github.com/pnp/custom-learning-office-365/assets/104829479/52574402-78f2-4bfc-ac0c-081330ebcd03)
![image](https://github.com/pnp/custom-learning-office-365/assets/104829479/500a0f40-033f-4129-934a-38d485d66de6)
![image](https://github.com/pnp/custom-learning-office-365/assets/104829479/dc368a91-df24-4891-8579-5e87e55cb650)

### Learning Pathways version number

>Please share the version number of learning pathways in your tenant app catalog 4.4.0.

### Additional context

>Before the upgrade, the owner of the Learning Pathways changed the URL name in the SharePoint communication site. We ran the PowerShell URL script to reconfigure the app, which installed without errors, but we're not sure if this is also causing the errors. The old app is still present along with the new app.

**Comment by v-asshrirao** [comment]
@JoNico5, Thank you for reporting this. Please allow us sometime to analyse the issue and we will get back to you ASAP.

**Comment by v-asshrirao** [comment]
@JoNico5, We tried from our end but we are not able to reproduce the issue. We tried to upgrade from v4.0+ to latest version.
Can you please provide below details to help us understand the root cause of this issue?
1. What version you are upgrading from?
2. Do you have any custom config settings?
3. Is multilingual settings enabled?

If you are upgrading from version 4.0+, can you please try to clear all entries from custom config list and try to check if you are getting same issue?

**Comment by dcashpeterson** [comment]
@JoNico5 you can try to remove the config files and any custom items that point to the old URL. I would expect that if that was the case that they would be erroring out in the browser as well. It's the same code running in Teams. To clear the cache you need to go to the Learning Pathways site => Site Contents => CustomConfig. Delete everything with the title CustomConfig. 

Depending on what is in the CustomAssets or CustomPlaylists if there is data in there with the old URL you should clear that out as well.

Try to do that and let us know if that fixes the issue.

**Comment by JoNico5** [comment]
@dcashpeterson I have removed all custom config that contained the old name and it is still producing the same error.  Is there a way to reload the learning path but still keep the content that is on the comms site?

**Comment by dcashpeterson** [comment]
@JoNico5 if you want to delete everything then you can remove all items from the CustomConfig list and the customasset and customplaylist lists. This will however remove any custom playlists you have created. It will also remove the custom assets from Learning Pathways but not the pages that were created so if you have a page in the new site in the Site Pages library that page will still be there. You would need to create a new asset and link it to that page.

That said, because this works in the browser and not Teams. Without doing the above, you can uninstall the SPFx package and make sure that you empty the trash in the app catalog, remove the app from Teams and make sure you can't see it from the Teams admin center. Then once you can confirm that it was deleted you can reinstall the SPFx package and sync the package to Teams.

**Comment by JoNico5** [comment]
OK lovely I will give that ago

**Comment by dcashpeterson** [comment]
Closed. If this is still an issue please open a new issue and reference this one in the comments.
