### ISSUE TITLE
Requesting the ability to duplicate a category, subcategory, playlist, and assets [ENHANCEMENT] 

### ISSUE THREAD

**Issue by robsoto1** [pnp/custom-learning-office-365#792]
**Describe the solution you'd like**
Sometimes content needs to be duplicated because there is enough overlap between courses to afford that approach. The option to duplicate should be available at every level of the custom learning administration screen. Your SharePoint web parts all have the "duplicate" option so I assumed it would be a native feature with this tool. 

**Additional context**
One of my clients today was quite disappointed by these limitations. She has hours of extra work ahead of her because she can't duplicate with ease. We figured the three-dot ellipsis in the upper right would offer that option. If you do add this enhancement, it would be an appropriate menu to offer the "duplicate" option.

**Comment by dcashpeterson** [comment]
@robsoto1 Can you please provide more details on what you are asking for? Some of what I think you are describing is by design and some is available through custom content packs. 

The Categories and Subcategories are not able to be copied by design as the Microsoft content team is responsible for those. If you need to copy those you can fork this repo and create a custom content pack giving you complete control over the contents of Learning Pathways. 

Playlists can be copied in the admin interface. Assets should not be copied as the idea is you would create one assets for a particular topic and then use it in multiple playlists. There is a search feature when adding assets to the playlist to help support this.

**Comment by robsoto1** [comment]
I'm referring specifically to the custom subcategories in the admin screen. There should be an option for "Copy this subcategory".

[cid:3b46f8fc-7039-4c1d-ba4e-ee04e41e0f07]

I was hoping for that option because in every other web part in SharePoint Microsoft has a "duplicate" option. I figured it would be possible here.

Assets should still be able to be copied/duplicated because sometimes you want a similar page layout but not identical. Being able to create a similar page


Rob Soto
Modern Workplace Advisor / Coach | Managed Services
. . . . . . . . . . . . . . . . . . . . . . 
Office: (512) 605-3916
After Hours Support: (877) 211-7658
TSXV: QUIS or OTCQX: QUISF

________________________________

**Comment by dcashpeterson** [comment]
@robsoto1 Thanks for making this request. As I mentioned in my previous response the ability to copy a category and sub-category is not included by design as Microsoft organizes that content and we want to ensure consistency in those assets across all users. If you need control over those you can use a custom content pack. For assets you can use the out of the box copy functionality in the site pages library. Thanks for using Microsoft 365 Learning Pathways. We will not be moving forward with this enhancement request at this time. Thank you.
