### ISSUE TITLE
What endpoints need to be unblocked to install in a DoD IL5 tenant?

### ISSUE THREAD

**Issue by andresmdc** [pnp/custom-learning-office-365#797]
### What is the context of your question

- [x] Installation

### What is your question

>I am a FTE with Microsoft supporting a DoD customer that wants to install Learning Pathways in their IL5 tenant. In speaking with others that have done the installation in DoD tenants, they only had to make a small change to the PowerShell script to point to https://$TenantName.sharepoint.us. However, in our case, I believe that there are certain endpoints (starting with Github.com) that are being blocked. I am asking if there is any documentation on what endpoints should be unblocked for a successful installation.

**Comment by dcashpeterson** [comment]
@andresmdc the webpart gets the manifest file from https://pnp.github.io/custom-learning-office-365/learningpathways so that needs to be accessible in any environment regardless if it is GCC or not. From what I understand Microsoft Learning Pathways does run in GCC environments with some changes to the install script as you mentioned and sites opened in firewalls but that is not something we "officially" support as we don't have a GCC tenant to test in.

**Comment by dcashpeterson** [comment]
Closed as answered
