### ISSUE TITLE
 Teams app does not load Learning Pathways 

### ISSUE THREAD

**Issue by M365Admin0529** [pnp/custom-learning-office-365#814]
We get 401 error when clicking learning Pathways from Teams or just a blank screen.

**Comment by dcashpeterson** [comment]
@M365Admin0529 We need more information on the error. Please fill out the issues template with as much information as you can including the app manifest. If you are referring to this app https://github.com/msft-teams/tools/tree/master/M365%20Learning%20Pathways not working then you can open an issue in that repo but my suggestion would be to manually create the app as the Teams app manifest schema has changed since that code was last updated. You can manually create the app using the Team Developer Portal app in Teams.

**Comment by M365Admin0529** [comment]
Hello @dcashpeterson thank you for the information. How do I open an issue in that repo?

**Comment by dcashpeterson** [comment]
@M365Admin0529 you do it the same way you created an issue here. You go to the repo and click on issues and then create a new issue. I will caution you though that in looking at the issues that are in the list it doesn't look like anyone from the team that created the app has responded it in many years. As I mentioned above, I think the best course of action is to use the Teams Developer Portal and create a new Teams app manually and add the links that you would like to add as tabs in the app. You can even upload the images that are in the solution as your icon images.

**Comment by dcashpeterson** [comment]
closed as answered
