### ISSUE TITLE
 OneNote Content Blank

### ISSUE THREAD

**Issue by dcashpeterson** [pnp/custom-learning-office-365#815]
All the content in the OneNote playlists is blank with the exception of OneNote Quick Start.

**Comment by CollinHunterGOC** [comment]
Any updates?

**Comment by melissamrywilliams** [comment]
I was able to find a URL for the OneNote training videos that will work in the Learning Pathway's iframe.  
The Microsoft OneNote training videos are located: https://support.microsoft.com/en-us/office/onenote-video-training-1c983b65-42f6-42c1-ab61-235aae5d0115

For each video - navigate to that video, capture the Guid from the end of the link and insert that GUID before the ? in this URL:
https://support.office.com/en-us/f1/topic/(insert GUID here)?embed=true
For example, the URL for the content "What is OneNote" is:
https://support.office.com/en-us/f1/topic/be6cc6cc-3ca7-4f46-8876-5000f013c563?embed=true

In the Learning Pathways site, I hid the original OneNote playlists that don't work, copied those playlists, added Assets under each playlist with the new URLs, and they all work.

Since the original links are hidden but still there, they can be activated when Microsoft or a Learning Pathways update  fixes them.

**Comment by dcashpeterson** [comment]
@melissamrywilliams and @CollinHunterGOC  I have rolled out a fix for the OneNote content issues. You will need to clear the cache in Learning Pathways to see the changes. This should be rolled out to all languages.

**Comment by CollinHunterGOC** [comment]
Thanks
