### ISSUE TITLE
Web part not loading unless users present in AppCatalog hidden user list

### ISSUE THREAD

**Issue by TinVoiceDragon** [pnp/custom-learning-office-365#83]
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

I found the Microsoft 365 learning pathways web part wasn't loading, instead presenting people with the message below.

I first deployed the solution on 17/06/19 through the pnp provisioning site, which installed version 2.0.15. I upgraded the solution to 2.0.16 on the 19/06/19, but the error remains.

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
[SPLoaderError.loadComponentError]:
***Failed to load component "141d4ab7-b6ca-4bf4-ac59-25b7bf93642d" (CustomLearningWebPart). Original error: ***Failed to load URL 'https://DomainName.sharepoint.com/sites/AppCatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/v2-customlearningwebpartstrings_en-us_550d233e4c4642a78860ff6ed0424b18.js' for resource 'CustomLearningWebPartStrings' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). There was a network problem.

***INNERERROR:
***Failed to load URL 'https://DomainName.sharepoint.com/sites/AppCatalog/ClientSideAssets/26c9cd9f-db62-49b1-b102-7f0dad281ea0/v2-customlearningwebpartstrings_en-us_550d233e4c4642a78860ff6ed0424b18.js' for resource 'CustomLearningWebPartStrings' in component '141d4ab7-b6ca-4bf4-ac59-25b7bf93642d' (CustomLearningWebPart). There was a network problem.
***CALLSTACK:
Error
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-06-14.010/sp-pages-assembly_en-gb_c7b6711d19abfa8f337923db195fc22d.js:870:15940)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-06-14.010/sp-pages-assembly_en-gb_c7b6711d19abfa8f337923db195fc22d.js:1493:21274)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-06-14.010/sp-pages-assembly_en-gb_c7b6711d19abfa8f337923db195fc22d.js:1493:16198)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-06-14.010/sp-pages-assembly_en-gb_c7b6711d19abfa8f337923db195fc22d.js:1493:12223)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2019-06-14.010/sp-pages-assembly_en-gb_c7b6711d19abfa8f337923db195fc22d.js:1493:61761)

#### Steps to Reproduce

Going into the AppCatalog user information list:
https://DomainName.sharepoint.com/sites/AppCatalog/_layouts/15/people.aspx?MembershipGroupId=0

I found the issue was only occurring for those who weren't listed. I can reproduce the issue by deleting a user from this list, and fix it by making it so a user is added into the list.

As a workaround to get names into this list I've created a new security group in the AppCatalog site collection, but not assigned it any permissions in the AppCatalog site and then added individual users into this unused group.

Unfortunately I don't get the fixed behaviour if I add the broader user item of "All Users (Membership)" into this security group, it has to be individual users, and I'm not convinced this should be necessary anyway.

Is this behaviour correct?

**Comment by juliemturner** [comment]
@TinVoiceDragon unfortunately you're issue is with your tenant and the configuration of it and your app catalog and not with this solution particularly.  You would have this issue with any SharePoint Framework solution you tried to deploy. You absolutely should not and should not have to change the permissions in the app catalog site to have SharePoint framework solutions work but you are correct in that your workaround seems to highlight what the issue is. I may be able to assist you in getting started in solving the issue, or identifying it more deeply but I'm not sure I can help you fix it and you may need to contact support.  So... moving forward... 

1. By default the security settings for the app catalog look something like the screen shot below. Note that "Everyone except external users" has read access. In my case there is no single person in any of the other groups, however, all the Office 365 tenant admins are site collection administrators of this site collection. If your security settings do not look like this, they should, unless they were changed for a very specific reason and then you need to identify the trade-offs for why the security change was made and your desire to get this solution to work.

![image](https://user-images.githubusercontent.com/7570936/60269173-f4825800-98bb-11e9-958a-6081462444b6.png)

Assuming your permissions look like the image above here are some other things to think about:

2. Can you verify that you don't have a vanity Office 365 domain name, by that I mean your SharePoint sites and your app catalog are are in the https://<mydomain>.sharepoint.com/.... domain?
3. Can you verify that all of the people with issues are external users, i.e. guests in your tenant?
4. Do you know if you've enabled the SharePoint public CDN?

**Comment by TinVoiceDragon** [comment]
Answering out of order, as I think point 1 is where the difference is, but I feel the need to answer every question for completeness!

4 - We haven't enabled the SharePoint public CDN (checked with and Get-SpoTenantCdnEnabled which shows as False for both public and private CdnType).

3 - All the people having issues were internal users (so no, not guests).

2 - We don't have a vanity domain name, the app catalog does sit under https://OurDomainName.sharepoint.com/sites/

1 - Our AppCatalog site permissions are different.
"Everyone except external users" isn't present, although the three default groups are the same as your screenshot (Owners = Full Control; Members = Contribute; Visitors = Read;), in our case these three groups are empty with no members.

I think then you may be about to say that a requirement is for "Everyone except external users" (or some equivalent group) to have some degree of access to the whole site?  (and potentially for this to work for guest users I'd have to add "All Users (membership)" instead?)

I think there was a part of me hoping that wasn't necessary, as the AppCatalog site feels like it should be this hidden thing in the background, inaccessible to your regular user...

**Comment by juliemturner** [comment]
So yes, you have to have them have read access to the site, which is why that's how it's set by default. Effectively the app catalog site is where the source code is served from, so by not granting them access to the site you're effectively saying they can't load any of the code from it.  By giving them read access there really isn't anything they can do there so I'm not sure that it's something you should be concerned about but yeah, I mean for it to work you have to do it that way so they can read the files they're serving up.  I can't say that I've personally every tried changing the setup.  Possibly if you changed it to serve of the content from a public CDN you could then remove the need for users to have read access but I doubt it because I would think they would still need to read the manifest file.. and then I suspect they wouldn't actually be able to add any of the apps to other site collections.  I think you should strongly consider setting it back to the way it's set by default.

**Comment by juliemturner** [comment]
Closed to lack of activity

**Comment by alimurtaza9266** [comment]
Hi @juliemturner 

I am not sure if my question is relevant to this post or not but I am getting the same error for **guest users only**.

When a user from the organization goes to the sharepoint site, all the webparts load perfectly and there is no error. When a guest user tries the same, "Tiles" Web part does not load and the following error appears.

![Tiles not loading for guest user](https://user-images.githubusercontent.com/61438143/76181885-d4f74980-6216-11ea-8d91-9ee51fcc6404.PNG)

- Guest User has access to the site.
- Other web parts of the site are loading and working fine.

Any help would be much appreciated.

Thanks

**Comment by juliemturner** [comment]
@alimurtaza9266 - Your issue is most likely that guest users do not have access to the app catalog by default.  You would need to give them read rights to it.  If you have further issues please open up a new issue as comments added to closed issues can tend to be overlooked and lost.
