### ISSUE TITLE
Notification of additional content

### ISSUE THREAD

**Issue by eriksv-ms** [pnp/custom-learning-office-365#95]
#### Category

- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

New content being made available should have a notification UI element showing that that content is newly available for users.

#### Observed Behavior

From customer DANA.COM:

Noticing that you can have playlist and then addition content to each, but there is no way for the user to see there is additional content or what that even is. It kind of defeats the purpose of playlist. I actually did not realize what was happening until today when test. The sub content (or additional content in the playlist) can only be accessed in order and by a arrow that has no description what so ever. You do not know how many content pieces are in the playlist for that playlist. This would be the equivalent of having a folder for your MP3 and not know what the next song is or how to go to the next song (also flipping through each one until you got to the one you wanted. 

#### Steps to Reproduce

- Add new content to a playlist
- View the playlist

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by juliemturner** [comment]
@eriksv-ms  -- In the viewer today there is a section where you can see the assets in the playlist but the positioning is not ideal. 

![image](https://user-images.githubusercontent.com/7570936/60899730-f394e300-a238-11e9-89e4-17cb732ebf17.png)

Some of our original design that made this a better experience had to be abandoned due to other technical issues with the Microsoft content being shown in the iFrame. That limitation has been overcome and a updated version of the web part will change this behavior so that the contents of the playlists are more obvious as well as indicating in the UX what things have been updated recently. However, it is currently only the plan to do with with content from Microsoft not custom playlists.  If you are interested in different functionality or other enhancements please submit a request to the [User Voice](https://microsoftteams.uservoice.com/forums/913429-learning-solutions)

**Comment by eriksv-ms** [comment]
Does the customer need to reinstall the web part or is there a different mechanism to update it?

Regards,

Erik

**Comment by juliemturner** [comment]
@eriksv-ms -- If you're asking when this feature comes out will the user have to update the web part using the update instructions [here](https://github.com/pnp/custom-learning-office-365), then yes, they will have to manually update the web part using the instructions to get the new features when they're available.  The admin page will notify a user that there is an updated web part available.

**Comment by juliemturner** [comment]
closed to inactivity
