### ISSUE TITLE
Provision issue Microsoft 365 learning pathways

### ISSUE THREAD

**Issue by BintMi** [pnp/custom-learning-office-365#98]
#### Category

- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

We are facing issues with adding the "Microsoft 365 learning pathways" to our tenant.
Already checked the prerequisites. It gets stuck with the following messages and nothing happens. 

**Validating site URL ...
Validating prerequisites ...**

Please can you help
Thanks

![image](https://user-images.githubusercontent.com/52733444/61116344-8d0c0100-a494-11e9-9a69-aa85010d94bf.png)

**Comment by juliemturner** [comment]
@BintMi  -- Unfortunately your issue is related to the SharePoint online provisioning service and not Microsoft 365 learning pathways which means we have no expertise to be able to assist you. You will need to submit this issue to their repository to get assistance which is at https://github.com/SharePoint/sp-dev-docs/issues.
